### PR TITLE
Option to run networkchaos tests on hostNetwork pods

### PR DESCRIPTION
**Pull request by svanellewee**
Signed-off-by: svanellewee <stephan.van.ellewee@gmail.com>

### What problem does this PR solve?

This brings back the ability to optionally run chaos testing on pods with `hostNetwork` set to `true`. I realize this is a dangerous option, but our tests depend on this functionality 

We migrated our chaos tests to `v1.0.0` that allowed this, but it seems after v1.0.1 this is no longer allowed.  This is not intended for use on production clusters.

### What is changed and how does it work?
This adds an environment variable `ALLOW_HOST_NETWORK_TESTING` to the chaos controller manager. 

When this is enabled (set to "true") it will allow testing of networkchaos on weave-pods or whatever has `hostNetwork: true`

### Checklist

Tests
No unit tests have been created yet, but I will add them if you are happy with me re-adding this behaviour.

- [x] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Manual test:
- Install a new kind cluster as per the CONTRIBUTING.md 
- install the chaos-mesh infrastructure `./hack/local-up-chaos-mesh.sh`
- install a NetworkChaos test as follows:
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-bandwidth
  namespace: "kube-system"
spec:
  action: bandwidth
  mode: all
  namespaces:
  - "kube-system"
  selector:
    labelSelectors:
      "app": "kindnet"
  bandwidth:
    rate: 10mbps  
    limit: 50000  
    buffer: 50000
  duration: "19s"
  scheduler:
    cron: "@every 20s"
```
- inspect the test. It should complain that running this test is dangerous
- modify the chaos-controller and add the `ALLOW_HOST_NETWORK_TESTING` environment variable:

```yaml
      ....
      containers:
      - command:
        - /usr/local/bin/chaos-controller-manager
      ....
        env:
        - name: ALLOW_HOST_NETWORK_TESTING
          value: "true"
      ...
```
- inspect the test again. Error message should be gone, test should proceed.
- I have also been able to confirm with tc on the node that this test is active:

```sh
root@kind-control-plane:/# tc qdisc  show dev eth0
qdisc tbf 1: root refcnt 2 rate 10485Kbit burst 49998b lat 0us  # ---> success
qdisc prio 2: parent 1: bands 3 priomap 1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
qdisc sfq 4: parent 2:2 limit 127p quantum 1514b depth 127 divisor 1024 
qdisc sfq 5: parent 2:3 limit 127p quantum 1514b depth 127 divisor 1024 
qdisc sfq 3: parent 2:1 limit 127p quantum 1514b depth 127 divisor 1024 
root@kind-control-plane:/# 
```

Side effects

- [ ] Breaking backward compatibility

Related changes

- [x] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
This enables pods using host networking to be tested. Not for production use.
```

### CODE REVIEW

**Comment by YangKeao** [comment]
There is another problem for `hostNetwork`: the interface of the host network namespace could be not "eth0", which we have hardcoded in the tc rules 😿

**Comment by svanellewee** [comment]
> There is another problem for `hostNetwork`: the interface of the host network namespace could be not "eth0", which we have hardcoded in the tc rules crying_cat_face

Good point!  May I try make it configurable?

**Comment by YangKeao** [comment]
> 
> 
> > There is another problem for `hostNetwork`: the interface of the host network namespace could be not "eth0", which we have hardcoded in the tc rules crying_cat_face
> 
> Good point! May I try make it configurable?

👍 I think a configurable global option is acceptable (though different nodes may have different interfaces, we can ignore this problem temporarily 😋  ).

**Comment by svanellewee** [comment]
> > > There is another problem for `hostNetwork`: the interface of the host network namespace could be not "eth0", which we have hardcoded in the tc rules crying_cat_face
> > 
> > 
> > Good point! May I try make it configurable?
> 
> +1 I think a configurable global option is acceptable (though different nodes may have different interfaces, we can ignore this problem temporarily yum ).

Thank you! I will add a small addition to the helm chart to allows this to be enabled along with an unit test

**Comment by svanellewee** [comment]
Hello again, I've added a unit tests and a small helm option. Please let me know if I need to add anything else.

Also tested the helm chart manually as follows:

- Used kind:
```sh
kind delete cluster
kind create cluster
```
- Uploaded the docker images to my cluster.

- Set up the helm installation
```sh
kubectl create ns chaos-testing
kubectl apply -f manifests/crd.yaml
helm install -n chaos-testing chaos-test \
        helm/chaos-mesh/ \
        --set controllerManager.allowHostNetworkTesting=true \
        --set controllerManager.image=localhost:5000/pingcap/chaos-mesh:latest \
        --set chaosDaemon.image=localhost:5000/pingcap/chaos-daemon:latest \
        --set chaosDaemon.runtime=containerd \
        --set chaosDaemon.socketPath=/run/containerd/containerd.sock
```
- Then checked that it worked here..
```sh
cat <<"EOF" | kubectl apply -f -
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-test
  namespace: "kube-system"
spec:
  action: bandwidth
  mode: all
  namespaces:
  - "kube-system"
  selector:
    labelSelectors:
      "app": "kindnet"
  bandwidth:
    rate: 10mbps
    limit: 50000  
    buffer: 50000
  duration: "19s"
  scheduler:
    cron: "@every 20s"
EOF
```

**Comment by svanellewee** [comment]
MMmm looks like I might have misread your previous comment on making the ethernet adapter configurable. I will make another PR that does that and link this to that.

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
@STRRL  PTAL

**Comment by STRRL** [comment]
Hi @YangKeao, this PR will introduce a new flag `-allowhostnetworktesting `; However we still use ENV to present most of our configurations, such as `ENABLE_LEADER_ELECTION`, `CHAOS_DAEMON_PORT`;

Shall we re-consider using flags or using env?

**Comment by YangKeao** [comment]
@STRRL My fault. :crying_cat_face: Environment variable seems to be a better choice.

**Comment by STRRL** [comment]
> @STRRL My fault. 😿 Environment variable seems to be a better choice.

(IMO flags are better. 😅)

For this PR, we should keep consistent with other configurations.

HI @svanellewee , could you change the cli flag to env config? You could add a new field in `pkg/config/controller.go`, struct  `ChaosControllerConfig`, and add struct label `envconfig` for it. And helm yaml file also should make changes. Thank you!

**Comment by svanellewee** [comment]
Sure thing, I'll get on that ASAP :-)

**Comment by svanellewee** [comment]
I've made a few updates (also updated the description)

**Comment by svanellewee** [comment]
> Hi @YangKeao, this PR will introduce a new flag `-allowhostnetworktesting `; However we still use ENV to present most of our configurations, such as `ENABLE_LEADER_ELECTION`, `CHAOS_DAEMON_PORT`;
> 
> Shall we re-consider using flags or using env?

Just for reference for whomever might be reading the comments I've updated the description, hence why this no longer applies

**Review by STRRL — APPROVED** [review]
LGTM

Thanks for your contribution! @svanellewee

**Comment by svanellewee** [comment]
It's a pleasure! Thank you!

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
