### PR TITLE
fix: add a resonable ulimit nofile for image-chaos-kernel

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

close https://github.com/chaos-mesh/chaos-mesh/issues/2479

> Problem Summary: Can not build docker image chaos-kernel

### What's changed and how it works?

> What's Changed:

refs to https://github.com/moby/moby/issues/40398, I set up a smaller ulimti nofile.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**: release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Comment by STRRL** [comment]
I think without this PR, it's hard to release both v2.0.4 and v2.1.0, because it stuck the CI. :cry:

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
The content of this PR could also be brought by  https://github.com/chaos-mesh/chaos-mesh/pull/2488 and https://github.com/chaos-mesh/chaos-mesh/pull/2481;

So this PR would just bring several comments. :D

**Comment by STRRL** [comment]
I think we could close this PR because #2488 and #2481 have been merged.

**Pull request closed without merging**
