### PR TITLE
structured event recorder for Workflow

### PR DESCRIPTION
**Pull request by STRRL**
### What is changed and how does it work?

Using structured event recorder for workflow.

I also add more logic in `generateAnnotations()` and `FromAnnotations()`, fallback to json serializer when `encoding.TextUnmarshaler` could not resolve. It is used with array like:
```golang
type NodesCreated struct {
	ChildNodes []string
}
// other methods of NodesCreated implement ChaosEvent
```

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```
Signed-off-by: STRRL <str_ruiling@outlook.com>

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@STRRL CI is broken! Maybe you need to fix it.

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
