### PR TITLE
rename IoChaos to IOChaos

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <keao.yang@yahoo.com>

Just like `HTTPChaos` and `DNSChaos`, `IoChaos` should be `IOChaos`.

Before this pull request, there are both `IoChaos` and `IOChaos` in the code base.

### CODE REVIEW

**Comment by fewdan** [comment]
If you want to change the name of "IoChaos", should "GcpChaos" and "AwsChaos" also be changed to "GCPChaos" and "AWSChaos"?

**Review by g1eny0ung — APPROVED** [review]

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
