### PR TITLE
chore: specify env tags for each branches

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

close https://github.com/chaos-mesh/chaos-mesh/issues/3068

### What's changed and how it works?

- new file `env-images.yaml` for specifying the certain image tag required for current branch/context
- new script `./hack/env-image-tag.sh` for querying this file, usage: `./hack/env-image-tag.sh build-env`, output: `latest`
- related changes in makefile and GitHub action workflow

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by Hexilee — COMMENTED** [review]
The `yq` told me 'Error: unknown command ".build-env.tag" for "yq"' when I run `./hack/env-image-tag.sh build-env`.

**Review by Hexilee — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
> cherry pick to release-2.1 failed

Manually cherry-pick in https://github.com/chaos-mesh/chaos-mesh/pull/3096

**Pull request merged**
