### PR TITLE
api: export one module for a group of api

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

The `controller-tools` (including `controller-gen`) cannot work on multiple go modules, which makes it impossible to generate CRD for multiple versions of API. 

### What's changed and how it works?

In this PR, I moved the `go.mod` and `go.sum` to the `/api` directory, and move the `/api/webhook` to `/pkg/webhook`. All related files have been modified.

### CODE REVIEW

**Comment by STRRL** [comment]
Could you update the https://github.com/chaos-mesh/chaos-mesh/issues/2811? 

And it seems there are lots of webhook-related codes left in `/api`, should we also move them out of `/api`(or in the next PRs)?

**Comment by YangKeao** [comment]
> Could you update the #2811?
> 
> And it seems there are lots of webhook-related (validation and default relates) codes left in `/api`, should we also move them out of `/api`? (or in the next PRs)

It doesn't matter. We can leave the webhook-related codes there (and it will not block the development of multi-version API).

**Review by Andrewmatilde — APPROVED** [review]
LGTM, I think this PR may bring a lot of merge conflicts.

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
