### PR TITLE
Promote "Zhiqiang Zhou" to maintainer

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

> Zhiqiang always stands with Chaos Mesh and looks forward to the long term success of Chaos Mesh. I would try to help Chaos Mesh Community more active and more transparent, make Chaos Mesh as the best project in the chaos engineering area.

From 2020, @STRRL has joined the development of Chaos Mesh, and has mentored many developers to become part of the Chaos Mesh. @STRRL not only accelerates the development of Chaos Mesh, brought many experience of SRE to the community, but also helps the the community to grow stronger/healthier. I'm really glad to hear @STRRL will always stand with the community, and continue to contribute more to the community. I believe, with @STRRL we can build a more helpful / elegant software, and construct a more active / engaging community :beers: 

The following are two questions answered by @STRRL :

## What does becoming a Chaos Mesh Maintainer mean to you? 

Chaos Engineering is a  way to resolve "known unknowns" and "unknown unknowns" for the availability and stability of modern distributed applications. Chaos Mesh is one of the popular OSS projects in the Chaos Engineering area. I am happy that I could contribute to this awesome project!

Becoming the Chaos Mesh Maintainer means the community acknowledged my contributions, like becoming the committer last time. And it means I would be more confident in publishing my opinions and ideas to this project and making Chaos Mesh better.

## Contribution Highlight

- Opened 182 issues and  247 PRs. Resolved 156 issues and merged 229 PRs. Comment with 427 issues and reviewed 515 PRs.
- introduced these features/enhancements with other contributors
  - Chaos Mesh Workflow
  - refine the logging
  - refine the CI from Jenkins to GitHub Action
- Draft the “Chaos Mesh Release Cycle” and become one of the release manager for Chaos Mesh 2.3.0
- Request CNCF for ARM computing resources and setup related CI infrastructure
- Take participant LFX Mentorship as a mentor with Chaos Mesh 3 times

### CODE REVIEW

**Comment by STRRL** [comment]
thanks @YangKeao! 🥰🥰

**Comment by dcalvin** [comment]
@STRRL's contributions and commitement to the project as well as the community are paramount. I am glad to see this PR and nomination - not only because this is a title well deserved for Zhiqiang, but also because Chaos Mesh will have a committed, capable, and loving maintainer for its sustaining propsperity. Congrations, and +1 from me!

**Review by dcalvin — APPROVED** [review]

**Review by cwen0 — APPROVED** [review]
LGTM! 

Thanks for @STRRL's contributions! I believe @STRRL can help Chaos Mesh community to grow!

**Review by xlgao-zju — APPROVED** [review]
LGTM! congratulation 🎉

**Review by g1eny0ung — APPROVED** [review]
LGTM! Zhiqiang made a lot of for the project. I'm glad he can be a maintainer. Congratulations! 🍻

**Review by fewdan — APPROVED** [review]
congratulation!!!

**Comment by WangXiangUSTC** [comment]
congratulation! 👍

**Review by FingerLeader — APPROVED** [review]
LGTM! Congratulations！

**Comment by YangKeao** [comment]
:beers:

**Pull request merged**
