### PR TITLE
generate structural schema

### LINKED ISSUE #1220: Generated OpenApi (openapi/v2) docs are incomplete
## Bug Report

**What version of Kubernetes are you using?**
1.18.2, 1.19.1...

**What did you do?**
Parse generated OpenApi definitions generated by Kubernetes from the applied provided CRDs.
```shell script
$ VERSION="1.0.2" && kubectl apply -f https://mirrors.chaos-mesh.org/v$VERSION/crd.yaml
$ kubectl get --raw /openapi/v2 | jq '.definitions."org.chaos-mesh.v1alpha1.PodChaos"'
```

**What did you expect to see?**
A complete object definition including all [properties](https://github.com/chaos-mesh/chaos-mesh/blob/244be9194c3f6404f8a55ffe806992e66d64b518/config/crd/bases/chaos-mesh.org_podchaos.yaml#L36) and descriptions (CRD validation has them but generated OpenApi JSON doesn't).

**What did you see instead?**
```json
{
  "type": "object",
  "x-kubernetes-group-version-kind": [
    {
      "group": "chaos-mesh.org",
      "kind": "PodChaos",
      "version": "v1alpha1"
    }
  ]
}
```
(Same for every other Custom Resource)

**Relates to:**
- https://github.com/manusa/yakc/issues/23
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### What problem does this PR solve?

Fix #1220 

Docs modification https://github.com/chaos-mesh/website/pull/20

### What is changed and how does it work?

Add `preserveUnknownFields: false` for every kinds of chaos. @manusa The `manifests/crd.yaml` from this PR could work. We will publish it in the next bugfix version.

```bash
chaos-mesh on  fix-1220 [$!] via 🐹 v1.15.5 
✦ ❯ kubectl get --raw /openapi/v2 | jq '.definitions."org.chaos-mesh.v1alpha1.PodChaos"'
{
  "description": "PodChaos is the control script`s spec.",
  "type": "object",
  "required": [
    "spec"
  ],
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
      "type": "string"
    },
    "kind": {
      "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
      "type": "string"
    },
    "metadata": {
      "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
      "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
    },
    "spec": {
      "description": "Spec defines the behavior of a pod chaos experiment",
      "type": "object",
      "required": [
        "action",
        "mode",
        "selector"
      ],
      "properties": {
        "action": {
          "description": "Action defines the specific pod chaos action. Supported action: pod-kill / pod-failure / container-kill Default action: pod-kill",
          "type": "string",
          "enum": [
            "pod-kill",
            "pod-failure",
            "container-kill"
          ]
        },
        "containerName": {
          "description": "ContainerName indicates the name of the container. Needed in container-kill.",
          "type": "string"
        },
        "duration": {
          "description": "Duration represents the duration of the chaos action. It is required when the action is `PodFailureAction`. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as \"300ms\", \"-1.5h\" or \"2h45m\". Valid time units are \"ns\", \"us\" (or \"µs\"), \"ms\", \"s\", \"m\", \"h\".",
          "type": "string"
        },
        "gracePeriod": {
          "description": "GracePeriod is used in pod-kill action. It represents the duration in seconds before the pod should be deleted. Value must be non-negative integer. The default value is zero that indicates delete immediately.",
          "type": "integer",
          "format": "int64",
          "minimum": 0
        },
        "mode": {
          "description": "Mode defines the mode to run chaos action. Supported mode: one / all / fixed / fixed-percent / random-max-percent",
          "type": "string",
          "enum": [
            "one",
            "all",
            "fixed",
            "fixed-percent",
            "random-max-percent"
          ]
        },
        "scheduler": {
          "description": "Scheduler defines some schedule rules to control the running time of the chaos experiment about pods.",
          "type": "object",
          "required": [
            "cron"
          ],
          "properties": {
            "cron": {
              "description": "Cron defines a cron job rule. \n Some rule examples: \"0 30 * * * *\" means to \"Every hour on the half hour\" \"@hourly\"      means to \"Every hour\" \"@every 1h30m\" means to \"Every hour thirty\" \n More rule info: https://godoc.org/github.com/robfig/cron",
              "type": "string"
            }
          }
        },
        "selector": {
          "description": "Selector is used to select pods that are used to inject chaos action.",
          "type": "object",
          "properties": {
            "annotationSelectors": {
              "description": "Map of string keys and values that can be used to select objects. A selector based on annotations.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "fieldSelectors": {
              "description": "Map of string keys and values that can be used to select objects. A selector based on fields.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "labelSelectors": {
              "description": "Map of string keys and values that can be used to select objects. A selector based on labels.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "namespaces": {
              "description": "Namespaces is a set of namespace to which objects belong.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "nodeSelectors": {
              "description": "Map of string keys and values that can be used to select nodes. Selector which must match a node's labels, and objects must belong to these selected nodes.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "nodes": {
              "description": "Nodes is a set of node name and objects must belong to these nodes.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "podPhaseSelectors": {
              "description": "PodPhaseSelectors is a set of condition of a pod at the current time. supported value: Pending / Running / Succeeded / Failed / Unknown",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "pods": {
              "description": "Pods is a map of string keys and a set values that used to select pods. The key defines the namespace which pods belong, and the each values is a set of pod names.",
              "type": "object",
              "additionalProperties": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "value": {
          "description": "Value is required when the mode is set to `FixedPodMode` / `FixedPercentPodMod` / `RandomMaxPercentPodMod`. If `FixedPodMode`, provide an integer of pods to do chaos action. If `FixedPercentPodMod`, provide a number from 0-100 to specify the percent of pods the server can do chaos action. IF `RandomMaxPercentPodMod`,  provide a number from 0-100 to specify the max percent of pods to do chaos action",
          "type": "string"
        }
      }
    },
    "status": {
      "description": "Most recently observed status of the chaos experiment about pods",
      "type": "object",
      "required": [
        "experiment",
        "phase"
      ],
      "properties": {
        "experiment": {
          "description": "Experiment records the last experiment state.",
          "type": "object",
          "properties": {
            "duration": {
              "type": "string"
            },
            "endTime": {
              "type": "string",
              "format": "date-time"
            },
            "phase": {
              "description": "ExperimentPhase is the current status of chaos experiment.",
              "type": "string"
            },
            "podRecords": {
              "type": "array",
              "items": {
                "description": "PodStatus represents information about the status of a pod in chaos experiment.",
                "type": "object",
                "required": [
                  "action",
                  "hostIP",
                  "name",
                  "namespace",
                  "podIP"
                ],
                "properties": {
                  "action": {
                    "type": "string"
                  },
                  "hostIP": {
                    "type": "string"
                  },
                  "message": {
                    "description": "A brief CamelCase message indicating details about the chaos action. e.g. \"delete this pod\" or \"pause this pod duration 5m\"",
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "namespace": {
                    "type": "string"
                  },
                  "podIP": {
                    "type": "string"
                  }
                }
              }
            },
            "reason": {
              "type": "string"
            },
            "startTime": {
              "type": "string",
              "format": "date-time"
            }
          }
        },
        "failedMessage": {
          "type": "string"
        },
        "phase": {
          "description": "Phase is the chaos status.",
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "scheduler": {
          "description": "ScheduleStatus is the current status of chaos scheduler.",
          "type": "object",
          "properties": {
            "nextRecover": {
              "description": "Next time when this action will be recovered",
              "type": "string",
              "format": "date-time"
            },
            "nextStart": {
              "description": "Next time when this action will be applied again",
              "type": "string",
              "format": "date-time"
            }
          }
        }
      }
    }
  },
  "x-kubernetes-group-version-kind": [
    {
      "group": "chaos-mesh.org",
      "kind": "PodChaos",
      "version": "v1alpha1"
    }
  ]
}


```

### CODE REVIEW

**Comment by manusa** [comment]
Hi,

I confirm the new generated CRD produced a _complete_ OpenApi spec :tada:  thx.

Later today I'll try to generate a client with this new output.

```shell script
$ kubectl apply -f https://raw.githubusercontent.com/chaos-mesh/chaos-mesh/fd0566f2e6ad44150a637388dde3637ec0e0dd93/manifests/crd.yaml
```

And OpenApi extraction:
```shell
$ kubectl get --raw /openapi/v2 | jq '.definitions."org.chaos-mesh.v1alpha1.PodChaos"'
{
  "description": "PodChaos is the control script`s spec.",
  "type": "object",
  "required": [
    "spec"
  ],
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
      "type": "string"
    },
    "kind": {
      "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
      "type": "string"
    },
    "metadata": {
      "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
      "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
    },
    "spec": {
      "description": "Spec defines the behavior of a pod chaos experiment",
      "type": "object",
      "required": [
        "action",
        "mode",
        "selector"
      ],
      "properties": {
        "action": {
          "description": "Action defines the specific pod chaos action. Supported action: pod-kill / pod-failure / container-kill Default action: pod-kill",
          "type": "string",
          "enum": [
            "pod-kill",
            "pod-failure",
            "container-kill"
          ]
        },
        "containerName": {
          "description": "ContainerName indicates the name of the container. Needed in container-kill.",
          "type": "string"
        },
        "duration": {
          "description": "Duration represents the duration of the chaos action. It is required when the action is `PodFailureAction`. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as \"300ms\", \"-1.5h\" or \"2h45m\". Valid time units are \"ns\", \"us\" (or \"µs\"), \"ms\", \"s\", \"m\", \"h\".",
          "type": "string"
        },
        "gracePeriod": {
          "description": "GracePeriod is used in pod-kill action. It represents the duration in seconds before the pod should be deleted. Value must be non-negative integer. The default value is zero that indicates delete immediately.",
          "type": "integer",
          "format": "int64",
          "minimum": 0
        },
        "mode": {
          "description": "Mode defines the mode to run chaos action. Supported mode: one / all / fixed / fixed-percent / random-max-percent",
          "type": "string",
          "enum": [
            "one",
            "all",
            "fixed",
            "fixed-percent",
            "random-max-percent"
          ]
        },
        "scheduler": {
          "description": "Scheduler defines some schedule rules to control the running time of the chaos experiment about pods.",
          "type": "object",
          "required": [
            "cron"
          ],
          "properties": {
            "cron": {
              "description": "Cron defines a cron job rule. \n Some rule examples: \"0 30 * * * *\" means to \"Every hour on the half hour\" \"@hourly\"      means to \"Every hour\" \"@every 1h30m\" means to \"Every hour thirty\" \n More rule info: https://godoc.org/github.com/robfig/cron",
              "type": "string"
            }
          }
        },
        "selector": {
          "description": "Selector is used to select pods that are used to inject chaos action.",
          "type": "object",
          "properties": {
            "annotationSelectors": {
              "description": "Map of string keys and values that can be used to select objects. A selector based on annotations.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "fieldSelectors": {
              "description": "Map of string keys and values that can be used to select objects. A selector based on fields.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "labelSelectors": {
              "description": "Map of string keys and values that can be used to select objects. A selector based on labels.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "namespaces": {
              "description": "Namespaces is a set of namespace to which objects belong.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "nodeSelectors": {
              "description": "Map of string keys and values that can be used to select nodes. Selector which must match a node's labels, and objects must belong to these selected nodes.",
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            },
            "nodes": {
              "description": "Nodes is a set of node name and objects must belong to these nodes.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "podPhaseSelectors": {
              "description": "PodPhaseSelectors is a set of condition of a pod at the current time. supported value: Pending / Running / Succeeded / Failed / Unknown",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "pods": {
              "description": "Pods is a map of string keys and a set values that used to select pods. The key defines the namespace which pods belong, and the each values is a set of pod names.",
              "type": "object",
              "additionalProperties": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "value": {
          "description": "Value is required when the mode is set to `FixedPodMode` / `FixedPercentPodMod` / `RandomMaxPercentPodMod`. If `FixedPodMode`, provide an integer of pods to do chaos action. If `FixedPercentPodMod`, provide a number from 0-100 to specify the percent of pods the server can do chaos action. IF `RandomMaxPercentPodMod`,  provide a number from 0-100 to specify the max percent of pods to do chaos action",
          "type": "string"
        }
      }
    },
    "status": {
      "description": "Most recently observed status of the chaos experiment about pods",
      "type": "object",
      "required": [
        "experiment",
        "phase"
      ],
      "properties": {
        "experiment": {
          "description": "Experiment records the last experiment state.",
          "type": "object",
          "properties": {
            "duration": {
              "type": "string"
            },
            "endTime": {
              "type": "string",
              "format": "date-time"
            },
            "phase": {
              "description": "ExperimentPhase is the current status of chaos experiment.",
              "type": "string"
            },
            "podRecords": {
              "type": "array",
              "items": {
                "description": "PodStatus represents information about the status of a pod in chaos experiment.",
                "type": "object",
                "required": [
                  "action",
                  "hostIP",
                  "name",
                  "namespace",
                  "podIP"
                ],
                "properties": {
                  "action": {
                    "type": "string"
                  },
                  "hostIP": {
                    "type": "string"
                  },
                  "message": {
                    "description": "A brief CamelCase message indicating details about the chaos action. e.g. \"delete this pod\" or \"pause this pod duration 5m\"",
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "namespace": {
                    "type": "string"
                  },
                  "podIP": {
                    "type": "string"
                  }
                }
              }
            },
            "reason": {
              "type": "string"
            },
            "startTime": {
              "type": "string",
              "format": "date-time"
            }
          }
        },
        "failedMessage": {
          "type": "string"
        },
        "phase": {
          "description": "Phase is the chaos status.",
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "scheduler": {
          "description": "ScheduleStatus is the current status of chaos scheduler.",
          "type": "object",
          "properties": {
            "nextRecover": {
              "description": "Next time when this action will be recovered",
              "type": "string",
              "format": "date-time"
            },
            "nextStart": {
              "description": "Next time when this action will be applied again",
              "type": "string",
              "format": "date-time"
            }
          }
        }
      }
    }
  },
  "x-kubernetes-group-version-kind": [
    {
      "group": "chaos-mesh.org",
      "kind": "PodChaos",
      "version": "v1alpha1"
    }
  ]
}

```

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
@YangKeao This feature need kubernetes >= 1.16, e2e test is using kubernetes 1.12.

**Comment by YangKeao** [comment]
@STRRL It needs kubernetes >= 1.15. Maybe I should update the docs to install `chaos-mesh` with `--validate=false` on lower version of kubernetes.

**Comment by cwen0** [comment]
> @STRRL It needs kubernetes >= 1.15. Maybe I should update the docs to install `chaos-mesh` with `--validate=false` on lower version of kubernetes.

When Kubernetes < 1.15, this update will cause installation failure using `install.sh`. Maybe we need to fix it first.

**Review by cwen0 — APPROVED** [review]

**Review by WangXiangUSTC — APPROVED** [review]

**Pull request merged**
