### PR TITLE
feat: support new 2.0 features on the UI

### LINKED ISSUE #1992: Chaos Dashboard: can not show stress chaos as expected
## Bug Report

**What version of Kubernetes are you using?**

```
k version                          
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

fork & branch: https://github.com/g1eny0ung/chaos-mesh/tree/nirvana-ui  
commit: ead62cd49a458b5eb698ce49ce193fcf7611cc2a

**What did you do?**

- startup chaos mesh on minikube 
- `k apply -f ./examples/burn-cpu.yaml`

**What did you expect to see?**

Could view stress chaos on dashboard.

**What did you see instead?**

I could see that experiment when listing experiment, but I can not access the detail.

image

image

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What is changed and how it works?

Resolve #1992.

What's Changed:

#### Display

- Renew homepage
   - Replace `TotalExperiments` with new count panels (Number of experiments, schedules, and workflows)
   - Adapt status pie chart with the new status API
   - Adapt events chart with the new events API
   - Use Material-UI `Timeline` to display recent events
- New pages: `Schedules` and `Schedule`
- Refactor New Experiment
   - Adapt to create a new schedule
   - Add a new `By YAML` panel to allow create an experiment or schedule by YAML
- Refactor `Events` page
- Refactor `Archives` page
   - Now workflows and schedules can be archived
   - Rewrite the single archive page
- Discard mobile viewport support

#### Code

- Material-UI
   - Upgrade Material-UI to version 5
   - Bump a independent `ThemeProvider` to compatible with legacy implementations
   - Rewrite `Space` by using Material-UI [Stack](https://next.material-ui.com/components/stack)
   - Replace almost every `useStyles` with [Material-UI System](https://next.material-ui.com/system/basics/)
- Components (main changes)
   - `ExperimentConfiguration` to `ObjectConfiguration`
   - `ExperimentListItem` to `ObjectListItem`
   - Merge some functions (like download YAML) into `YAMLEditor`
   - Remove unused
- API: adapt backend API changes
- Update i18n
- Remove all unused react imports: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
- Bugs fixes

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by AsterNighT** [comment]
It looks wierd on my computer, why is that?
image

**Comment by g1eny0ung** [comment]
> It looks wierd on my computer, why is that?
> image

Oops. If you mean the `TotalStatus` panel on the right side, I forgot to update the related i18n 😢. I will fix it soon.

**Comment by AsterNighT** [comment]
> > It looks wierd on my computer, why is that?
> > image
> 
> Oops. If you mean the `TotalStatus` panel on the right side, I forgot to update the related i18n 😢. I will fix it soon

Also the icons are a bit too big. And there are two useless scroll bars.

**Comment by g1eny0ung** [comment]
@AsterNighT Which section of icons do you mean? And the scrollbars are related to the system. There have no perfect methods to style the scrollbars because of different browser implements except using JS to unify.

**Comment by AsterNighT** [comment]
Here
image

**Comment by g1eny0ung** [comment]
> Here
> image

It's a deliberate design 🤣. If you think this is weird to you, I suggest that it can be raised during the weekly meeting and we will discuss it together.

**Review by STRRL — APPROVED** [review]
It could be compiled and run on my machine.

I will keep testing the detail in the next few days.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
