### PR TITLE
chore(helm): allow install to namespace with numbers only

### LINKED ISSUE #1493: Can't be installed to namespace with numbers only
## Bug Report

**What version of Kubernetes are you using?**
v1.19.3

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"master-g61ed59d386da23", GitCommit:"61ed59d386da23ac4a4a4e0a95f4d9b7f100af3f", BuildDate:"2021-02-03T06:38:41Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
Chaos Mesh can't be installed into namespace with numbers only 
```
helm install chaos-mesh chaos-mesh/chaos-mesh --namespace 123456
``` 

**What did you expect to see?**
Chaos Mesh will be installed

**What did you see instead?**
Error like : expecting " in namespace, see 1 instead of

**Output of chaosctl**
-

### PR DESCRIPTION
**Pull request by sedlakr**
### What problem does this PR solve?

fixes #1493

### What is changed and how does it work?
All used namespace vars are quoted to allow use number in namespace only

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by fewdan** [comment]
Looks like you need to deal with CI and DCO first?  Thank you.

**Comment by sedlakr** [comment]
Hi, CI and DCO fixed

**Review by cwen0 — DISMISSED** [review]
@sedlakr Thanks for your contribution! LGTM

**Comment by sedlakr** [comment]
@cwen0 one more fix on targetNamespace

**Review by fewdan — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
