### PR TITLE
TEST_USE_EXISTING_CLUSTER replace USE_EXISTING_CLUSTER

### PR DESCRIPTION
**Pull request by sanxun0325**
### What problem does this PR solve?

Issue Number: https://github.com/chaos-mesh/chaos-mesh/issues/1974

Problem Summary:
test: TEST_USE_EXISTING_CLUSTER replace USE_EXISTING_CLUSTER
### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

None

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @sanxun0325, thanks for your contribution! :heart: 

Please fix the DCO check, you could click the `Detail` in that row to find how to fix that. :D

**Review by fewdan — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM

**Pull request merged**
