### PR TITLE
e2e test on GitHub Action

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

This PR try to move e2e tests from self-hosted Jenkins to GitHub Action, the latter one provides a better network environment.

### What's changed and how it works?

- create a new GitHub Action workflow
- using a test reporter to generate test report

known issue:

- test reporter would insert the test report to an incorrect position. https://github.com/dorny/test-reporter/issues/67

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
I met some trouble with the displayed position of checks: https://github.com/STRRL/chaos-mesh/pull/4/checks?check_run_id=5492032669

It seems we could not choose which "check-suites" to append the "E2E test Reports" 

ref https://github.community/t/github-actions-status-checks-created-on-incorrect-check-suite-id/16685

**Comment by STRRL** [comment]
PTAL

And I think we'd better set `E2E Test / E2E Test Passed` as a required check.

/cc @YangKeao @cwen0 @Hexilee

**Comment by cwen0** [comment]
> PTAL
> 
> And I think we'd better set `E2E Test / E2E Test Passed` as a required check.
> 
> /cc @YangKeao @cwen0 @Hexilee

I will update the configuration after this pr merged

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> > PTAL
> > And I think we'd better set `E2E Test / E2E Test Passed` as a required check.
> > /cc @YangKeao @cwen0 @Hexilee
> 
> I will update the configuration after this pr merged

Oh, @STRRL  you can create a pr in this repo https://github.com/ti-community-infra/configs to update it directly.

**Pull request merged**
