### PR TITLE
refactor: chaos dns temp file in etc rather than root

### PR DESCRIPTION
**Pull request by muang0**
### What problem does this PR solve?
When inflicting dns chaos, the daemon creates a temp resolv.conf at the root directory.  If we create this temp file in /etc instead, we can provide better support for users implementing readOnly root filesystems.

### What's changed and how it works?
Write temp file to /etc instead of root directory

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cherry-pick to release branches**
  - [ ] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG
- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [x] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### CODE REVIEW

**Comment by muang0** [comment]
Hope you're having an enjoyable week sofar. Gentle nudge on this one, looking for a review from @g1eny0ung and/or @cwen0

**Comment by g1eny0ung** [comment]
> Hope you're having an enjoyable week sofar. Gentle nudge on this one, looking for a review from @g1eny0ung and/or @cwen0

Hi @muang0, thanks for the mentions, I forgot to keep up with the progress of this PR, which I will look at this evening. Sorry for a long time no response.

**Comment by g1eny0ung** [comment]
@muang0 I have no questions about this change, but there also has a potential problem related to this line of code. What about updating the `/etc/temp` to another name like `/etc/resolv_conf_dnschaos_temp`? This avoids having a file called `temp` by chance, considering that temp is a relatively common name.

**Comment by g1eny0ung** [comment]
> @muang0 I have no questions about this change, but there also has a potential problem related to this line of code. What about updating the `/etc/temp` to another name like `/etc/resolv_conf_dnschaos_temp`? This avoids having a file called `temp` by chance, considering that temp is a relatively common name.

Hi @muang0, I now feel this is a necessary optimization. I will update it now and then merge this PR.

**Pull request merged**
