### PR TITLE
chore: some dashboard updates

### LINKED ISSUE #1459: Can't update StressChaos on Dashboard
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v1.1.0", GitCommit:"eeeba39ad758f2463e8ca83a704a06c8957ebc01", BuildDate:"2021-01-08T13:15:03Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
I've created StressChaos with a certain namespace/deployment target specification. After I monitored CPU/Mem usage in my Kubernetes Grafana dashboard and the Pods didn't fail, I thought I could turn up the stress a little more.

I opened the existing experiment, clicked "Update" and changed the values of workers&load (doubled them).

**What did you expect to see?**
I wanted the experiment to update and accept the new values.

**What did you see instead?**
this

**Output of chaosctl**
No special events.

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Resolve #1459.

### What is changed and how does it work?

This PR includes some regular updates and bugs fixes:

- Supports pod-kill `GracePeriod` in dashboard
- Hides DNSChaos automatically when `dnsServer.create` is false
- Fixes `StressChaos` unable to update
- Fixes `StressChaos` load problem when creating experiments in UI

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by WangXiangUSTC — DISMISSED** [review]
LGTM

**Comment by fewdan** [comment]
It looks like CI has failed and may need to be revised.

**Comment by g1eny0ung** [comment]
> It looks like CI has failed and may need to be revised.

@fewdan Fixed it!

**Review by fewdan — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
