### PR TITLE
[add] api/archives/report

### PR DESCRIPTION
**Pull request by fewdan**
### What problem does this PR solve?
add api/archives/report

```
{
	"Meta": {
		"ID": 1,
		"CreatedAt": "2020-07-08T17:11:17.955744+08:00",
		"UpdatedAt": "2020-07-08T17:11:17.955744+08:00",
		"DeletedAt": null,
		"Name": "network-delay-example",
		"Namespace": "pingcap",
		"Kind": "NetworkChaos",
		"Action": "delay",
		"UID": "ab5e0fed-61c3-4ba3-9f7d-003b369ec935",
		"StartTime": "2020-07-08T17:10:00+08:00",
		"FinishTime": "2020-07-08T17:11:17+08:00"
	},
	"Events": [{
		"ID": 1,
		"CreatedAt": "2020-07-08T17:10:00.582267+08:00",
		"UpdatedAt": "2020-07-08T17:10:09.992392+08:00",
		"DeletedAt": null,
		"Experiment": "network-delay-example",
		"Namespace": "pingcap",
		"Kind": "NetworkChaos",
		"Message": "",
		"StartTime": "2020-07-08T17:10:00+08:00",
		"FinishTime": "2020-07-08T17:10:10+08:00",
		"Duration": "",
		"Pods": [{
			"ID": 1,
			"CreatedAt": "2020-07-08T17:10:00.583341+08:00",
			"UpdatedAt": "2020-07-08T17:10:00.583341+08:00",
			"DeletedAt": null,
			"EventID": 1,
			"PodIP": "10.244.2.12",
			"PodName": "tidb-controller-manager-5f76c759c5-cxbkz",
			"Namespace": "pingcap",
			"Message": "network netem action duration 10s",
			"Action": "delay"
		}],
		"ExperimentID": "ab5e0fed-61c3-4ba3-9f7d-003b369ec935"
	}, {
		"ID": 2,
		"CreatedAt": "2020-07-08T17:10:14.989749+08:00",
		"UpdatedAt": "2020-07-08T17:10:25.013557+08:00",
		"DeletedAt": null,
		"Experiment": "network-delay-example",
		"Namespace": "pingcap",
		"Kind": "NetworkChaos",
		"Message": "",
		"StartTime": "2020-07-08T17:10:15+08:00",
		"FinishTime": "2020-07-08T17:10:25+08:00",
		"Duration": "",
		"Pods": [{
			"ID": 2,
			"CreatedAt": "2020-07-08T17:10:14.990994+08:00",
			"UpdatedAt": "2020-07-08T17:10:14.990994+08:00",
			"DeletedAt": null,
			"EventID": 2,
			"PodIP": "10.244.2.12",
			"PodName": "tidb-controller-manager-5f76c759c5-cxbkz",
			"Namespace": "pingcap",
			"Message": "network netem action duration 10s",
			"Action": "delay"
		}],
		"ExperimentID": "ab5e0fed-61c3-4ba3-9f7d-003b369ec935"
	}, {
		"ID": 3,
		"CreatedAt": "2020-07-08T17:10:30.009301+08:00",
		"UpdatedAt": "2020-07-08T17:10:39.993685+08:00",
		"DeletedAt": null,
		"Experiment": "network-delay-example",
		"Namespace": "pingcap",
		"Kind": "NetworkChaos",
		"Message": "",
		"StartTime": "2020-07-08T17:10:30+08:00",
		"FinishTime": "2020-07-08T17:10:40+08:00",
		"Duration": "",
		"Pods": [{
			"ID": 3,
			"CreatedAt": "2020-07-08T17:10:30.010558+08:00",
			"UpdatedAt": "2020-07-08T17:10:30.010558+08:00",
			"DeletedAt": null,
			"EventID": 3,
			"PodIP": "10.244.2.12",
			"PodName": "tidb-controller-manager-5f76c759c5-cxbkz",
			"Namespace": "pingcap",
			"Message": "network netem action duration 10s",
			"Action": "delay"
		}],
		"ExperimentID": "ab5e0fed-61c3-4ba3-9f7d-003b369ec935"
	}, {
		"ID": 4,
		"CreatedAt": "2020-07-08T17:10:44.999305+08:00",
		"UpdatedAt": "2020-07-08T17:10:55.0208+08:00",
		"DeletedAt": null,
		"Experiment": "network-delay-example",
		"Namespace": "pingcap",
		"Kind": "NetworkChaos",
		"Message": "",
		"StartTime": "2020-07-08T17:10:45+08:00",
		"FinishTime": "2020-07-08T17:10:55+08:00",
		"Duration": "",
		"Pods": [{
			"ID": 4,
			"CreatedAt": "2020-07-08T17:10:45.000667+08:00",
			"UpdatedAt": "2020-07-08T17:10:45.000667+08:00",
			"DeletedAt": null,
			"EventID": 4,
			"PodIP": "10.244.2.12",
			"PodName": "tidb-controller-manager-5f76c759c5-cxbkz",
			"Namespace": "pingcap",
			"Message": "network netem action duration 10s",
			"Action": "delay"
		}],
		"ExperimentID": "ab5e0fed-61c3-4ba3-9f7d-003b369ec935"
	}, {
		"ID": 5,
		"CreatedAt": "2020-07-08T17:11:00.016301+08:00",
		"UpdatedAt": "2020-07-08T17:11:09.997386+08:00",
		"DeletedAt": null,
		"Experiment": "network-delay-example",
		"Namespace": "pingcap",
		"Kind": "NetworkChaos",
		"Message": "",
		"StartTime": "2020-07-08T17:11:00+08:00",
		"FinishTime": "2020-07-08T17:11:10+08:00",
		"Duration": "",
		"Pods": [{
			"ID": 5,
			"CreatedAt": "2020-07-08T17:11:00.017526+08:00",
			"UpdatedAt": "2020-07-08T17:11:00.017526+08:00",
			"DeletedAt": null,
			"EventID": 5,
			"PodIP": "10.244.2.12",
			"PodName": "tidb-controller-manager-5f76c759c5-cxbkz",
			"Namespace": "pingcap",
			"Message": "network netem action duration 10s",
			"Action": "delay"
		}],
		"ExperimentID": "ab5e0fed-61c3-4ba3-9f7d-003b369ec935"
	}],
	"TotalTime": "1m17s",
	"TotalFaultTime": "50s"
}
```

### CODE REVIEW

**Comment by yeya24** [comment]
Could you please briefly explain where this API is used?

**Comment by fewdan** [comment]
> Could you please briefly explain where this API is used?

The previous requirement stated that an interface was needed to return the report of the experiment. May be placed on the archive page.

**Comment by cwen0** [comment]
> > Could you please briefly explain where this API is used?
> 
> The previous requirement stated that an interface was needed to return the report of the experiment. May be placed on the archive page.

We will support the status check API, so we need to generate a report including the status of the application and the fault injection. This report just is the basest version.

**Pull request merged**
