### PR TITLE
Handle deleting jvmchaos crds when the container holding the jvm rules has been deleted (#2981)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2981 to release-2.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In chaos-mesh repo:
git pr https://github.com/chaos-mesh/chaos-mesh/pull/3059
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/chaos-mesh.git pr/3059:release-2.1-00768bf9c951
```

---

Signed-off-by: Peter Reilly <peter.reilly@netscout.com>

### What problem does this PR solve?

When a jvm rule causes the container containing the jvm is deleted, or the jvm to exit, one cannot delete the jvm rule

Using the hello example `hello.yaml`:

```yaml hello.yaml
apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  namespace: hello
spec:
  containers:
    - name: helloworld
      # source code: https://github.com/WangXiangUSTC/byteman-example/tree/main/example.helloworld
      # this application will print log like this below:
      # 0. Hello World
      # 1. Hello World
      # ...
      image: xiang13225080/helloworld:v1.0
      imagePullPolicy: IfNotPresent
```

with the return rule `return.yaml`

```yaml return.yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: return
  namespace: hello
spec:
  action: return
  class: Main
  method: getnum
  value: '9999'
  mode: all
  selector:
    namespaces:
      - hello
```

```bash
kubectl apply -f return.yaml
kubectl delete pod -n hello helloworld
# the following never returns
kubectl delete -f return.yaml
```

With the rule `jvm-kill.yaml`

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-kill
  namespace: hello
spec:
  action: ruleData
  mode: all
  ruleData: "\nRULE modify return value\nCLASS Main\nMETHOD getnum\nAT ENTRY\nIF true\nDO killJVM(), return 9999\nENDRULE\n"
  selector:
    namespaces:
      - hello
```

```yaml
kubectl apply -f jvm-kill.yaml
# the following waits forever
kubectl delete -f jvm-kill.yaml
```

### What's changed and how it works?

In controllers/chaosimpl/jvmchaos/impl.go::Recover

if the code cannot find the container for the record, it will return
```go
v1alpha1.NotInjected, nil
```

if the code cannot  delete the jvm rule, it will also return

```go
v1alpha1.NotInjected, nil
```

to say to the caller that there is no need to remove the jvm rule.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

```bash
kubectl apply -f return.yaml
kubectl delete pod -n hello helloworld
# the following now works
kubectl delete -f return.yaml
```

```bash
kubectl apply -f jvm-kill.yaml
# the following now works
kubectl delete -f jvm-kill.yaml
```

Side effects

- [ ] Breaking backward compatibility

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@peterkittreilly cherry-pick automatically failed, could you please cherry-pick it manually?

**Review by fewdan — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
