### PR TITLE
Helm: Update manifests for cert-manager/v1 API

### PR DESCRIPTION
**Pull request by elsesiy**
### What problem does this PR solve?

Updates the current usage of cert-manager resources to the stable `v1` API.

### Checklist

Tests

- [ ] Unit test
- [x] E2E test (tested on kind with latest cert-manager release)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Breaking backward compatibility

### Release note 

```release-note
Helm: Update cert-manager resources to v1
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @elsesiy, thanks for your contribution!

I think that removing the support for `cert-manager.io/v1alpha2` directly might be not so good, how about using `.Capabilities.APIVersions.Has` for prefer using `cert-manager.io/v1alpha2`, but keep compatibility with `cert-manager.io/v1alpha2`.

I think we could finally remove the support about `cert-manager.io/v1alpha2` in v2.2 or later.

**Comment by STRRL** [comment]
> Hi @elsesiy, thanks for your contribution!
> 
> I think that removing the support for `cert-manager.io/v1alpha2` directly might be not so good, how about using `.Capabilities.APIVersions.Has` for prefer using `cert-manager.io/v1alpha2`, but keep compatibility with `cert-manager.io/v1alpha2`.
> 
> I think we could finally remove the support about `cert-manager.io/v1alpha2` in v2.2 or later.

Hi @elsesiy, could you help us with that capability thing? ❤️

**Comment by elsesiy** [comment]
@STRRL The existing certs api version will continue to work until cert-manager 1.6.0 is adopted by users, see [here](https://cert-manager.io/docs/installation/upgrading/remove-deprecated-apis/). I understand your concerns, however the original API was introduced [about 2 years ago](https://github.com/jetstack/cert-manager/releases/tag/v0.11.0) so do you really want to continue to support it?

**Comment by STRRL** [comment]
> @STRRL The existing certs api version will continue to work until cert-manager 1.6.0 is adopted by users, see [here](https://cert-manager.io/docs/installation/upgrading/remove-deprecated-apis/). I understand your concerns, however the original API was introduced [about 2 years ago](https://github.com/jetstack/cert-manager/releases/tag/v0.11.0) so do you really want to continue to support it?

Removing support for the old version of cert-manager without any warning is not so good for users. I prefer to support both v1 and v1alpha2 at least in Chaos Mesh 2.1(will release in next month), and remove the support for v1alpha2 at 2.2 :)  How do you think about it? @elsesiy .

**Review by STRRL — APPROVED** [review]
LGTM, we are going to make the capability things in the next PRs.

**Review by Hexilee — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
Hi @elsesiy, could you update the codebase for syncing with the base `master` branch? Thanks a lot!

**Comment by elsesiy** [comment]
@STRRL Done!

**Comment by STRRL** [comment]
:joy: sorry for my misoperation with closing this PR. We're going to merge it!

**Comment by STRRL** [comment]
Oops, we messed up the order of merging PRs, #2552 should be merged after the PR.  

Could you resolve the conflict? :heart: @elsesiy

**Comment by elsesiy** [comment]
@STRRL Done again :)

**Pull request merged**
