### PR TITLE
Add: CRD into Helm Chart

### PR DESCRIPTION
**Pull request by nlamirault**
### What is changed and how does it work?

Add CRD files into the Helm Chart.
According to Helm documentation : https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
@nlamirault Thanks for your contribution!

**Comment by YangKeao** [comment]
I agree with you that the CRD should be inside the `helm` chart. 🍻

**Review by YangKeao — COMMENTED** [review]
These files should be generated automatically through `make yaml`.

**Comment by cwen0** [comment]
> These files should be generated automatically through `make yaml`.

@nlamirault Can you help us to implement this?

**Comment by zhouqiang-cl** [comment]
hey, @nlamirault are you still here😝

**Comment by WangXiangUSTC** [comment]
ping @nlamirault, could you please update this pr, or I will create another pr to do the same thing

**Comment by nlamirault** [comment]
@cwen0 how generates theses files using Makefile ?
I see `yaml` goal. But CRD aren't not split.

**Comment by WangXiangUSTC** [comment]
> @cwen0 how generates theses files using Makefile ?
> I see `yaml` goal. But CRD aren't not split.

I think update the `manifests` is ok, just like:

```
manifests: $(GOBIN)/controller-gen
	$< $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
	$< $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=helm/chaos-mesh/crds
```

**Review by WangXiangUSTC — DISMISSED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
the ci failed, please execute `make manifests` and update the changes to git and then commit

**Review by WangXiangUSTC — APPROVED** [review]

**Comment by WangXiangUSTC** [comment]
@cwen0 @YangKeao PTAL

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
