### PR TITLE
Slightly adjusted contents of Chaos Mesh Dashboard

### PR DESCRIPTION
**Pull request by ClSlaid**
Signed-off-by: ClSlaid \<cailue@bupt.edu.cn\>
Following your docs, I installed Chaos Mesh by Helm3 on my desktop running Manjaro.
When I wanted to enable Chaos Mesh Dashboard, code provided in docs didn't work properly:
```zsh
% helm upgrade chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set dashboard.create=true     
Error: failed to download "helm/chaos-mesh" (hint: running `helm repo update` may help)
```
So I slightly adjusted **helm/chaos-mesh** to **chaos-mesh/chaos-mesh**. And that worked well on my Manjaro device.

### What problem does this PR solve?

None
### What is changed and how does it work?
Slightly changed documents
### Checklist

None
Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [y] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
Slightly adjusted bash script of enabling Chaos-Mesh Dashboard.
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@ClSlaid Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/825/checks?check_run_id=1005890930) first? Thanks!

**Comment by ClSlaid** [comment]
Then you may wait until I get familiar with git and GitHub...
In fact I consider it better raising an issue instead of create a pr...

**Comment by fewdan** [comment]
@ClSlaid 
You can refer to [this](https://github.com/chaos-mesh/chaos-mesh/pull/825/checks?check_run_id=1005890930) to sign off DCO.

**Comment by ClSlaid** [comment]
> @ClSlaid
> You can refer to [this](https://github.com/chaos-mesh/chaos-mesh/pull/825/checks?check_run_id=1005890930) to sign off DCO.

Situation is getting awkward... I've tried with scripts given by the link however they didn't really work...

**Comment by fewdan** [comment]
> > @ClSlaid
> > You can refer to [this](https://github.com/chaos-mesh/chaos-mesh/pull/825/checks?check_run_id=1005890930) to sign off DCO.
> 
> Situation is getting awkward... I've tried with scripts given by the link however they didn't really work...

What happened?  Looks like you haven't pushed to github yet?

**Comment by ClSlaid** [comment]
> > > @ClSlaid
> > > You can refer to [this](https://github.com/chaos-mesh/chaos-mesh/pull/825/checks?check_run_id=1005890930) to sign off DCO.
> > 
> > 
> > Situation is getting awkward... I've tried with scripts given by the link however they didn't really work...
> 
> What happened? Looks like you haven't pushed to github yet?

Well at very beginning I merely pull requested without forking the repository.
Then I tried clone the repo from here to my local machine, changed target file and push. And at the very first I do tried these scripts, and you know these is no such `patch-1` things here.  Surely that's not even wrong.
Now I forked the repo, then used `git pull` to copy the forked repo to local machine. After edit I used `git add` and `git commit -a -s` to commit changes. And `git push origin origin/patch-1`, `git push origin master`. They worked well I think, however that didn't pass DCO check.
Now I must have pushed everything to my forked repo, maybe I operated with wrong repo.

**Comment by fewdan** [comment]
You can simply close this pr and resubmit a pr.
Just need *git add* , then *git commit -s -m "xxx"* , and finally *git push origin xxx*.

**Comment by ClSlaid** [comment]
> You can simply close this pr and resubmit a pr.
> Just need _git add_ , then _git commit -s -m "xxx"_ , and finally _git push origin xxx_.

Thanks for your help, I will try...

**Pull request closed without merging**
