### PR TITLE
chore: disable update temporally

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What problem does this PR solve?

> Problem Summary:

Address #2227.

### What's changed and how it works?

> What's Changed:

Delete and comment related code.

### Related changes

- [x] Need to update `chaos-mesh/website`https://github.com/chaos-mesh/website/pull/157
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by STRRL — COMMENTED** [review]
please remove codes instead  comment them

**Comment by g1eny0ung** [comment]
> please remove codes instead comment them

Got it. Already done.

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
Do we need cheery-pick to release-2.0? @g1eny0ung

**Comment by g1eny0ung** [comment]
> Do we need to cheery-pick to release-2.0? @g1eny0ung

Yes, we should. But it must be done manually because the APIs have breaking changes. I'll submit a PR later.

**Pull request merged**
