### PR TITLE
Helm: install chaos-dashboard by default

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What problem does this PR solve?
 

Update Helm Chart to install chaos-dashboard by default 

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
The Chaos Mesh docs should be updated, I will do it!

**Pull request closed without merging**
