### PR TITLE
fix-typo (aws-finalizer)

### PR DESCRIPTION
**Pull request by fewdan**
Signed-off-by: “fewdan” <fewdan@hotmail.com>

### What problem does this PR solve?
fix-typo

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
What will happen if we don't fix it？Or it is only a typo?

**Comment by fewdan** [comment]
> What will happen if we don't fix it？Or it is only a typo?

@WangXiangUSTC It is just a typo, and there will be no consequences if it is not modified. Modify it to be consistent with the case of other places.

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
