### PR TITLE
Fix typo in controller error message

### PR DESCRIPTION
**Pull request by Shoothzj**
### What's changed and how it works?
Fix typo in controller error message

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [] I have labeled this PR with "no-need-update-changelog"

### CODE REVIEW

**Comment by STRRL** [comment]
Thanks for your contribution! @Shoothzj

**Review by STRRL — APPROVED** [review]
LGTM! 🎉

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
