### PR TITLE
refactor: move from io/ioutil to io and os packages

### PR DESCRIPTION
**Pull request by Juneezee**
### What's changed and how it works?

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [x] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by fewdan** [comment]
Thanks for your contribution!

**Review by fewdan — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Blocked by https://github.com/chaos-mesh/chaos-mesh/pull/3083

**Pull request merged**
