### PR TITLE
renamed all occurances of chaos testing to chaos-mesh

### LINKED ISSUE #2818: Use `chaos-mesh` instead of `chaos-testing` in anywhere
## Feature Request

**Is your feature request related to a problem? Please describe:**
No. 

**Describe the feature you'd like:**
We use `chaos-testing` in most scripts and codes as the namespace which assumed/expected that Chaos Mesh installed. It's a  historical problem and using `chaos-testing` does not properly describe what would Chaos Mesh be expected.

So we propose that use `chaos-mesh` to replace `chaos-testing` as the namespace.

**Describe alternatives you've considered:**

It would need lots of changes, it would not be cherry-picked into release-2.1 and release-2.0.

**Teachability, Documentation, Adoption, Migration Strategy:**

No other reference.

### PR DESCRIPTION
**Pull request by krystian-kulgawczuk**
### What problem does this PR solve?

Close #2818

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [x] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [x] Breaking backward compatibility

### CODE REVIEW

**Comment by STRRL** [comment]
Welcome @krystian-kulgawczuk !

**Comment by krystian-kulgawczuk** [comment]
Switching to new IDE and replace plugin didn't include hidden dirs... Fixed!

**Comment by krystian-kulgawczuk** [comment]
@STRRL Could you please take a look and help me figure out why the tests are failing? I noticed that on previous ci go test it passed and now it failed, but I don't see how I could've broken it. Can i trust these tests? :)

**Comment by g1eny0ung** [comment]
@krystian-kulgawczuk I tested this locally, and it's probably because `.editorconfig` formatted the snap file automatically.

Run `yarn workspace @ui/mui-extends test -u` under the `ui` to update snapshots again can solve this problem.

**Comment by STRRL** [comment]
I have updated the snap file and changelog. :)

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
/cc @YangKeao @iguoyr 

PTAL

**Comment by krystian-kulgawczuk** [comment]
Thanks @STRRL. Still one e2e test failing. Tried getting pod in post run, but it was already deleted.

**Comment by STRRL** [comment]
> Thanks @STRRL. Still one e2e test failing. Tried getting pod in post run, but it was already deleted.

e2e test are flaky 🥲, I would retry them

**Comment by xlgao-zju** [comment]
maybe we should figure out how to upgrade the chaos mesh and migrate the existing resource, before we merge this PR 🤔

**Review by xlgao-zju — APPROVED** [review]
LGTM

**Pull request merged**
