### PR TITLE
fix: goroutine leak

### PR DESCRIPTION
**Pull request by 0xff-dev**
## What problem does this PR solve?
Based on my local tests, it has been discovered that in this particular scenario, the goroutine may fail to exit when an unbuffered channel is used.

```go
package main

import (
	"fmt"
	"runtime"
	"time"
)

func try() {
	ch := make(chan error)
	go func() {
		time.Sleep(5 * time.Second)
		fmt.Println("write error")
		ch <- fmt.Errorf("leak")
	}()
	select {
	case <-time.After(3 * time.Second):
		break
	case <-ch:
		fmt.Println("get chan error")
	}
   fmt.Println("wait a moment")
	time.Sleep(3 * time.Second)
}
func main() {
	before := runtime.NumGoroutine()
	try()
	after := runtime.NumGoroutine()
	fmt.Println(after == before)
}
```

## What's changed and how it works?
Using buffered channel.

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [x] release-2.6
- [x] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
LGTM. But only for cap 1 buffered channel is one of the error-prone practices.

/lgtm

**Review by cwen0 — APPROVED** [review]
/lgtm Good catch!

**Review by cwen0 — APPROVED** [review]

**Comment by g1eny0ung** [comment]
@cwen0 Please refer to https://prow.chaos-mesh.dev/command-help?repo=chaos-mesh%2Fchaos-mesh to get the new commands about merging PRs and cherry-picks.

**Pull request merged**
