### PR TITLE
ci: upgrade actions

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Upgrade `actions/checkout` and `actions/cache` to v2.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by fewdan — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]

**Comment by cwen0** [comment]
@g1eny0ung PTAL

**Comment by g1eny0ung** [comment]
@cwen0 All checks passed now.

**Pull request merged**
