### PR TITLE
[update] update api/experiments (new and update)

### PR DESCRIPTION
**Pull request by fewdan**
### What problem does this PR solve?
Check the fields when creating or updating an experiment

### What is changed and how does it work?
Check the nil pointers

### Check List
No

Tests

- No code

Code changes

- Has Go code change

Side effects

- NO

Related changes

- NO

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
I think we should use a **validate** library to perform API input checking. We have already include https://pkg.go.dev/mod/github.com/go-playground/validator/v10 as a dep.

**Comment by fewdan** [comment]
@g1eny0ung 
I checked the code, it looks like this:
```
if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		v.RegisterValidation("NameValid", apivalidator.NameValid)
		v.RegisterValidation("NamespaceSelectorsValid", apivalidator.NamespaceSelectorsValid)
		v.RegisterValidation("MapSelectorsValid", apivalidator.MapSelectorsValid)
		v.RegisterValidation("PhaseSelectorsValid", apivalidator.PhaseSelectorsValid)
		v.RegisterValidation("CronValid", apivalidator.CronValid)
		v.RegisterValidation("DurationValid", apivalidator.DurationValid)
		v.RegisterValidation("ValueValid", apivalidator.ValueValid)
		v.RegisterValidation("PodsValid", apivalidator.PodsValid)
	}
```
It seems that we use "validator" to verify whether the field is legal, rather than checking whether the field is empty?

**Comment by g1eny0ung** [comment]
> @g1eny0ung
> I checked the code, it looks like this:
> 
> ```
> if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
> 		v.RegisterValidation("NameValid", apivalidator.NameValid)
> 		v.RegisterValidation("NamespaceSelectorsValid", apivalidator.NamespaceSelectorsValid)
> 		v.RegisterValidation("MapSelectorsValid", apivalidator.MapSelectorsValid)
> 		v.RegisterValidation("PhaseSelectorsValid", apivalidator.PhaseSelectorsValid)
> 		v.RegisterValidation("CronValid", apivalidator.CronValid)
> 		v.RegisterValidation("DurationValid", apivalidator.DurationValid)
> 		v.RegisterValidation("ValueValid", apivalidator.ValueValid)
> 		v.RegisterValidation("PodsValid", apivalidator.PodsValid)
> 	}
> ```
> 
> It seems that we use "validator" to verify whether the field is legal, rather than checking whether the field is empty?
> Do you mean that we register other validators to verify the relevant fields of the experiment?

Yep. we can custom some validators to meet our needs. Like this PR solved, for example:

> NetworkChaos `action` is required.
The `delay` field is required when `action` is `delay`.

So we can write **bindings** to describe this behavior:

```go
type NetworkChaosInfo struct {
	Action      string                  `json:"action" binding:"oneof='' 'netem' 'delay' 'loss' 'duplicate' 'corrupt' 'partition' 'bandwidth'"`
	Delay       *v1alpha1.DelaySpec     `json:"delay"  binding:"required_field_equal=Action:delay"`
}
```

At last, we need to define a func to implement `required_field_equal=Action:delay`:

```go
v.RegisterValidation(`required_field_equal`, func (fl validator.FieldLevel) bool {}
```

I found a useful example: https://github.com/go-playground/validator/issues/494, it use `reflect` to implement this func.

**Comment by fewdan** [comment]
@g1eny0ung 
Okay, let me take a look.

**Pull request closed without merging**
