### PR TITLE
word correct

### PR DESCRIPTION
**Pull request by Akiros001**
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by fewdan** [comment]
@Akiros001 hello, would you please fix the DCO first?  Thanks for your contribution.

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by AsterNighT** [comment]
Thank you for your contribution! It seems you should fix the DCO first.

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@Akiros001 Thanks for your contribution! Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/1879/checks?check_run_id=2673463738) first?

**Comment by STRRL** [comment]
I am going to close this PR because it has been not updated for a long time.

Feel free to update and reopen it! :smile:

**Pull request closed without merging**
