### PR TITLE
fix wrong zero value of httpchaos replace body action

### LINKED ISSUE #2988: zero value config of httpchaos replace action cause wrong behavior
## Bug Report

**What version of Chaos Mesh are you using?**
Latest

**What did you do?**

Apply following config.

```yaml
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: http-fault
  namespace: default
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx
  mode: all
  target: Request
  port: 80
  path: /*
  replace:
    code: 502
```

**What did you expect to see?**

HTTPChaos works.

**What did you see instead?**

```
400 Fail to apply, unknown variant ``, expected `TEXT` or `BASE64`.
```

**The possible cause**
In https://github.com/chaos-mesh/chaos-mesh/pull/2555, we introduce the chaos-tproxy v0.4.x, which needs a compatibility layer to HTTPChaos config. However, the zero value of field [`Body`](https://github.com/chaos-mesh/chaos-mesh/blob/5005201fdab583f46bef71c2e9e536f6766cc7b6/pkg/chaosdaemon/tproxyconfig/config.go#L179) in ` PodHttpChaosReplaceActions` is wrong, we should replace it with a pointer.

### PR DESCRIPTION
**Pull request by Hexilee**
### What problem does this PR solve?

Close #2988

### What's changed and how it works?

Replace field [Body](https://github.com/chaos-mesh/chaos-mesh/blob/5005201fdab583f46bef71c2e9e536f6766cc7b6/pkg/chaosdaemon/tproxyconfig/config.go#L179) of PodHttpChaosReplaceActions with a pointer.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
Hi @Hexilee  please append CHANGELOG for this bugfix.

And do we need to cherry-pick this PR into release-2.1?

**Comment by Hexilee** [comment]
> Hi @Hexilee please append CHANGELOG for this bugfix.
> 
> And do we need to cherry-pick this PR into release-2.1?

I'm sorry to forget that, I will create another PR to update CHANGELOG. This bug is introduced after release-2.1, so it's unnecessary to cherry-pick.

**Pull request merged**
