### PR TITLE
Refactor static interface 'controllers-action-delegate'

### PR DESCRIPTION
**Pull request by ReigenDing**
### What problem does this PR solve?
static interface check 

Problem Summary:

### What is changed and how it works?
check static interface

What's Changed:

- [x] struct Delegate at controllers/action/delegate.go
- [x] struct Impl at controllers/chaosimpl/awschaos/detachvolume/impl.go
- [x] struct Impl at controllers/chaosimpl/awschaos/ec2restart/impl.go
- [x] struct Impl at controllers/chaosimpl/awschaos/ec2stop/impl.go
- [x] struct Impl at controllers/chaosimpl/dnschaos/types.go
- [x] struct Impl at controllers/chaosimpl/gcpchaos/diskloss/impl.go
- [x] struct Impl at controllers/chaosimpl/gcpchaos/nodereset/impl.go
- [x] struct Impl at controllers/chaosimpl/gcpchaos/nodestop/impl.go
- [x] struct Impl at controllers/chaosimpl/httpchaos/impl.go
- [x] struct Impl at controllers/chaosimpl/iochaos/impl.go
- [x] struct Impl at controllers/chaosimpl/jvmchaos/impl.go
- [x] struct Impl at controllers/chaosimpl/kernelchaos/types.go
- [x] struct Impl at controllers/chaosimpl/networkchaos/trafficcontrol/impl.go
- [x] struct Impl at controllers/chaosimpl/networkchaos/partition/impl.go
- [x] struct Impl at controllers/chaosimpl/podchaos/containerkill/impl.go
- [x] struct Impl at controllers/chaosimpl/podchaos/podfailure/impl.go
- [x] struct Impl at controllers/chaosimpl/podchaos/podkill/impl.go
- [x] struct Impl at controllers/chaosimpl/stresschaos/impl.go
- [x] struct Impl at controllers/chaosimpl/timechaos/impl.go

### Related changes

#2163
* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Comment by STRRL** [comment]
/cc @YangKeao 
/cc @Hexilee 

PTAL

**Review by YangKeao — APPROVED** [review]
LGTM

Cool! Thanks

**Pull request merged**
