### PR TITLE
Download build cache from file server

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Use the `fileserver` rather than docker image to store the cache.

### CODE REVIEW

**Comment by STRRL** [comment]
Does https://github.com/YangKeao/chaos-mesh-e2e-image need updates?

**Review by Hexilee — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]

**Comment by YangKeao** [comment]
> Does [YangKeao/chaos-mesh-e2e-image](https://github.com/YangKeao/chaos-mesh-e2e-image) need updates?

Yes. The cache in it should be removed (but it doesn't matter, and will not block the merge).

**Pull request merged**
