### PR TITLE
cherry-pick-to-release-1.0: modify stable repo (#1315)

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

Try to fix e2e test failed, which belongs to "type/1.0-cherry-pick", like #1346.
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @YangKeao @WangXiangUSTC @cwen0 PTAL.

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
