### PR TITLE
Specify DaemonSetUpdateStrategy for chaos-daemon

### PR DESCRIPTION
**Pull request by miedzinski**
Signed-off-by: Dominik Miedziński <dominik.miedzinski@allegro.pl>

### What problem does this PR solve?

This PR allows for configuring `DaemonSetUpdateStrategy` for chaos-daemon in Helm template.

### What's changed and how it works?

A new `chaosDaemon.updateStrategy` configuration option in values.yaml is used for chaos-daemon DaemonSet `updateStrategy` field. For more details refer to [Kubernetes documentation](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec).

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Add `chaosDaemon.updateStrategy` to Helm chart to allow configuring `DaemonSetUpdateStrategy` for chaos-daemon.
```

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
Thanks! LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@miedzinski Can you help to update CHANGELOG?

**Comment by miedzinski** [comment]
@cwen0 done!

**Pull request merged**
