### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by AsterNighT**
There's no building errors aside from dashboard and chaosctl now. Chaosctl may have to be redesigned.

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by AsterNighT** [comment]
Uhh, e2e-test should be disabled for nirvana, at least not now.

**Comment by AsterNighT** [comment]
I add `nirvana` to e2e blacklist now. If it is ready for e2e pls let me know.

**Pull request merged**
