### PR TITLE
chore: change project name for build-env and dev-env

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Close https://github.com/chaos-mesh/chaos-mesh/issues/2475

> Problem Summary:

### What's changed and how it works?

> What's Changed:

- rename image:
  - from `ghcr.io/chaos-mesh/chaos-mesh/build-env` to `ghcr.io/chaos-mesh/build-env`
  - from `ghcr.io/chaos-mesh/chaos-mesh/dev-env` to `ghcr.io/chaos-mesh/dev-env`
- update GitHub Action Workflow, use `github.repository_owner` as the project name( I think it would be easier for contributors building their own build-env and dev-env with manually dispatched github actions than hard-coding PROJECT as `chaos-mesh`. )

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL  @cwen0 @YangKeao @WangXiangUSTC @Hexilee @iguoyr

**Comment by iguoyr** [comment]
https://github.com/chaos-mesh/chaos-mesh/blob/acc060c7d3190d3971b6fb601d75db6b18f95e8c/.github/workflows/upload_env_image.yml this file also needs update.

**Comment by STRRL** [comment]
> [`acc060c`/.github/workflows/upload_env_image.yml](https://github.com/chaos-mesh/chaos-mesh/blob/acc060c7d3190d3971b6fb601d75db6b18f95e8c/.github/workflows/upload_env_image.yml) this file also needs update.

Updated in 9274a622, PTAL!

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
