### PR TITLE
Fix dashboard mysql bug

### LINKED ISSUE #2464: Dashboard MySQL 8 Bootstrapping Issue In Workflows
## Bug Report

**What version of Kubernetes are you using?**
1.19

**What version of Chaos Mesh are you using?**
2.0.2

**What did you do?**
Tried using mysql 8.0 version for backend database

**What did you expect to see?**
Successful database bootstrapping

**What did you see instead?**
```
(/app/chaos-mesh/pkg/store/workflow/workflow.go:30) 
[2021-11-03 17:06:15]  Error 1074: Column length too big for column 'workflow' (max = 16383); use BLOB or TEXT instead 
panic: Error 1146: Table 'chaos-mesh.workflow_entities' doesn't exist
```

### PR DESCRIPTION
**Pull request by craig-seeman**
### What problem does this PR solve?
Close #2464

> Problem Summary:

### What's changed and how it works?

Added gorm argument in dashboard core workflow for the WorkflowEntity struct. This will define the type as a TEXT, allowing the column length to be bigger than MySQL allows via defaults.

Related error shown when starting dashboard with brand new / blank database:
```
[2021-11-03 17:06:15]  Error 1074: Column length too big for column 'workflow' (max = 16383); use BLOB or TEXT instead 
panic: Error 1146: Table 'chaos-mesh.workflow_entities' doesn't exist
```

> What's Changed:

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard` (Leaving unchecked, I believe this is for NPM changes?)
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests
- [X] Manual test (add detailed scripts or steps below)

I have not had time to get local complete e2e testing environment working to run unit tests, however have tried basic test of starting the dashboard and running an experiment.

Manually tested with sqlite and mysql 8.0 ( Complete MySQL usage still blocked by bug outlined in #1659 )

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Fixed issue within workflows causing initial dashboard startup to fail when using mysql 8.x
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
> (Leaving unchecked, I believe this is for NPM changes?)

This is for checking if other changes affect the dashboard. If the dashboard itself is modified, you can safely ignore it.

> I have not had time to get local complete e2e testing environment working to run unit tests

Don't worry, this is not necessary.

Finally, the DCO needs to be fixed. You can sign with `git commit --amend -s` and force push again.

**Review by g1eny0ung — APPROVED** [review]
LGTM ❤️

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by craig-seeman** [comment]
Lol, sorry for the two master merges.. I hope I did that correctly..

I don't OSS contribute a lot so have not worked with forks much 😊

**Comment by g1eny0ung** [comment]
> Lol, sorry for the two master merges.. I hope I did that correctly..
> 
> I don't opensource contribute a lot so have not worked with forks much 😊

It's ok to do this. 😄

**Pull request merged**
