### PR TITLE
fix default percent field in iochaos

### LINKED ISSUE #2843: IOChaos: default percent field not work
## Bug Report

**What version of Kubernetes are you using?**
 

1.20.0 
**What version of Chaos Mesh are you using?**

v2.1.1
**What did you do?**
 

Create an IOChaos experiment and set the `percent` field empty. According to chaos mesh docs, the default `percent` field is `100`. But when I set it to empty, the chaos action didn't work.  

```
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-delay-example
spec:
  action: latency
  mode: one
  selector:
    labelSelectors:
      statefulset.kubernetes.io/pod-name: advanced-tidb-tikv-0
    namespaces:
      - tidb-c0
  volumePath: /var/lib/tikv
  path: /var/lib/tikv/raft/*
  delay: "1s"
  ```

When I set the `percent` to `100`, this chaos experiment worked. 

**What did you expect to see?**
 

**What did you see instead?** 

IO delay action was working. 

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by z1cheng**
Signed-off-by: z1cheng <imchench@gmail.com>

### What problem does this PR solve?

Close #2843 

### What's changed and how it works?

Add a comment on the Percent field in IOChaosSpec

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Comment by iguoyr** [comment]
@z1cheng Hi, thanks for your contributing! There are two things need to do:

1. run `make check`, you could refer to [this contributing document](https://github.com/chaos-mesh/chaos-mesh/blob/master/CONTRIBUTING.md)
2. add a changelog to [`CHANGELOG.md`](https://github.com/chaos-mesh/chaos-mesh/blob/master/CHANGELOG.md)

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by iguoyr — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@z1cheng Can you cherry-pick this pr to release-2.1 branch manualy?

**Comment by z1cheng** [comment]
@cwen0 Sure, I will~

**Pull request merged**
