### PR TITLE
chore: bump version to toda to v0.2.4

### LINKED ISSUE #3680: io-delay experiment causes restart of cassandra container
**What version of Kubernetes are you using?**
_Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}_

**What version of Chaos Mesh are you using?**
_v2.3.1_

**What did you do?**
_Run  IOChaos, type=delay=10ms  for cassandra_ 

Content of io-delay.yaml file:
              apiVersion: chaos-mesh.org/v1alpha1
              kind: IOChaos
              metadata:
                name: io-delay-cassandra
                namespace: footprint
              spec:
                action: latency
                mode: one
                selector:
                  labelSelectors:
                    "statefulset.kubernetes.io/pod-name": cassandra-0
                volumePath: /var/lib/cassandra/ 
                delay: "10ms"
                percent: 10
                duration: "10s"

**What did you expect to see?**
_I expect to see read/write delays of 10ms from specified volumePath._

**What did you see instead?**
_Restart of cassandra container and_ 

See chaos-daemon log
[chaosMeshDaemonCassandraLog.zip](https://github.com/chaos-mesh/chaos-mesh/files/9674666/chaosMeshDaemonCassandraLog.zip)

Last lines of cassandra container log:
[cassandra_IOchaosMesh.zip](https://github.com/chaos-mesh/chaos-mesh/files/9674980/cassandra_IOchaosMesh.zip)

### LINKED ISSUE #4446: io-fault experiment causes restart of cassandra container
## Bug Report

**What version of Kubernetes are you using?**
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"chart-2.5.1", GitCommit:"08b173528f315d3a6621b9be5566e74ab9e0d35d", BuildDate:"2023-01-14T02:33:15Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
**+ Using a chaos-daemon black build which we got from [https://github.com/chaos-mesh/chaos-mesh/issues/3680](https://github.com/chaos-mesh/chaos-mesh/issues/3680) as a solution for a similar issue.**

**What did you do? / Minimal Reproducible Example**
Run IOChaos, action=fault, errNo=5 for cassandra

Content of io-fault.yaml file:

kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh-experiment
  name: io-fault-experiment-o6wcip7g
spec:
  selector:
    namespaces:
      - robu
    labelSelectors:
      app: myapp
      app.kubernetes.io/name: myapp
  mode: all
  containerNames:
    - cassandra
  action: fault
  errno: 5
  path: /var/lib/cassandra/**/*
  percent: 100
  volumePath: /var/lib/cassandra
  duration: 60s

**What did you expect to see?**
I expected to see volume path /var/lib/cassandra produces I/O errors for read/write operations during chaos.
And after the chaos has finished Cassandra comes back to ready state.

**What did you see instead?**
Some of the Cassandra containers produced "A fatal error has been detected by the Java Runtime Environment" error and got restarted and got back into ready state after the chaos ended. But some of them were not affected by this error, they did not get restarted and stuck in 'not ready' state after the chaos ended.

The issue looks very similar to a previously reported issue for I/O latency chaos: 
[https://github.com/chaos-mesh/chaos-mesh/issues/3680](https://github.com/chaos-mesh/chaos-mesh/issues/3680)

**Chaos Daemon log**
[chaos-daemon-96ds9.log](https://github.com/user-attachments/files/16053331/chaos-daemon-96ds9.log)
[chaos-daemon-qg2xz.log](https://github.com/user-attachments/files/16053334/chaos-daemon-qg2xz.log)
[chaos-daemon-s7mzn.log](https://github.com/user-attachments/files/16053337/chaos-daemon-s7mzn.log)

**Cassandra error log**: 
[cassandra.log](https://github.com/user-attachments/files/16053364/cassandra.log)

### LINKED ISSUE #4447: IO fault experiment causes file system corruption into volumePath of opensearch
## Bug Report

**What version of Kubernetes are you using?**
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"chart-2.5.1", GitCommit:"08b173528f315d3a6621b9be5566e74ab9e0d35d", BuildDate:"2023-01-14T02:33:15Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
+ Using a chaos-daemon black build which we got from https://github.com/chaos-mesh/chaos-mesh/issues/3680.

**What did you do? / Minimal Reproducible Example**
Run IOChaos, action=fault, errNo=5 for opensearch

Content of io-fault.yaml file:
kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-mesh-experiment
  name: io-fault-experiment-1aidwk2s
spec:
  selector:
    namespaces:
      - robu
    labelSelectors:
      app: myapp
      app.kubernetes.io/name: myapp
  mode: all
  containerNames:
    - data
  action: fault
  errno: 5
  path: /opt/opensearch/data/**/*
  percent: 100
  volumePath: /opt/opensearch/data
  duration: 60s

**What did you expect to see?**
I expected to see volume path  /opt/opensearch/data produces I/O errors for read/write operations during chaos.
And I expected the chaos to finish successfully and after the chaos has finished all I/O errors disappear.

**What did you see instead?**
1. The chaos stuck in running state. With followin message:
Failed to apply chaos: failed to apply for pod mypod: rpc error: code = Unknown desc = toda startup takes too long or an error occurs: Transport endpoint is not connected (os error 107)

2. /opt/opensearch/data is corrupted and inaccessible:
ls -la /opt/opensearch/data
ls: cannot access '/opt/opensearch/data': Transport endpoint is not connected

3. The __chaosfs__data__ folder is not empty.
ls -la /opt/opensearch/__chaosfs__data__/
total 28
drwxrwsr-x 4 root   10000  4096 Jul  2 11:49 .
drwxrwxr-x 1 143743 root   4096 Jul  2 12:43 ..
drwxrws--- 2 root   10000 16384 Jul  2 11:45 lost+found
drwxrwsr-x 3 143743 10000  4096 Jul  2 11:49 nodes

**Output of chaosctl**
[chaos_daemon_opensearch.log](https://github.com/user-attachments/files/16069336/chaos_daemon_opensearch.log)

Earlier we had a similar issue with I/O latency chaos for postgres: [https://github.com/chaos-mesh/chaos-mesh/issues/4330](https://github.com/chaos-mesh/chaos-mesh/issues/4330)

### PR DESCRIPTION
**Pull request by YangKeao**
## What problem does this PR solve?

It upgrades the `toda` component to version v0.2.4. It mainly introduces the issue needed by https://github.com/chaos-mesh/chaos-mesh/issues/3680.

close #3680

## What's changed and how it works?

https://github.com/chaos-mesh/toda/pull/42. This PR fixes the incorrect `mmap` argument :+1: .

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [x] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by balazs-sz** [comment]
Hi,
Thanks for the merge.
But please do not close [4447](https://github.com/chaos-mesh/chaos-mesh/issues/4447) and [4446](https://github.com/chaos-mesh/chaos-mesh/issues/4446).
This fix does not solve those issues. Those are very similar but for I/O fault chaos.

**Comment by eedjama** [comment]
Hi @YangKeao and @g1eny0ung,
the fix solves the issue only for the IO-chaos **latency** case.
Unfortunately it does not solve the IO-chaos **fault** case.
We are now looking into the needed adaptations to make it applicable also for the IO-chaos **fault**.
Thanks.

**Comment by STRRL** [comment]
> Hi @YangKeao and @g1eny0ung, the fix solves the issue only for the IO-chaos **latency** case. Unfortunately it does not solve the IO-chaos **fault** case. We are now looking into the needed adaptations to make it applicable also for the IO-chaos **fault**. Thanks.


Hi @eedjama , we are looking forward for your check.

**Comment by g1eny0ung** [comment]
@eedjama Thank you very much for your continued investigation. 👍🏼

**Pull request merged**
