### PR TITLE
Protect chaos available namespace and filter namespaces if needed

### LINKED ISSUE #3452: Return only annotated namespaces when filter is enabled
## Feature Request

**Is your feature request related to a problem? Please describe:**

I’ve enabled filter namespace in the controller:

```
# If enabled, only pods in the namespace annotated with `"chaos-mesh.org/inject": "enabled"` could be injected
enableFilterNamespace: true
```

When logged in to the UI I can see all available namespaces in the cluster. For the record - only one namespace has this annotation (demo-bookapp)

image

But as you can see full list of namespaces is visible in the UI

**Describe the feature you'd like:**

Ideally, I'd like Chaosmesh to return only those namespace that has the annotation `"chaos-mesh.org/inject": "enabled"`.

Even though we can't run chaos tests against the namespaces that do not have this annotation, reducing information noise would improve the UX. It would, also, simplify things because when a cluster has >100 namespaces, but only, let's say, 5 namespaces have this annotation, there is no point in returning rest of the namespaces

Return only namespaces that have the annotation will remove information noise in a couple of places:

image

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

### PR DESCRIPTION
**Pull request by brnck**
Signed-off-by: brnck <a.berneckas@gmail.com>

### What problem does this PR solve?

Close #3452 

### What's changed and how it works?

This PR fixes endpoint `/api/common/chaos-available-namespaces` when **SecurityMode** and ** enableFilterNamespace** - both set to true.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [X] Manual test (add steps below)

Steps to test:
* Deploy chaos-mesh
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return all namespaces
* Set `enableFilterNamespace` to true and redeploy.
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return `[]`
* `kubectl annotate ns chaos-mesh chaos-mesh.org/inject=enabled`
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return `["chaos-mesh"]`
* Set `SecurityMode` to true and redeploy.
* `curl <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return empty body
* Create token using **token generator** feature in dashboard UI
* `curl -H "Authorization: Bearer <generated_token>" <domain.tld>:<port>/api/common/chaos-available-namespaces` - will return `["chaos-mesh"]`

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]

**Review by xlgao-zju — APPROVED** [review]
LGTM

**Comment by brnck** [comment]
@STRRL @xlgao-zju Looks like I can't execute a re-run on failing tests. Can you do that so this PR would be merged?

**Comment by STRRL** [comment]
> @STRRL @xlgao-zju Looks like I can't execute a re-run on failing tests. Can you do that so this PR would be merged?

Sorry for the late response. I would rerun the test!

**Pull request merged**
