### PR TITLE
chaosctl: cleanup init functions, avoid load kubernetes client before operate anything

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

It's a part of #1397.
### What is changed and how does it work?

- cleanup unnecessary `func init(){}` from codes;
- initial kubernetes client only when context need it 
 
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by STRRL** [comment]
I think this PR is ready to review. PTAL @Yiyiyimu @YangKeao @WangXiangUSTC @cwen0.

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by Yiyiyimu — APPROVED** [review]
LGTM

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
