### PR TITLE
[WIP] Enable test for nirvana

### PR DESCRIPTION
**Pull request by AsterNighT**
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by YangKeao** [comment]
Great. This PR can be used as the final target of `nirvana`, as it cannot pass a lot of tests now :crying_cat_face:

**Comment by AsterNighT** [comment]
> Great. This PR can be used as the final target of `nirvana`, as it cannot pass a lot of tests now 😿

I'll check the failed tests and see if some of them can be fixed now.

**Pull request closed without merging**
