### PR TITLE
ci: fix `upload-image` action 

### LINKED ISSUE #2896: Github Action: action `Upload Image` was broken when building chaos-daemon on arm64
## Bug Report

**What version of Kubernetes are you using?**

N/A

**What version of Chaos Mesh are you using?**

master, 4d3bfeda0f2c68c0416cfbf06c132191f751af6a

**What did you do?**

N/A

**What did you expect to see?**
N/A

**What did you see instead?**
the scheduled daily CI failed when building chaos-daemon on arm64: https://github.com/chaos-mesh/chaos-mesh/actions/workflows/upload_image.yml

```
# github.com/chaos-mesh/chaos-mesh/pkg/time
pkg/time/fake_image.go:59:18: undefined: ptrace.Trace
```

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by iguoyr**
### What problem does this PR solve?

Close #2896 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

test in my repository: https://github.com/iguoyr/chaos-mesh/runs/5314637511?check_suite_focus=true

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
e2e failed with error message:

```
 ERROR: image: "localhost:5000/pingcap/e2e-helper:latest" not present locally
```

you should also update the hard-coded e2e helper name if you would like to change the `IMAGE_PROJECT` in makefile. 

(How about making these changes in another PR?)

**Comment by iguoyr** [comment]
> e2e failed with error message:
> 
> ```
>  ERROR: image: "localhost:5000/pingcap/e2e-helper:latest" not present locally
> ```
> 
> you should also update the hard-coded e2e helper name if you would like to change the `IMAGE_PROJECT` in makefile.
> 
> (How about making these changes in another PR?)

Ok! I have already rollbacked these changes.

**Pull request merged**
