### PR TITLE
Remove token checker when listing namespaces

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: Cwen Yin <cwenyin0@gmail.com>

### What problem does this PR solve?

`chaos-available-namespaces` API will be used before entering Token. If we add this checker will make generating token action fail.  Caused by https://github.com/chaos-mesh/chaos-mesh/pull/3473

### What's changed and how it works?  

Remove token checker when listing namespaces. 

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [x] release-2.3
  - [x] release-2.2

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
> If we add this checker will make generating token action fail.

What does this mean?

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> > If we add this checker will make generating token action fail.
> 
> What does this mean?

image
image

**Comment by g1eny0ung** [comment]
> > If we add this checker will make generating token action fail.
> 
> What does this mean?

There is some missing context here.

This is because we need to get the available namespaces before we can get the token. The error will happen in this place (https://chaos-mesh.org/docs/manage-user-permissions/#create-user-accounts-and-bind-permissions). Users need to get the available ns in advance when generating the RBAC templates.

**Comment by cwen0** [comment]
> > If we add this checker will make generating token action fail.
> 
> What does this mean?

This checker will make generating RBAC template fail.

**Comment by STRRL** [comment]
> > > If we add this checker will make generating token action fail.
> > 
> > 
> > What does this mean?
> 
> There is some missing context here.
> 
> This is because we need to get the available namespaces before we can get the token. The error will happen in this place (https://chaos-mesh.org/docs/manage-user-permissions/#create-user-accounts-and-bind-permissions). Users need to get the available ns in advance when generating the RBAC templates.

Is there any other solutions to archive #3452 and also avoid breaking things? @g1eny0ung @cwen0 🤔🤔

**Comment by cwen0** [comment]
> > > > If we add this checker will make generating token action fail.
> > > 
> > > 
> > > What does this mean?
> > 
> > 
> > There is some missing context here.
> > This is because we need to get the available namespaces before we can get the token. The error will happen in this place (https://chaos-mesh.org/docs/manage-user-permissions/#create-user-accounts-and-bind-permissions). Users need to get the available ns in advance when generating the RBAC templates.
> 
> Are there any other solutions to archive #3452 and also avoid breaking things? @g1eny0ung @cwen0 🤔🤔

We can add an other API for generating RBAC templates.

**Comment by brnck** [comment]
> > > > > If we add this checker will make generating token action fail.
> > > > 
> > > > 
> > > > What does this mean?
> > > 
> > > 
> > > There is some missing context here.
> > > This is because we need to get the available namespaces before we can get the token. The error will happen in this place (https://chaos-mesh.org/docs/manage-user-permissions/#create-user-accounts-and-bind-permissions). Users need to get the available ns in advance when generating the RBAC templates.
> > 
> > 
> > Are there any other solutions to archive #3452 and also avoid breaking things? @g1eny0ung @cwen0 🤔🤔
> 
> We can add an other API for generating RBAC templates.

It would be great not to show all namespaces to an unauthorized user as well as not break the current feature to generate tokens.

Showing all namespaces for unauthorized users poses some security risks I am afraid

**Pull request merged**
