### PR TITLE
Fix typo in NewExperiment screen

### PR DESCRIPTION
**Pull request by xbx**
### What problem does this PR solve?

> Problem Summary:

Just a typo.

### What's changed and how it works?

> What's Changed:

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @xbx , thanks for your contribution!

Please fix the DCO first, you could inspect the detail by clicking the failed `DCO`  check. :D

**Review by g1eny0ung — APPROVED** [review]
LGTM ❤️

**Comment by cwen0** [comment]
@xbx Can you fix the [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/2535/checks?check_run_id=4236723926) first?

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
Hi @xbx, I make an update on your branch and fix the DCO issue because you enable the `Allow edits and access to secrets by maintainers`. Thanks for your contribution!

**Pull request merged**
