### PR TITLE
JVMChaos: support inject fault into MySQL client (#3277)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3277 to release-2.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In chaos-mesh repo:
git pr https://github.com/chaos-mesh/chaos-mesh/pull/3362
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/chaos-mesh.git pr/3362:release-2.2-d120d2db5ec5
```

---

### What problem does this PR solve?

close issue https://github.com/chaos-mesh/chaos-mesh/issues/2977

(this pr is cherry-picked from https://github.com/chaos-mesh/chaos-mesh/pull/3189)

### What's changed and how it works?

Using `sql-helper` in [byteman-helper](https://github.com/chaos-mesh/byteman-helper/tree/main/BytemanHelper#sqlhelper) to analyze SQLs, and judge whether to inject fault.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @WangXiangUSTC , the position of changelog need updates

**Comment by Mini256** [comment]
Testing bots:

/cc YangKeao

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
