### PR TITLE
move UnlockOSThread before ptrace error

### PR DESCRIPTION
**Pull request by dongzerun**
Signed-off-by: zerun dong <zerun.dong@grabtaxi.com>

### What problem does this PR solve?
will not unlockosthread if ptrace return an error

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
I wonder why these github actions don't run.

**Comment by dongzerun** [comment]
looks there no such file cluster/log-dump/log-dump.sh
how to fix that? should i rebase master?

**Comment by YangKeao** [comment]
@STRRL  @cwen0 Really wired. Should we merge this PR manually? The Github doesn't run actions for it :facepalm: .

**Comment by STRRL** [comment]
> @STRRL @cwen0 Really wired. Should we merge this PR manually? The Github doesn't run actions for it  .

Maybe affected by https://www.githubstatus.com/incidents/ltvyl42v20j5. 

I agree with you, but it seems we even could not manually click the "Merge" button without these checks. :cry: 

Maybe we need to ask @dongzerun for closing this PR and create a duplicate new PR.

**Review by YangKeao — APPROVED** [review]

**Review by cwen0 — APPROVED** [review]

**Pull request merged**
