### PR TITLE
style: let groupimports could effect on all codes

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

`make groupimports` will not reformat codes under `/test`

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
how about just delete `chaos-mesh/test` in `PACKAGE_LIST`

**Comment by STRRL** [comment]
> how about just delete `chaos-mesh/test` in `PACKAGE_LIST`

`make test` depends on `PACKAGE_LIST`, I think we do not want execute e2e test with `make test`.

**Comment by WangXiangUSTC** [comment]
> > how about just delete `chaos-mesh/test` in `PACKAGE_LIST`
> 
> `make test` depends on `PACKAGE_LIST`, I think we do not want execute e2e test with `make test`.

I mean

PACKAGE_LIST := go list ./... | grep -vE "chaos-mesh/test|pkg/ptrace|zz_generated|vendor" 
=>
PACKAGE_LIST := go list ./... | grep -vE "pkg/ptrace|zz_generated|vendor"

**Comment by STRRL** [comment]
> > > how about just delete `chaos-mesh/test` in `PACKAGE_LIST`
> > 
> > 
> > `make test` depends on `PACKAGE_LIST`, I think we do not want execute e2e test with `make test`.
> 
> I mean
> 
> PACKAGE_LIST := go list ./... | grep -vE "chaos-mesh/test|pkg/ptrace|zz_generated|vendor"
> =>
> PACKAGE_LIST := go list ./... | grep -vE "pkg/ptrace|zz_generated|vendor"

Yes, I think I get your point. In our `Makefile`:

```makefile
# Run tests
test: failpoint-enable generate manifests test-utils
	rm -rf cover.* cover
	$(GOTEST) $$($(PACKAGE_LIST)) -coverprofile cover.out.tmp
	cat cover.out.tmp | grep -v "_generated.deepcopy.go" > cover.out
	@$(FAILPOINT_DISABLE)
```
I think it intent to skip `*_test.go` under `/test` directory, which is our e2e test codes.

**Comment by WangXiangUSTC** [comment]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
