### PR TITLE
update install.sh

### PR DESCRIPTION
**Pull request by fewdan**
Signed-off-by: “fewdan” <fewdan@hotmail.com>

### What problem does this PR solve?
update install.sh

### What is changed and how does it work?
add schedule to install.sh

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by STRRL** [comment]
But we do NOT have a webhook for `Schedule`. :thinking:

**Comment by fewdan** [comment]
> But we do NOT have a webhook for `Schedule`. 🤔

@STRRL 
Oh yes, we have to update install.sh after adding webhook.

**Comment by AsterNighT** [comment]
Our webhooks need a bit refactor. It is quite difficult to write a proper webhook that work for schedule now.

**Comment by AsterNighT** [comment]
Now there is a webhook for schedule. I think this pr can be merged?

**Review by AsterNighT — APPROVED** [review]

**Comment by fewdan** [comment]
@STRRL 
After [schedule webhook](https://github.com/chaos-mesh/chaos-mesh/pull/1939) merged, the install.sh can be updated now?

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
