### PR TITLE
Update e2e test for kubernetes v1.26, v1.27 and v1.28 as v1.25 is out of life cycle.

### PR DESCRIPTION
**Pull request by huangyingting**
## What problem does this PR solve?

Update e2e test pipeline for kubernetes v1.26, v1.27 and v1.28 as v1.25 is out of life cycle.
All tests are passed. We need to update docs to state kubernetes supported version.

## What's changed and how it works?
Update e2e test pipeline for kubernetes v1.26, v1.27 and v1.28 as v1.25 is out of life cycle.

## Related changes

- [x] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [x] E2E test
- [ ] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Hi @huangyingting, please sign off your commits to pass the DCO check. You can find the details above, at the end of the PR template.

**Review by g1eny0ung — APPROVED** [review]
Since all the e2e tests are passed. I've no questions to merge, and I will update the docs soon for this update.

**Comment by huangyingting** [comment]
@g1eny0ung , can you help on the merge, it looks still stuck at tide "Pending — Not mergeable. Needs lgtm label."

**Comment by g1eny0ung** [comment]
> @g1eny0ung , can you help on the merge, it looks still stuck at tide "Pending — Not mergeable. Needs lgtm label."

Yep. I didn't add the `lgtm` label because I still wait for @STRRL to review https://github.com/chaos-mesh/website/pull/412.

**Comment by g1eny0ung** [comment]
> @STRRL and @g1eny0ung , need approve again, when I update to merge, it seems the lable LGTM get removed again.

Got it. Now it's merged.

**Pull request merged**
