### PR TITLE
[BugBash] SC2206: Use quote to prevent word splitting/globbing

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?
Use quote to prevent word splitting/globbing

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
Hi @anuragpaliwal80 , please update the CHANGELOG ❤️

**Pull request merged**
