### PR TITLE
bump container-runtime to 0.11.0, kubernetes related dependencies to 0.23.1

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2752;

### What's changed and how it works?

- bump container runtime to 0.11.0
- bump kubernetes related dependencies to 0.23.1
- bump klog to v2

and there are lots of updates (about 3700 lines of addition, 1300 lines of deletion) in crd YAML files because of some description/comments and fields about container updated in kubernetes 1.23 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
This pr is ready for review, PTAL

/cc @iguoyr @YangKeao @cwen0 @Hexilee

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
