### PR TITLE
Rollback license checker version

### PR DESCRIPTION
**Pull request by Andrewmatilde**
Signed-off-by: andrewmatilde <davis6813585853062@outlook.com>

### What problem does this PR solve?
license checker:lastest failed to load .gitignore now. So I rollback it to v0.4.0.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by Andrewmatilde** [comment]
PTAL @cwen0 , @STRRL

**Comment by STRRL** [comment]
is there an upstream issue? Or that behavior is by design?

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
> is there an upstream issue? Or that behavior is by design?

A little weird, I could not reproduce the failed CI check with latest `license-eye`. Maybe there are some differences between my local env and github action

**Comment by STRRL** [comment]
> is there an upstream issue? Or that behavior is by design?

I could reproduce this situation now, but actually `license-eye` works well as expected, we did track the `.gitkeep` and `yarn.lock`, but the legacy `.gitignore` pattern ignores them by fault.

I prefer to using `apache/skywalking-eyes` with the `latest` version (the latest release version, not `main`), and configure it correctly.

**Pull request merged**
