### PR TITLE
remove host port declare in chaos-daemon-daemonset.yaml, background r…

### PR DESCRIPTION
**Pull request by track87**
…ef https://github.com/chaos-mesh/chaos-mesh/pull/1206

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by cwen0** [comment]
@track87 Thanks for your contribution! Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/2862/checks?check_run_id=5120920667) check first?

**Comment by cwen0** [comment]
> @track87 Thanks for your contribution! Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/2862/checks?check_run_id=5120920667) check first?

@track87 Can you try to fix it? Thanks!

**Comment by cwen0** [comment]
@track87 Do you need any help on this pr?

**Comment by xlgao-zju** [comment]
@cwen0 Talked with @track87 offline, I will file a PR to fix this.

**Pull request closed without merging**
