### PR TITLE
models and controller of workflow http api

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What is changed and how does it work?

Reference: #1521

This PR appends the models and controller for workflow HTTP API which communicates with the frontend.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

It could generate the expected swagger file.

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM 😆

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
