### PR TITLE
Add rollme for chaos dashboard

### PR DESCRIPTION
**Pull request by AsterNighT**
Signed-off-by: AsterNighT <klxjt99@outlook.com>

### What problem does this PR solve?

Now helm will upgrade chaos dashboard if image is updated.

Problem Summary:

### What is changed and how it works?

Add rollme for chaos dashboard

What's Changed:

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by fewdan** [comment]
It seems that CI failed, maybe you should update "update.sh"?

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
