### PR TITLE
cherrypick: delete ip/hostname check in validation webhook (#3483)

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: Jerry Jia <jerry.jia@sap.com>

cherrypick ##3483 to branch release-2.2

### CODE REVIEW

**Comment by STRRL** [comment]
/cc @WangXiangUSTC @Andrewmatilde 

PTAL

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Review by xlgao-zju — APPROVED** [review]
LGTM

**Pull request merged**
