### PR TITLE
docs:add a chaos demo in Get Started

### PR DESCRIPTION
**Pull request by wuxiaohui94**
### What problem does this PR solve?

[https://github.com/chaos-mesh/chaos-mesh/issues/953](url)
### What is changed and how does it work?
move run_chaos_experiment  to Get Started
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
@wuxiaohui94 Please fix conflicts first, thanks!

**Comment by zhouqiang-cl** [comment]
@wuxiaohui94 thank you for your contribution

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by wuxiaohui94** [comment]
PTAL @fewdan

**Pull request merged**
