### PR TITLE
chore: remove `IN_DOCKER` env in `Makefile`

### LINKED ISSUE #3988: Remove `IN_DOCKER` env entry in `Makefile`
Ref: https://github.com/chaos-mesh/chaos-mesh/pull/3986#discussion_r1152731381

Since our default build behavior is to build using containers to avoid compatibility issues, we should no longer provide an `IN_DOCKER` env entry to trigger a local build in `Makefile`.

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What problem does this PR solve?

Close #3988

### What's changed and how it works?

Since our default build behavior is to build using containers to avoid compatibility issues, we should no longer provide an `IN_DOCKER` env entry to trigger a local build in `Makefile`.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@cwen0 PTAL.

**Comment by STRRL** [comment]
it seems `IN_DOCKER` still is included in `build/get_env_shell.py`.

we could also remove that.

**Comment by g1eny0ung** [comment]
> it seems `IN_DOCKER` still is included in `build/get_env_shell.py`.
> 
> we could also remove that.

Since we will still be running `get_env_shell.py` in the container when building, if we want to completely remove the `IN_DOCKER` environments, we need to find another way to determine whether the current process is running in the container.

I found a helpful stackoverflow link, I will test it to see if it works properly: https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker.

**Comment by g1eny0ung** [comment]
> > it seems `IN_DOCKER` still is included in `build/get_env_shell.py`.
> > we could also remove that.
> 
> Since we will still be running `get_env_shell.py` in the container when building, if we want to completely remove the `IN_DOCKER` environments, we need to find another way to determine whether the current process is running in the container.
> 
> I found a helpful stackoverflow link, I will test it to see if it works properly: https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker.

@STRRL Test in my local and works. Please check again.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
