### PR TITLE
chore: update image project name in Makefile

### PR DESCRIPTION
**Pull request by TangliziGit**
Signed-off-by: TangliziGit <tanglizimail@foxmail.com>

### What problem does this PR solve?

> Problem Summary:

Since the image project name of the image is changed from `pingcap` to `chaos-mesh`, the corresponding image project name in the Makefile has not changed. 

The goal of this PR is to modify the image project name into `chaos-mesh`, which images are produced by `make` and `make docker-push`.

### What's changed and how it works?

> What's Changed:

The default value of `IMAGE_PROJECT` and the hardcoded image project name in `docker-push` are replaced into `chaos-mesh`.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@TangliziGit Can you update the e2e test files?  https://github.com/chaos-mesh/chaos-mesh/blob/master/hack/run-e2e.sh#L69-L70

**Comment by cwen0** [comment]
> @TangliziGit Can you update the e2e test files? https://github.com/chaos-mesh/chaos-mesh/blob/master/hack/run-e2e.sh#L69-L70

This issue blocks the e2e tests.

**Comment by TangliziGit** [comment]
> @TangliziGit Can you update the e2e test files? https://github.com/chaos-mesh/chaos-mesh/blob/master/hack/run-e2e.sh#L69-L70

OK

**Comment by cwen0** [comment]
Here also need to be updated. Thanks! https://github.com/chaos-mesh/chaos-mesh/blob/master/hack/run-e2e.sh#L141-L144

**Comment by TangliziGit** [comment]
OK thank you, I will run the e2e-test to check it before the new commit.

**Pull request merged**
