### PR TITLE
Imagepullsecrets feature

### LINKED ISSUE #2199: Enable the ability to configure imagePullSecrets from the values file to pull chaos mesh images from private registries
## Feature Request

**Is your feature request related to a problem? Please describe:**
When your chaos mesh images reside in a private registry, one may need the ability to configure a docker secret via imagePullSecrets in the helm values file which can be enabled and overridden as required

**Describe the feature you'd like:**
Specify an imagePullSecrets parameter in the values file, which can be overridden with a docker secret. If this imagePullSecrets value is present, it can be used in the 5 deployment files to pull images from a private registry

**Describe alternatives you've considered:**
The alternative we currently use is to clone this repo, make this change and install from our own repo

**Teachability, Documentation, Adoption, Migration Strategy:**
Specify imagePullSecrets in the values file
```
imagePullSecrets: []
#- name: secretName
```
Reference in the deployment files 
```
{{- if .Values.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}
```

### PR DESCRIPTION
**Pull request by aido123**
### What problem does this PR solve?

Issue Number: close #2199

Problem Summary:
When your chaos mesh images reside in a private registry, one may need the ability to configure a docker secret via imagePullSecrets in the helm values file which can be enabled and overridden as required.

### What is changed and how it works?

Proposal/What's Changed:
Specify an imagePullSecrets parameter in the values file, which can be overridden with a docker secret. If this imagePullSecrets value is present, it can be used in the 4 deployment files and 1 daemonset file to pull images from a private registry

### Related changes
N/A

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

#### Manual Steps to Test
* Create a new private azure container registry i.e. chaosmeshtest.azurecr.io
* Publish chaos mesh images to chaosmeshtest.azurecr.io
* * pingcap/chaos-daemon
* * pingcap/chaos-dashboard
* * pingcap/chaos-kernel
* * pingcap/chaos-mesh
* * pingcap/coredns
* * prom/prometheus

* Deploy kind cluster locally
* Create Docker Secret to access chaosmeshtest.azurecr.io
```
kubectl create secret docker-registry regcred --docker-server=chaosmeshtest.azurecr.io --docker-username=*** --docker-password=*** --docker-email=adrian.hynes@fmr.com
```
* Install helm chart with new registry, imagePullSecrets and enabling dashboard, dns server and prometheus
```
helm install chaos-mesh helm/chaos-mesh/ --set registry=chaosmeshtest.azurecr.io --set dashboard.create=true --set dnsServer.create=true --set prometheus.create=true --set imagePullSecrets[0].name=regcred
```
* All chaos pods images pulled down successfully from private registry and running as expected
* Simple test
* * Deploy nginx Pod
* * Deploy simple pod failure

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
New imagePullSecrets parameter added to the values file, which can be overridden with a docker secret. If this imagePullSecrets value is present, it can be used in the 4 deployment files and 1 daemonset file to pull images from a private registry
```

### CODE REVIEW

**Comment by cwen0** [comment]
@aido123 Thanks for your contribution!

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Pull request merged**
