### PR TITLE
daemon: avoid tls downgrade attack by setting min version of tls

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

The default minimum version of `TLS` is 1.0. This PR will set it to TLS 1.3

It doesn't have any compatibility problem because Chaos Mesh is using TLS 1.3 now.

### CODE REVIEW

**Comment by YangKeao** [comment]
I have verified that it avoids serving for the lower version of tls.

```bash
openssl s_client -connect localhost:31767 -tls1_2
```

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM

**Pull request merged**
