### PR TITLE
chore: support `KernelChaos` in `AutoForm`

### LINKED ISSUE #3420: ui(workflow-ng): support `KernelChaos`

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Close #3420

### What's changed and how it works?

This PR supports creating `KernelChaos` in the `<AutoForm />` component, which is introduced in the next generation `New Workflow`. Below is a demo:

https://user-images.githubusercontent.com/15034155/178754930-c0d82f83-2bc7-4531-9435-cfff04df8f39.mp4

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Yeah! The array `[]Frame` finally works!

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by cwen0** [comment]
@g1eny0ung Please fix conflicts!

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
