### PR TITLE
fix: use `*time.Time` to represent finish time

### LINKED ISSUE #1659: dashboard: can't insert experiment in MySQL NO_ZERO_IN_DATE mode
## Bug Report

**What version of Kubernetes are you using?**

> Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

> Latest

**What did you do?**

Helm install with MySQL driver:

```sh
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set dashboard.create=true,dashboard.securityMode=false,dashboard.env.DATABASE_DRIVER=mysql,dashboard.env.DATABASE_DATASOURCE="root@tcp(docker.for.mac.localhost:3306)/chaosmesh?parseTime=True"
```

**What did you expect to see?**

After creating an experiment, the database should insert its record successfully.

**What did you see instead?**

Data insertion failed.

After my test, seems this related to https://dev.mysql.com/doc/refman/5.7/en/date-and-time-types.html.

Because the experiment will not set an exact finish time in the beginning. So we will get an error like: `Incorrect datetime value: '0000-00-00'`.

A temporary solution:

```sql
show variables like 'sql_mode';
-- Copy all values except NO_ZERO_IN_DATE.
set global sql_mode=xxx  -- set again
```

Since zero time is not recommended, we need to set the unknown time to 1970-01-01(an example) to avoid this problem.

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What problem does this PR solve?

Close #1659

### What's changed and how it works?

Use `*time.Time` to represent the finish time, this can prevent an invalid date `0000-00-00` being inserted when creating a chaos object.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
it might bring breaking changes on db table schema, although we enabled the `AutoMigrate` of gorm.

I would take a try with MySQL later, then I would give my lgtm

**Comment by g1eny0ung** [comment]
> it might bring breaking changes on db table schema, although we enabled the `AutoMigrate` of gorm.
> 
> I would take a try with MySQL later, then I would give my lgtm

Oh...yes, I tested in a new MySQL database and all works fine, but I didn't test on an existing MySQL with old Chaos experiments.

**Comment by STRRL** [comment]
/lgtm

I noticed that gorm already used `null` for that column, no matter whether we use the pointer or not in the go struct.

```sql
create table experiments
(
    id          int unsigned auto_increment
        primary key,
    created_at  datetime      null,
    updated_at  datetime      null,
    deleted_at  datetime      null,
    uid         varchar(255)  null,
    kind        varchar(255)  null,
    name        varchar(255)  null,
    namespace   varchar(255)  null,
    action      varchar(255)  null,
    start_time  datetime      null,
    finish_time datetime      null,
    archived    tinyint(1)    null,
    experiment  varchar(4096) null
);
```

**Pull request merged**
