### PR TITLE
add registry config to the helm chart

### LINKED ISSUE #1385: How can chaos-mesh be installed in intranet eaily?
## Question
According to the chaos-mesh wiki or doc,  it is required to download script or file from git or mirrors,  and it is difficult to do that in intranet.  Comparing with another tool chaos-blade, which could be installed easily in intranet via operator image, is chaos mesh supported by that?  Or is there any way to install chaos-mesh in intranet more easily?   Would you please kindly have a look?

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### What problem does this PR solve?

Fix #1385 . Add a registry configuration in the helm chart.

Example:

```bash
helm install chaos-mesh helm/chaos-mesh -n chaos-testing --set registry=hub.pingcap.com
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
LGTM, and need to resolve conflicts

**Comment by cwen0** [comment]
@YangKeao Please resolve conflicts! Thanks!

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]

**Pull request merged**
