### PR TITLE
Cherry pick #2526 to release 2.0 

### PR DESCRIPTION
**Pull request by STRRL**
* Add: kubebuilder comment for additional display column 'action' and 'duration'

Signed-off-by: dinghq001 <dinghq001@foresealife.com>

* Update: yaml  file by  excuting 'make check'

Signed-off-by: huanqiao Ding <huanqiaoding@sz-dl-254.autox.sz>
Signed-off-by: reigending <1066297896@qq.com>

* Update: remove additional display field  from [HTTPChaos,KernelChaos,StressChaos,TimeChaos] and all field in PodXXXChaos

Signed-off-by: reigending <1066297896@qq.com>

Co-authored-by: dinghq001 <dinghq001@foresealife.com>
Co-authored-by: Ti Chi Robot <ti-community-prow-bot@tidb.io>

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL @ReigenDing @cwen0 @iguoyr

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
