### PR TITLE
helm/templates: use serviceAccountName instead of serviceAccount

### PR DESCRIPTION
**Pull request by cxuu**
### What problem does this PR solve?

For Deployment/DaemenSet, `.spec.serviceAccount` is deprecated. Use `.spec.serviceAccountName` instead.

### What is changed and how does it work?
Update the helm templates to use `.spec.serviceAccountName` instead.

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by sfc-gh-cxu** [comment]
Thanks for the quick review, everyone!

I am new to chaos-mesh. Just realized that I need to run `./hack/update_install_script.sh` and I did so in `8af5c6f`. PTAL.

**Comment by Hexilee** [comment]
> 
> 
> Thanks for the quick review, everyone!
> 
> I am new to chaos-mesh. Just realized that I need to run `./hack/update_install_script.sh` and I did so in [8af5c6f](https://github.com/chaos-mesh/chaos-mesh/commit/8af5c6f6c712d58b75179580b6400071951b701f). PTAL.

It seems we should add `check-install-script` task into dependencies of `check` task in Makefile.

**Comment by sfc-gh-cxu** [comment]
> > Thanks for the quick review, everyone!
> > I am new to chaos-mesh. Just realized that I need to run `./hack/update_install_script.sh` and I did so in [8af5c6f](https://github.com/chaos-mesh/chaos-mesh/commit/8af5c6f6c712d58b75179580b6400071951b701f). PTAL.
> 
> It seems we should add `check-install-script` task into dependencies of `check` task in Makefile.

100%. See 03330cf

**Comment by Hexilee** [comment]
> 
> 
> > > Thanks for the quick review, everyone!
> > > I am new to chaos-mesh. Just realized that I need to run `./hack/update_install_script.sh` and I did so in [8af5c6f](https://github.com/chaos-mesh/chaos-mesh/commit/8af5c6f6c712d58b75179580b6400071951b701f). PTAL.
> > 
> > 
> > It seems we should add `check-install-script` task into dependencies of `check` task in Makefile.
> 
> 100%. See [03330cf](https://github.com/chaos-mesh/chaos-mesh/commit/03330cf35ab00de367632667f53a16c842e61a3f)

Duplicated #1793 😂. OK, I will close that.

**Comment by YangKeao** [comment]
Sorry. The CI cluster is not stable now. We will migrate to a new cluster tomorrow and hope everything could get better :pray:

**Pull request merged**
