### PR TITLE
nirvana: merge from master #1706 

### PR DESCRIPTION
**Pull request by Hexilee**
* remove scheduler and abstract selector

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* generate new yaml files

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* try to modify status

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* try to build new router

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* move selector place

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* define unified selector

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* spec rename

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* enable simple chaos

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* add delete, pause and duration controller

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* add README.md

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* network chaos work well

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* TimeChaos works well

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* format and make check

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* refractor IOChaos

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* pass containerkill and podkill status

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* fix dnschaos

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* run make check

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* reimpl stresschaos

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* add e2e test for stress

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* change name to cpuTime

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* format codes

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* Revert "Use bigheap to inject heap stress (#776)"

This reverts commit c0ff1bf0d0d25157baedbbfc503bf34cb7cf0d01.

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* fix e2e test

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* pass stress chaos test

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* fix AWS test

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* add e2e test for stress (#1612)

* add e2e test for stress

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* change name to cpuTime

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* format codes

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* add comment and refine threshold choice

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* format codes

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

Co-authored-by: Ti Chi Robot <71242396+ti-chi-bot@users.noreply.github.com>
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* remove jvmchaos kernelchaos httpchaos

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* fix dashboard compile error

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* use fx to do dependency injection

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* add kubernetes events

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

* delegate multiple action chaos

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

Co-authored-by: Ti Chi Robot <71242396+ti-chi-bot@users.noreply.github.com>### What problem does this PR solve?

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by AsterNighT** [comment]
it looks chaotic, but /lgtm

**Comment by Hexilee** [comment]
DCO should pass now, could we rerun DOC check?

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
