### PR TITLE
chore: short the project name for image

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/2475;

> Problem Summary:

### What's changed and how it works?

> What's Changed:

change artifact image name, from `ghcr.io/chaos-mesh/chaos-mesh/<component>` to  `ghcr.io/chaos-mesh/<component>`

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [x] Need to **cheery-pick to release branches**, should manually cherry-picked to release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@STRRL Why not update `docker-env` image together?

**Comment by STRRL** [comment]
> @STRRL Why not `build-env` and `dev-env` images together?

I would update for them in another PR.

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
> cherry pick to release-2.0 failed

I would manually cherry-pick it.

**Comment by cwen0** [comment]
@STRRL We also need to update related documents.

**Pull request merged**
