### PR TITLE
fix bug: cpu stress can not reach pod limit in some situation (#3102)

### LINKED ISSUE #3100: cpu stress can not reach pod limit in some situation
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+k3s1", GitCommit:"60f1e80dcb07a32a42688e149778778ffb00ca9a", GitTreeState:"clean", BuildDate:"2021-01-14T22:50:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+k3s1", GitCommit:"60f1e80dcb07a32a42688e149778778ffb00ca9a", GitTreeState:"clean", BuildDate:"2021-01-14T22:50:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

2.1.1

**What did you do?**

set cpu stress experiment `cpu 3` and `cpu-load 30`
and the resource limit of target pod  is 500m
 
image

the cpu usage only reach about 300m

**What did you expect to see?**

the cpu usage should reach about 500m

**What did you see instead?**

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: xianglingao <xianglingao@tencent.com>

Co-authored-by: Ti Chi Robot <ti-community-prow-bot@tidb.io>

### What problem does this PR solve?

- fix #3100 on release-2.1

### What's changed and how it works?

- cherry-pick #3102 into release-2.1
- append changelog

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
I have manually set DCO to pass.

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
