### PR TITLE
Workflow: Eliminate redundant code

### LINKED ISSUE #2054: unnecessary wrap for `[]NodeNameWithTemplate` in Dashboard API
:cold_sweat:  I must be drunk when I wrote these code:

```go
// Node defines a single step of a workflow.
type Node struct {
	Name     string        `json:"name"`
	Type     NodeType      `json:"type"`
	State    NodeState     `json:"state"`
	Serial   *NodeSerial   `json:"serial,omitempty"`
	Parallel *NodeParallel `json:"parallel,omitempty"`
	Template string        `json:"template"`
	UID      string        `json:"uid"`
}

type NodeNameWithTemplate struct {
	Name     string `json:"name,omitempty"`
	Template string `json:"template,omitempty"`
}

// FIXME: unnecessary another wrap of []NodeNameWithTemplate, like struct NodeSerial and NodeParallel

// NodeSerial defines SerialNode's specific fields.
type NodeSerial struct {
	Children []NodeNameWithTemplate `json:"children"`
}

// NodeParallel defines ParallelNode's specific fields.
type NodeParallel struct {
	Children []NodeNameWithTemplate `json:"children"`
}
```

Structs `NodeSerial` and `NodeParallel` are totally useless. It should be like

```go
// Node defines a single step of a workflow.
type Node struct {
	Name     string                `json:"name"`
	Type     NodeType              `json:"type"`
	State    NodeState             `json:"state"`
	Serial   []NodeNameWithTemplate `json:"serial,omitempty"`
	Parallel []NodeNameWithTemplate `json:"parallel,omitempty"`
	Template string                `json:"template"`
	UID      string                `json:"uid"`
}
```

Related test cases and frontend API also need updates

### PR DESCRIPTION
**Pull request by jackwener**
Signed-off-by: jackwener <jakevingoo@gmail.com>

### What problem does this PR solve?

Issue Number: #2054 

Problem Summary:

​	Eliminate redundant code

### What is changed and how it works?

Just Eliminate the unneccessary code.

What's Changed:

### Related changes

- None

### Checklist
Tests

- [x] Unit test

Side effects

- No Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by jackwener** [comment]
@STRRL PTAL

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Comment by STRRL** [comment]
And these changes also make break changes for the frontend, I will raise another PR for updating after this PR merged.

**Comment by STRRL** [comment]
> And these changes also make break changes for the frontend, I will raise another PR for updating after this PR merged.

So @jackwener , we could not just close  #2054 only by this PR. Please remove the "close" magic word in your PR description. :P

**Comment by jackwener** [comment]
> > And these changes also make break changes for the frontend, I will raise another PR for updating after this PR merged.
> 
> So @jackwener , we could not just close #2054 only by this PR. Please remove the "close" magic word in your PR description. :P

Thanks for your remind. I changed it just now.

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
