### PR TITLE
feat(metrics): gRPC and HTTP request duration histogram metrics

### PR DESCRIPTION
**Pull request by TangliziGit**
### What problem does this PR solve?

> Problem Summary: a part of #2397

### What's changed and how it works?

> What's Changed:
1. rename `chaos-daemon` grpc histogram metric into `chaos_daemon_grpc_server_handling_seconds`.
2. add HTTP request duration metrics `chaos-dashboard_http_request_duration_seconds`.
3. expose metrics port for `chaos-dashboard` in `helm/values.yaml`.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [x] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Breaking backward compatibility

In previous versions, the metric endpoint was exposed by manually adding the environment variable `METRIC_ADDRESS: "0.0.0.0:8080"` to the deployment configuration of 'chaos-dashboard'. But the port can not be exposed in the helm template, because `spec.template.spec.containers.ports.containerPort` in deployment configurations and service configurations should be an integer.

In order to expose metric port from the helm template, ChaosDashboardConfig.MetricAdress in `/pkg/config/dashboard/dashboard.go` is modified for `ChaosDashboardConfig.MetricHost` and `ChaosDashboardConfig.MetricPort`.

As a result, if the chaos-dashboard is installed by helm, there is no change required. However, if it is installed manually, you need to change the environment variable `METRIC_ADDRESS: "0.0.0.0:8080"` to `METRIC_HOST: "0.0.0.0"` and `METRIC_PORT: 8080`.

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
/cc @YangKeao @Hexilee @iguoyr 

PTAL

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
