### PR TITLE
chore: show children of task node

### LINKED ISSUE #2051: workflow: enhance conditionalBranches display on UI
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

I want to see the children nodes of one Task node, for example:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: try-task
  namespace: default
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 1h
      children:
        - customized-task
    - name: nginx-kill
      templateType: PodChaos
      deadline: 3m
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-kill
        gracePeriod: 0
    - name: nginx-failure
      templateType: PodChaos
      deadline: 3m
      podChaos:
        selector:
          namespaces:
            - default
          labelSelectors:
            app: nginx
        mode: one
        action: pod-failure
        gracePeriod: 0
    - name: customized-task
      templateType: Task
      task:
        container:
          name: main
          image: busybox
          command:
            - echo
            - a
          resources: {}
      conditionalBranches:
        - target: nginx-kill
          expression: stdout == "a"
        - target: nginx-failure
          expression: exitCode == 0
```

Both `nginx-kill` and `nginx-failure` should be executed after `customized-task` accomplished. But we could not see these two node on Chaos Dashboard for now.
image

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

The Chaos Dashboard API should return the conditional branches in Task WorkflowNode, in `pkg/core/workflow.go`, new struct `ConditionalBranch` need to be created. And one new field in `Node` called `conditionalBranches` also will be created.

After the update of the backend API, the frontend could draw the children nodes.

(Optional) And could we also draw the `expression` on the line which connects the child node?

like that:
image

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Issue Number: close #2051

### What is changed and how it works?

What's Changed:

- change the way to generate workflow nodes of the graph
- use the same way which draws the PrallelNode to draw TaskNode

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No.
* Need to update Chaos Dashboard component, related issue: No.
* Need to cheery-pick to the release branch: Yes, release-2.0.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@g1eny0ung PTAL

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
