### PR TITLE
Revert "update chaos-coredns version to v0.2.4"

### PR DESCRIPTION
**Pull request by g1eny0ung**
@xlgao-zju @STRRL Reverts chaos-mesh/chaos-mesh#3947

This PR has not passed the e2e tests, and there has been a pioneer working on this problem in #3488.

### CODE REVIEW

**Comment by xlgao-zju** [comment]
oops, I see...

but why will `ghcr.io/chaos-mesh/chaos-coredns:v0.2.4` break the e2e test?

**Comment by STRRL** [comment]
> oops, I see...
> 
> but why will `ghcr.io/chaos-mesh/chaos-coredns:v0.2.4` break the e2e test?

I am not sure.. will profile it deeper later...

**Review by STRRL — APPROVED** [review]

**Review by xlgao-zju — APPROVED** [review]
LGTM

**Pull request merged**
