### PR TITLE
chaosdaemon: fix multiple tc filter

### PR DESCRIPTION
**Pull request by cwen0**
### What problem does this PR solve?

If ipset is empty, other filters don't work 😂

### What is changed and how does it work?

Set multiple filter rules when to apply iptables rule and remove the unnecessary checker.

### Checklist

Tests
 

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

```
iptables -L TC-TABLES-0 -n
Chain TC-TABLES-0 (0 references)
target     prot opt source               destination
CLASSIFY   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 CLASSIFY set 1:4
```

### CODE REVIEW

**Comment by cwen0** [comment]
I will add more tests for this on other PR

**Review by STRRL — APPROVED** [review]
LGTM

How we test it? It seems not able to write e2e tests.

**Comment by cwen0** [comment]
> LGTM
> 
> How we test it? It seems not able to write e2e tests.

Yep, at present, I test it by chaosd tool. Although It is hard to write e2e tests,  I will try to do it.

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
