### PR TITLE
Building chaos kernel on master

### LINKED ISSUE #2491: Github Action: fail to build image
https://github.com/chaos-mesh/chaos-mesh/runs/4134396825?check_suite_focus=true  

image

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

> Problem Summary:

It's a part of #2483, close #2491

### What's changed and how it works?

- try to build chaos-kernel with GitHub Action

> What's Changed:

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

I am trying to test it at https://github.com/STRRL/chaos-mesh/actions/runs/1434757478

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Comment by YangKeao** [comment]
The building error was caused by https://github.com/abseil/abseil-cpp/issues/365 . I would try to upgrade absl and see whether it would be better.

**Comment by YangKeao** [comment]
@STRRL I have upgraded the chaos-mesh/bpfki, it should build successfully now.

**Comment by iguoyr** [comment]
> @STRRL I have upgraded the chaos-mesh/bpfki, it should build successfully now.

@YangKeao Hi, I tried to build chaos-kernel image on arm64 machine, and I got some error message:

```
#23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_bad_optional_access.pc
#23 171.7 -- Installing: /bpfki/build/absl/lib/libabsl_bad_optional_access.a
#23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_bad_variant_access.pc
#23 171.7 -- Installing: /bpfki/build/absl/lib/libabsl_bad_variant_access.a
#23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_variant.pc
#23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_compare.pc
#23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_utility.pc
#23 171.7 [ 61%] Completed 'absl'
#23 171.7 [ 61%] Built target absl
#23 171.7 make: *** [all] Error 2
#23 171.7 Makefile:90: recipe for target 'all' failed
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c cmake .. && make -j && mv bin/bpfki /usr/local/bin/ && mv examples/fail* /usr/local/bin/]: exit code: 2
make: *** [images/chaos-kernel/.dockerbuilt] Error 1
```

ps. I confirm that `bpfki` code is latest.

**Comment by STRRL** [comment]
> > @STRRL I have upgraded the chaos-mesh/bpfki, it should build successfully now.
> 
> @YangKeao Hi, I tried to build chaos-kernel image on arm64 machine, and I got some error message:
> 
> ```
> #23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_bad_optional_access.pc
> #23 171.7 -- Installing: /bpfki/build/absl/lib/libabsl_bad_optional_access.a
> #23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_bad_variant_access.pc
> #23 171.7 -- Installing: /bpfki/build/absl/lib/libabsl_bad_variant_access.a
> #23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_variant.pc
> #23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_compare.pc
> #23 171.7 -- Installing: /bpfki/build/absl/lib/pkgconfig/absl_utility.pc
> #23 171.7 [ 61%] Completed 'absl'
> #23 171.7 [ 61%] Built target absl
> #23 171.7 make: *** [all] Error 2
> #23 171.7 Makefile:90: recipe for target 'all' failed
> ------
> error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c cmake .. && make -j && mv bin/bpfki /usr/local/bin/ && mv examples/fail* /usr/local/bin/]: exit code: 2
> make: *** [images/chaos-kernel/.dockerbuilt] Error 1
> ```
> 
> ps. I confirm that `bpfki` code is latest.

After upgrading absl, it works on my arm64 with qemu on amd64 machine. FYI @YangKeao @iguoyr 

But it fails in another place, really weird because it seems to be `kill -9` by someone(exit code 137), but no logs printed from `dockerd.service`

**Comment by STRRL** [comment]
> But it fails in another place, really weird because it seems to be `kill -9` by someone(exit code 137), but no error logs printed from `dockerd.service`. I am still profiling that.

I found the reason from, I enabled the `systemd-oomd`, so it killed by `systemd-oomd` instead of oom killer;

**Comment by STRRL** [comment]
> > But it fails in another place, really weird because it seems to be `kill -9` by someone(exit code 137), but no error logs printed from `dockerd.service`. I am still profiling that.
> 
> I found the reason from, I enabled the `systemd-oomd`, so it killed by `systemd-oomd` instead of oom killer;

It gets oom-killed when building grpc. :(

**Comment by STRRL** [comment]
> > > But it fails in another place, really weird because it seems to be `kill -9` by someone(exit code 137), but no error logs printed from `dockerd.service`. I am still profiling that.
> > 
> > 
> > I found the reason from, I enabled the `systemd-oomd`, so it killed by `systemd-oomd` instead of oom killer;
> 
> It gets oom-killed when building grpc. :(

It works after setup `make -j 16` :)

**Comment by STRRL** [comment]
I think this PR is ready for review, PTAL

/cc @YangKeao  @Hexilee @iguoyr @cwen0

**Review by iguoyr — APPROVED** [review]
LGTM, and I have built `chaos-kernel` image on m1 mbp successfully!

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
