### PR TITLE
Promote "Siyu Chen" to committer

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

In accordance with our Governance, I am pleased to apply to promote [Siyu Chen](https://github.com/iguoyr) as a new committer for Chaos Mesh. I would like to hereby thank her for her great contributions to the project and look forward to seeing more of her growth and engagements. 

## What does becoming a Chaos Mesh Committer mean to you? 

I am an open-source lover and I am very happy to be involved in Chaos Mesh open-source community. Chaos Mesh is an excellent chaos engineering product. During the time I have been involved in the Chaos Mesh community, I have seen Chaos Mesh successfully promote to the incubation phase in CNCF, which makes me more deeply realize the charm and power of open-source. After becoming a Chaos Mesh Committer, I hope to continue to play my part in helping Chaos Mesh eventually enter the graduation phase in CNCF.

## Contribution Highlights 

- Feature: physical machine auth. Based on the Kubernetes RBAC mechanism, it provides an access control solution for physical machine experiments. The default HTTP connection between the chaos-controller-manager and chaosd is upgraded to an mTLS connection, which improves the security of communication between services. In order to allow users to use it out of the box, a command is added to chaosctl to generate TLS certificates for chaos-controller-manager and chaosd with one click.  
- Feature: add leader election on chaos-controller-manager, which improves the high availability of chaos-controller-manager 
- Refactor: the implementation of selector, decouple the original logic to enhance readability and maintainability
- Presentation: Chaos Mesh Office Hours session at KubeCon NA 2021, and 'Disrupt your systems with Chaos Mesh' at KCD Guatemala 2021

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM 🎉

**Review by Gallardot — APPROVED** [review]
LGTM 🎉

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM！

**Review by g1eny0ung — APPROVED** [review]
LGTM 🍻

**Pull request merged**
