### PR TITLE
Ignore the .go file startwith zz_generated 

### PR DESCRIPTION
**Pull request by ReigenDing**
### What problem does this PR solve?
Ignore the .go file startwith zz_generated

Problem Summary:

### What is changed and how it works?
check the prefix of file name and return nil

What's Changed:
cmd/chaos-builder/main.go  line 65-67

### Related changes
#2190

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by STRRL — COMMENTED** [review]
LGTM!

Thanks for your contribution!

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
