### PR TITLE
proposal: add watch pod change and make networkchaos request proposal.

### PR DESCRIPTION
**Pull request by Colstuwjx**
### What problem does this PR solve?
Related to #799 .

### What is changed and how does it work?
We'll watch pod changes and send request to networkChaos.

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [x] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Colstuwjx** [comment]
From now, I'd like to fill out the details in my mind.

Proposal:

1. NetworkChaos ( it may also applied to common chaos objects ) need to add `ExperimentTargets` inside its `Status` part, records the current applied targets;

2. NetworkChaos Reconciler add pod watch function, once received a pod change event, it collects all NetworkChaos objects in the same namespace, and filter out the associate NetworkChaos via the target selector. Then, it send all such relative NetworkChaos requests to NetworkChaos Reconciler;

3. For CommonReconciler and SchedulerReconciler, add another if-statement for ensuring whether the NetworkChaos experiment targets has been changed, if it did changed, do Recover() on these targets, and do the following steps as usual.

More details is shown in a graph below:

image

It will be appreciated if you could take some suggestions on this proposal!

**Comment by Colstuwjx** [comment]
I've been updated the code according the proposal design, and I've tried testing it on my kind cluster:

```
kind create cluster
make image
...
curl -sSL https://mirrors.chaos-mesh.org/v0.9.1/web-show/deploy.sh | sh
kubectl apply -f network-delay.yaml
```

and I ran into the following issue:

```
2020-09-17T09:18:41.000Z	INFO	controllers.NetworkChaos	Reconciling networkchaos	{"reconciler": "networkchaos"}
2020-09-17T09:18:41.000Z	INFO	controllers.NetworkChaos	Reconciling a two phase chaos	{"reconciler": "networkchaos", "action": "netem", "name": "web-show-network-delay", "namespace": "default"}
2020-09-17T09:18:41.000Z	INFO	controllers.NetworkChaos	Renewing self	{"reconciler": "networkchaos", "action": "netem"}
2020-09-17T09:18:41.000Z	INFO	controllers.NetworkChaos	running modification on pod	{"reconciler": "networkchaos", "action": "netem", "key": {"namespace": "default", "name": "web-show-7b477b5c6-627zm"}, "modification": {"Steps":[{"Source":"default/web-show-network-delay"}]}}
2020-09-17T09:18:41.000Z	ERROR	controllers.NetworkChaos	error while finding pod	{"reconciler": "networkchaos", "action": "netem", "key": {"namespace": "default", "name": "web-show-7b477b5c6-627zm"}, "error": "Pod \"web-show-7b477b5c6-627zm\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:86
k8s.io/client-go/util/retry.OnError.func1
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
k8s.io/client-go/util/retry.OnError
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:73
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-17T09:18:41.005Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "284cbdc9-6d49-4c53-bfdb-8a5407e70364", "kind": "chaos-mesh.org/v1alpha1, Kind=PodNetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"podnetworkchaos"}}
2020-09-17T09:18:41.005Z	INFO	rawpodnetwork-resource	default	{"name": "web-show-7b477b5c6-627zm"}
2020-09-17T09:18:41.006Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-podnetworkchaos", "UID": "284cbdc9-6d49-4c53-bfdb-8a5407e70364", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-17T09:18:41.008Z	ERROR	controllers.NetworkChaos	error while creating podnetworkchaos	{"reconciler": "networkchaos", "action": "netem", "error": "PodNetworkChaos.chaos-mesh.org \"web-show-7b477b5c6-627zm\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:102
k8s.io/client-go/util/retry.OnError.func1
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
k8s.io/client-go/util/retry.OnError
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:73
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-17T09:18:41.008Z	ERROR	controllers.NetworkChaos	error while updating	{"reconciler": "networkchaos", "action": "netem", "error": "PodNetworkChaos.chaos-mesh.org \"web-show-7b477b5c6-627zm\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:116
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-17T09:18:41.008Z	ERROR	controllers.NetworkChaos	fail to commit	{"reconciler": "networkchaos", "action": "netem", "error": "PodNetworkChaos.chaos-mesh.org \"web-show-7b477b5c6-627zm\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty, metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/trafficcontrol.(*Reconciler).cleanFinalizersAndRecover
	/src/controllers/networkchaos/trafficcontrol/types.go:221
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/trafficcontrol.(*Reconciler).Recover
	/src/controllers/networkchaos/trafficcontrol/types.go:183
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:88
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:52
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:164
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-09-17T09:18:41.009Z	INFO	controllers.NetworkChaos	After recovering	{"reconciler": "networkchaos", "action": "netem", "finalizers": []}
2020-09-17T09:18:41.009Z	INFO	controllers.NetworkChaos	Recovering	{"reconciler": "networkchaos", "action": "netem"}
2020-09-17T09:18:41.009Z	INFO	controllers.NetworkChaos	After recovering	{"reconciler": "networkchaos", "action": "netem", "finalizers": []}
2020-09-17T09:18:41.009Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"NetworkChaos","namespace":"default","name":"web-show-network-delay","uid":"63952662-6b53-4a95-83f1-4449968bf486","apiVersion":"chaos-mesh.org/v1alpha1","resourceVersion":"976"}, "reason": "ChaosRecovered", "message": ""}
2020-09-17T09:18:41.010Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"NetworkChaos","namespace":"default","name":"web-show-network-delay","uid":"63952662-6b53-4a95-83f1-4449968bf486","apiVersion":"chaos-mesh.org/v1alpha1","resourceVersion":"976"}, "reason": "ChaosRecovered", "message": ""}
2020-09-17T09:18:41.019Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "3c85fcdd-4a9a-4013-8cce-aadf5aa266e6", "kind": "chaos-mesh.org/v1alpha1, Kind=NetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"networkchaos"}}
2020-09-17T09:18:41.020Z	INFO	networkchaos-resource	default	{"name": "web-show-network-delay"}
2020-09-17T09:18:41.020Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/mutate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "3c85fcdd-4a9a-4013-8cce-aadf5aa266e6", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-17T09:18:41.024Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "12768ff6-691a-4da2-b97a-f01927e08b1d", "kind": "chaos-mesh.org/v1alpha1, Kind=NetworkChaos", "resource": {"group":"chaos-mesh.org","version":"v1alpha1","resource":"networkchaos"}}
2020-09-17T09:18:41.024Z	INFO	networkchaos-resource	validate update	{"name": "web-show-network-delay"}
2020-09-17T09:18:41.025Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-chaos-mesh-org-v1alpha1-networkchaos", "UID": "12768ff6-691a-4da2-b97a-f01927e08b1d", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
2020-09-17T09:18:41.028Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "networkchaos", "request": "default/web-show-network-delay"}
```

**Comment by Colstuwjx** [comment]
The error may happens due to that the original pod has been deleted, and we did error check but continue to next steps, see [this line](https://github.com/chaos-mesh/chaos-mesh/blob/d94435fdf5e6e4ffe623d43c81eaecb907c668ad/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go#L86), shall we re-check the commit logic?

**Comment by cwen0** [comment]
> The error may happens due to that the original pod has been deleted, and we did error check but continue to next steps, see [this line](https://github.com/chaos-mesh/chaos-mesh/blob/d94435fdf5e6e4ffe623d43c81eaecb907c668ad/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go#L86), shall we re-check the commit logic?

I think this is a bug here. If the pod isn't exist, we don't need to create chaos on it. But we need to record the err message to the Chaos status field.  @YangKeao @fewdan PTAL

**Comment by fewdan** [comment]
> > The error may happens due to that the original pod has been deleted, and we did error check but continue to next steps, see [this line](https://github.com/chaos-mesh/chaos-mesh/blob/d94435fdf5e6e4ffe623d43c81eaecb907c668ad/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go#L86), shall we re-check the commit logic?
> 
> I think this is a bug here. If the pod isn't exist, we don't need to create chaos on it. But we need to record the err message to the Chaos status field. @YangKeao @fewdan PTAL

@cwen0 Yes, I think there should be a bug here, and we should need to fix it.

**Comment by Colstuwjx** [comment]
> @Colstuwjx If I want to reproduce this error, should I create a chaos first and then delete the target pod?
Little tricky here, from now, if we created a chaos, and delete the target pod, it wouldn't do any actions since it didn't watch pod changes, therefore, I proposed this PR. And after I implement the code, I found this issue...

**Comment by fewdan** [comment]
> Little tricky here, from now, if we created a chaos, and delete the target pod, it wouldn't do any actions since it didn't watch pod changes, therefore, I proposed this PR. And after I implement the code, I found this issue...

Okay, got it.

**Comment by Colstuwjx** [comment]
Close for #962 .

**Pull request closed without merging**
