### PR TITLE
format and clean code

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
### What problem does this PR solve?

format and clean code

### What is changed and how does it work?

use [staticcheck](https://staticcheck.io/docs/) to check code, find some problems, and fix them.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by cwen0 — DISMISSED** [review]
LGTM

**Comment by STRRL** [comment]
Should we add `golangci-lint` github action for this repo?  It could invoke the rule called staticcheck and many other rules.

**Comment by WangXiangUSTC** [comment]
> Should we add `golangci-lint` github action for this repo? It could invoke the rule called staticcheck and many other rules.

I agree with you, and we still need to fix many problems, for example, there are so many exported functions need to add comment or be unexported.

**Review by STRRL — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]

**Pull request merged**
