### PR TITLE
fix error handling in chaos-dashboard to avoid panic

### PR DESCRIPTION
**Pull request by cwen0**
### What problem does this PR solve?
 

Accessing certain API interfaces may cause chaos-dashboard panic

### What is changed and how does it work?

Exit the function directly when an error is encountered 

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by fewdan — DISMISSED** [review]
LGTM

**Comment by g1eny0ung** [comment]
@cwen0 The check of DCO is failed.

**Comment by cwen0** [comment]
> @cwen0 The check of DCO is failed.

Fixed

**Review by g1eny0ung — APPROVED** [review]

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
