### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by xlgao-zju**
Signed-off-by: xianglingao <xianglingao@tencent.com>

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
oops, as the comments of CRD changed, the yaml manifest also needs updates.

Please execute `make check` on your local machine, then commit the changes.  It would re-generate the manifests.

**Review by STRRL — CHANGES_REQUESTED** [review]
oops, as the comments of CRD changed, the yaml manifest also needs updates.

Please execute make check on your local machine, then commit the changes. It would re-generate the manifests.

**Comment by xlgao-zju** [comment]
@STRRL updated, look like we fix so many typos, lol

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
PTAL

/cc @cwen0 @WangXiangUSTC

**Review by cwen0 — APPROVED** [review]

**Pull request merged**
