### PR TITLE
feat!: support PhysicalMachine in UI

### LINKED ISSUE #3221: ui(workflow): remaining new features in next `New Workflow`
After #3185, there has still some unfinished things about the next generation `New Workflow` in UI:

- [x] #3253
- [x] #3623
- [x] #3420
- [x] #3224
- [x] #3364
- [x] #3365

I will address these and some other potential things in the future.

### LINKED ISSUE #3623: Specific `address` info in `selector` when creating `PhysicalMachineChaos`

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Close #3623
Close #3221

### What's changed and how it works?

This PR adds support for `PhysicalMachine` in UI. Here is an example of its definition:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachine
metadata:
  name: physical-machine-example
  namespace: default
spec:
  address: http://192.168.199.170:31767
```

After applying, you should enable a setting in the UI's settings to activate the **Get `PhysicalMachine`s** through Scope:

image

And then, the following section will keep the Scope fields instead of the previous address fields:

image

The rest is the same as creating the Kubernetes experiment. ⛑️

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [x] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @g1eny0ung, is this PR ready for review ?

**Comment by g1eny0ung** [comment]
> Hi @g1eny0ung, is this PR ready for review ?

@STRRL Theoretically it is. But I still have some tests not fixed. 😢 I will solve them today.

**Comment by g1eny0ung** [comment]
@STRRL Ready to go! 🚀

**Review by STRRL — APPROVED** [review]
Awesome! LGTM!

**Comment by cwen0** [comment]
@g1eny0ung Can you add new docs to guide users on how to use the new UI?

**Comment by g1eny0ung** [comment]
OK.

**Pull request merged**
