### PR TITLE
more better logs in e2e tests

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

use `ginkgo.By` instead of `framework.log`, the former could make better view in e2e tests with parallel nodes

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by fewdan — APPROVED** [review]
LGTM

**Review by AsterNighT — APPROVED** [review]
LGTM, it would be better if there is some comparison (like log excerpts or snapshots)

**Pull request merged**
