### PR TITLE
Fix: client.Get gets empty GVK(Group/APIVersion/Kind)

### PR DESCRIPTION
**Pull request by cwen0**
### What problem does this PR solve?

image

`Client.Get` gets empty GVK(Group/APIVersion/Kind). 

### What is changed and how does it work?
 
Use `schema` and object to get GVK

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

image

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]

**Review by YangKeao — CHANGES_REQUESTED** [review]
upgrade `controller-runtime` should solve the problem:

https://github.com/kubernetes-sigs/controller-runtime/pull/203

**Review by YangKeao — COMMENTED** [review]
Sorry. I'm not sure whether it's fixed in `controller-runtime`. As this PR got merged in 2018, but the `controller-runtime` v0.4.0 releases at 2019...

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
