### PR TITLE
chore: always build swagger server

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Problem Summary:

As mentioned in https://github.com/chaos-mesh/chaos-mesh/pull/2250#pullrequestreview-742375862 and https://github.com/chaos-mesh/chaos-mesh/pull/2274#issuecomment-914025017, the artifacts of swagger will be generated automatically in every build, and the definition is included in the repo.

So I think we could always build the swagger server `/api/swagger/index.html` for chaos dashboard.

### What is changed and how it works?

What's Changed:

- remove `empty_handler.go` in sawaggerserver
- remove env `SWAGGER` in makefile
- remove buildtag `sawgger_server`, always build swaggerserver

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No.
* Need to update Chaos Dashboard component, related issue: No.
* Need to cheery-pick to the release branch: No.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL 

/cc @g1eny0ung 
/cc @YangKeao 
/cc @fewdan

**Review by fewdan — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM! This will save a lot of work.

**Pull request merged**
