### PR TITLE
bump go to 1.19.3

### PR DESCRIPTION
**Pull request by hypnoce**
Signed-off-by: JACQUES Francois <Francois.JACQUES@murex.com>

### What problem does this PR solve?

Update to latest go 1.19.3 for dev, test and release.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.4
  - [ ] release-2.3

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
please execute `go mod tidy` and `make check` and commit the changes :")

**Comment by STRRL** [comment]
oops, please also setup go as 1.19 in https://github.com/chaos-mesh/chaos-mesh/blob/master/.github/workflows/codecov_unittest.yaml

Rest LGTM!

**Comment by hypnoce** [comment]
I cannot update any go version in https://github.com/chaos-mesh/chaos-mesh/blob/master/.github/workflows/codecov_unittest.yaml 
I think this PR should have labels `rebuild-build-env-image` and `rebuild-dev-env-image`. WDYT ?

**Comment by STRRL** [comment]
> I cannot update any go version in https://github.com/chaos-mesh/chaos-mesh/blob/master/.github/workflows/codecov_unittest.yaml I think this PR should have labels `rebuild-build-env-image` and `rebuild-dev-env-image`. WDYT ?

You're right. Thanks!

But the bot does not works well, I manually append these labels.

**Comment by STRRL** [comment]
I just realized that GitHub Action requires a new commit to let new labels get effected, I would try to make a new commit but without any changes and forcely push to re-trigger the CI.

**Comment by hypnoce** [comment]
emqx.com seems unreachable  😯

**Comment by hypnoce** [comment]
I ran `make test` locally and it passed. Not sure what happened on the CI.

**Comment by STRRL** [comment]
> I ran `make test` locally and it passed. Not sure what happened on the CI. image

I think CI failed because of the unstable networking, I have triggered the retry, and it passed now. 🥳

**Comment by STRRL** [comment]
/merge

Thanks for your contribution!! @hypnoce

**Pull request merged**
