### PR TITLE
re-trigger ci 'must_update_changelog' when labels change

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: xixi <i@hexilee.me>

### What problem does this PR solve?

The result of CI `must_update_changelog` depends on the label "no-need-update-changelog", but it won't re-run when labels change. This PR resolved a part of #3301.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.2
  - [x] release-2.1

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — COMMENTED** [review]
LGTM!

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
/cc @Andrewmatilde @iguoyr @YangKeao @cwen0 

PTAL :heart:

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
It seems the GHA Workflow "Must Update CHANGELOG" are triggered multiple times:

- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2385398729
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2385399843
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2385399872
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2394758206
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2394761789
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2394761807
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2394763295
- https://github.com/chaos-mesh/chaos-mesh/actions/runs/2395416984


Maybe it is not expected. cc @Hexilee

**Comment by STRRL** [comment]
/hold cancel

> It seems the GHA Workflow "Must Update CHANGELOG" are triggered multiple times:

Do not mind. I think this situation is caused by github itself.

**Pull request merged**
