### PR TITLE
intergration tests for workflow

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?
Integration tests of workflow controllers.
As the assertion of e2e is hard to write, this PR is a replacement of https://github.com/chaos-mesh/chaos-mesh/pull/1902.

### What is changed and how it works?

it will use `envtest` and only bootstrap workflow controllers for testing.

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by STRRL** [comment]
This PR is ready to review, PTAL.
/cc @YangKeao 
/cc @Hexilee 
/cc @AsterNighT

**Comment by AsterNighT** [comment]
A problem is that such tests could not be run parallelly. I tried to improve it in #1910 but it did not work very well. Have you got any ideas?

**Comment by STRRL** [comment]
> A problem is that such tests could not be run parallelly. I tried to improve it in #1910 but it did not work very well. Have you got any ideas?

Not yet. I am not so familiar with `envtest` and `ginkgo`.

I set up `envtest` in `ginkgo.BeforeSuite` and cleanup that env in `gingkgo.AfterSuite`. I think the problem is the env set by `envtest` is not shared by parallel instance.

**Comment by STRRL** [comment]
> > A problem is that such tests could not be run parallelly. I tried to improve it in #1910 but it did not work very well. Have you got any ideas?
> 
> Not yet. I am not so familiar with `envtest` and `ginkgo`.
> 
> I set up `envtest` in `ginkgo.BeforeSuite` and cleanup that env in `gingkgo.AfterSuite`. I think the problem is the env set by `envtest` is not shared by parallel instance.

Maybe I could initialize in `BeforeEach` and using a singleton pattern with `envtest`

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
