### PR TITLE
Making awschaos read and use aws_session_token secret

### PR DESCRIPTION
**Pull request by punarjitsingh-okta**
### What problem does this PR solve?

Chaos mesh doesn't support the use of [temporary AWS credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) for awschaos. The simple reason being its not reading the valid session `aws_session_token` set in the kubernetes secrets.

This PR solves this bug reported by the same author: https://github.com/chaos-mesh/chaos-mesh/issues/4065

### What's changed and how it works?

All existing awschoas experiments will now read the `aws_session_token` set in the kubernetes secrets. This allows the use of [temporary AWS credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) i.e. users will be able to use awschaos with AWS switch to an IAM role feature.

### Related changes

- [x] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs) - Separate PR https://github.com/chaos-mesh/website/pull/385 raised
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by cwen0** [comment]
@punarjitsingh-okta Thanks for your contribution!

**Review by STRRL — APPROVED** [review]

**Review by cwen0 — APPROVED** [review]
/lgtm

**Pull request merged**
