### PR TITLE
fix: optimize darwin static check

### LINKED ISSUE #3499: macos can not build chaos-mesh daemon
## Bug Report

**What version of Chaos Mesh are you using?**
release-2.3

**What did you do?**

**What did you expect to see?**
chaos-mesh daemon run
**What did you see instead?**

package github.com/chaos-mesh/chaos-mesh/cmd/chaos-daemon
	imports github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon
	imports github.com/chaos-mesh/chaos-mesh/pkg/time
	imports github.com/chaos-mesh/chaos-mesh/pkg/ptrace: build constraints exclude all Go files in /Users/zhouhoufa/Code/src/github.com/chaos-mesh/chaos-mesh/pkg/ptrace
截屏2022-07-28 10 47 23

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Close #3499.

This is a very old problem for people like me who develop on macOS. Since I use the Go extension for VSCode, the gopls automatically analyzes the code, so my console keeps coming up with platform-related errors.

### What's changed and how it works?

Use `GOOS` and `GOARCH` suffixes to avoid building on darwin.

### Related changes

- [ ] This change also requires further updates to `chaos-mesh/website` (e.g. docs)
- [ ] This change also requires further updates to `UI interface`
- Need to **cheery-pick to release branches**
  - [x] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by FingerLeader — APPROVED** [review]
LGTM

**Comment by FingerLeader** [comment]
I think pkg/ptrace can also be modified like this.

**Comment by g1eny0ung** [comment]
> I think pkg/ptrace can also be modified like this.

It makes sense to me. But after I looked at the code, only the `time` package uses it at the moment, and it doesn't affect anywhere else. We can open a separate PR to update it (the `ptrace` package is relatively more complicated).

**Comment by FingerLeader** [comment]
> > I think pkg/ptrace can also be modified like this.
> 
> It makes sense to me. But after I looked at the code, only the `time` package uses it at the moment, and it doesn't affect anywhere else. We can open a separate PR to update it (the `ptrace` package is relatively more complicated).

OK, I'll handle it later

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
