### PR TITLE
Move @siddontang, @zhouqiang-cl, and @Yisaer to emeritus maintainers

### PR DESCRIPTION
**Pull request by cwen0**
As per the [governance doc](https://github.com/chaos-mesh/chaos-mesh/blob/master/GOVERNANCE.md#maintainer), I create this PR on behalf of Chaos Mesh maintainers to move @siddontang, @zhouqiang-cl, and @Yisaer to emeritus maintainers as they haven't been able to stay active in the project for a while due to shift of focus. And they all agree to become emeritus maintainers.  

Thanks for their awesome work on Chaos Mesh! We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly and sustained project. 

/cc @chaos-mesh/maintainers

### CODE REVIEW

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by dcalvin** [comment]
LGTM! It's a great privilege to be working with all of you on Chaos Mesh. Truly appreciate your work as the initial building blocks for the community.

**Review by dcalvin — APPROVED** [review]

**Comment by yeya24** [comment]
@cwen0 It is hard to say but please add me as well. I am busy with other work recently and cannot contribute to Chaos Mesh now.

**Review by yeya24 — APPROVED** [review]
LGTM

**Pull request merged**
