### PR TITLE
chore: create workflow tasks recursively

### LINKED ISSUE #2029: Dashboard: describe the "deadline' field format
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
 

Add a description for the "deadline" field format. 
 
image

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What is changed and how it works?

Close #2029

What's Changed:

As the title. With this PR, you can create arbitrary complexity workflows.

Bug fixes:

- Correct theme's secondary color
- `ByYAML` can't listen after content changed
- Supplement schedule spec into `ObjectConfiguration`
- Delete predefined after confirm

And this PR needs to wait for #2006 to be merged because this PR relies on its bug fixes.

### Related changes

* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @g1eny0ung , I find unexpected behavior:

image

I can not finish the creation of workflow, when I click that "SUBMIT" button, nothing happens: the state of the form does not change, I can not submit this form.

PTAL @g1eny0ung

**Comment by g1eny0ung** [comment]
> Hi @g1eny0ung , I find unexpected behavior:
> 
> image
> 
> I can not finish the creation of workflow, when I click that "SUBMIT" button, nothing happens: the state of the form does not change, I can not submit this form.
> 
> PTAL @g1eny0ung

I found that I forgot to bind the `onClick` event to the submit button...now it's working.

**Comment by cwen0** [comment]
@g1eny0ung Hi, the YAML file generated by the dashboard is invalid: 

image

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
