### PR TITLE
Dashboard rwo pvc restart

### LINKED ISSUE #3876: Dashboard not rolling-restarting
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4-gke.2100", GitCommit:"0e55ef943b612cf213ba4abfd1e6e915b9832969", GitTreeState:"clean", BuildDate:"2022-12-07T09:33:35Z", GoVersion:"go1.19.3 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
v2.5.0
```

**What did you do? / Minimal Reproducible Example**

I deployed the Chaos Mesh Helm chart with a PersistentVolumeClaim (RWO) for the dashboard. I tried to do a `kubectl rollout restart deployment chaos-dashboard` to restart the dashboard.

**What did you expect to see?**
I expected to see a restart of the deployment.

**What did you see instead?**
The rollout is stuck because the PersistentVolumeClaim can only be bound to one Pod at the same time (RWO).

```bash
chaos-dashboard-5477447df-2kfcm             1/1     Running    0          11m   172.22.193.254   gke-XXXXXXXXXXXXXXXXXXXxx-e33a33db-vfx7   <none>           <none>
chaos-dashboard-568594946f-kvq6t            0/1     Init:0/1   0          13m   <none>           gke-XXXXXXXXXXXXXXXXXXXxx-e33a33db-9lhx   <none>           <none>

```

kubectl describe pod <the pod that is stuck>:

```bash
  Warning  FailedAttachVolume  14m                  attachdetach-controller  Multi-Attach error for volume "pvc-e0b0e23c-1a6b-4762-b2b8-70d65a4643da" Volume is already used by pod(s) chaos-dashboard-5477447df-rpt49
  Warning  FailedMount         7m56s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[XXXXXXXXXXXXXXXXXXXXXXXXXXXX]: timed out waiting for the condition

```

**Output of chaosctl**

Not needed I guess.

**Hint from me: Since the dashboard is a single Pod and the PVC is RWO, the `restartPolicy` of the Deployment might need to be changed so the Pod is replaced by Kubernetes instead of a rolling restart.**

### PR DESCRIPTION
**Pull request by torbendury**
### What problem does this PR solve?

Close #3876

### What's changed and how it works?

I have changed the dashboards `updateStrategy`. The PersistentVolumeClaim for the dashboard is created with the accessMode `ReadWriteOnce`, which does not allow the dashboard to do a rolling restart because the blue version of the dashboard won't be shutdown until the green version is up and running.

This lead to problems when doing a `kubectl rollout-restart deployment chaos-dashboard` because the new dashboard Pod could not mount the PVC.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [x] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

steps:

- Install the ChaosMesh + dashboard using a `helm install` command
  - configure the dashboard to be enabled and use a PersistentVolumeClaim of arbitrary size
- Change the update strategy as mentioned in this PR
- Watch the dashboard rollout-restart instead of being stuck

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by torbendury** [comment]
Apparently it's not _that_ easy to sign-off commits using GitHub Desktop, anyway I was able to force push over my mistake. Open for comments/review!

**Comment by g1eny0ung** [comment]
> Apparently it's not _that_ easy to sign-off commits using GitHub Desktop, anyway I was able to force push over my mistake. Open for comments/review!

Ah, I'm also facing this problem before. The GitHub desktop lacks sign-off commits support. :(

**Comment by torbendury** [comment]
Are those failing checks related to my PR? I took a quick look but they don't really seem to correlate imho

**Review by g1eny0ung — APPROVED** [review]
I'm ok with this solution of setting the strategy to `type: Recreate` because real-time availability of the dashboard is not so critical.

We can also make a separate option for `ReadWriteOnce` PV or PVC, like:

```yaml
strategy:
  {{- if eq .Values.dashboard.persistentVolume.accessModes "ReadWriteOnce" }}
  type: Recreate
  {{- else }}
  # ...
```

I think both are fine. What do you think? @STRRL

**Comment by g1eny0ung** [comment]
> Are those failing checks related to my PR? I took a quick look but they don't really seem to correlate IMHO

@torbendury It can be said to be irrelevant. These errors are not about the charts themselves, they are just used to prevent some omissions (because of the need to synchronize the chart's changes to `install.sh`).

Run `make install.sh` in your local and commit again can pass the checks. 😃

**Comment by torbendury** [comment]
I also thought of making it depending on the accessMode of the PVC itself, but it is (at least at the moment!) hardcoded [here](https://github.com/chaos-mesh/chaos-mesh/blob/d3c8a29344540c41472253395b4548dd4a314599/helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml#L35) by the Helm Chart itself, if I didn't overlook anything

**Comment by g1eny0ung** [comment]
> I also thought of making it depending on the accessMode of the PVC itself, but it is (at least at the moment!) hardcoded [here](https://github.com/chaos-mesh/chaos-mesh/blob/d3c8a29344540c41472253395b4548dd4a314599/helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml#L35) by the Helm Chart itself, if I didn't overlook anything

Good catch! Then I think about the `accessMode` we can consider in a separate PR.

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
