### PR TITLE
fix: replace core.SelectorInfo with v1alpha1.PodSelectorSpec

### LINKED ISSUE #2320: Label selectors on dashboard don't work.
## Bug Report

**What version of Kubernetes are you using?**
v1.21

**What version of Chaos Mesh are you using?**
 Image:         pingcap/chaos-dashboard:latest
    Image ID:      docker-pullable://pingcap/chaos-dashboard@sha256:4a15e5b31e921b5c2f13fa123b9c138db3cf0074057ecc2fd1fca421266c0a88

**What did you do?**
I created an expriment on dashboard.

**What did you expect to see?**
After selecting the label selectors, dashboard filters right pods.
**What did you see instead?**
Label selectors don't work.
image

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: FingerLeader <wanxfinger@gmail.com>

### What problem does this PR solve?

Issue Number: close #2320 

Problem Summary:

### What is changed and how it works?

What's Changed:

Use `v1alpha1.PodSelectorSpec` rather than `core.SelectorInfo` to resolve the problem that label selector on dashboard doesn't work.

Tests

- [x] Unit test
- [x] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @FingerLeader, you could execute `make check` for re-generating the swagger files.

**Comment by g1eny0ung** [comment]
> It seems to be something wrong with creating stress chaos on physical machine. Do you have any ideas?

Now all tests have passed again. 🤔 I will merge this PR first due to this error is occasional.

**Pull request merged**
