### PR TITLE
add: new blog link to README

### PR DESCRIPTION
**Pull request by milasuperstar**
Signed-off-by: Mila Wu <wuzaixuan@pingcap.com>

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```
@dcalvin @zhouqiang-cl

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by milasuperstar** [comment]
@zhouqiang-cl @cwen0 
Link is moved to under community blogs, PTAL

**Review by cwen0 — APPROVED** [review]

**Review by WangXiangUSTC — DISMISSED** [review]

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
