### PR TITLE
Add dashboard API for `StatusCheck`

### LINKED ISSUE #2968: Feature: StatusCheck in Workflow, Add Dashboard API for StatusCheck
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by iguoyr**
Signed-off-by: SiyuChen <ryougi201@gmail.com>

### What problem does this PR solve?

Close #2968 

### What's changed and how it works?

Add dashboard api for status check

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by iguoyr** [comment]
@STRRL @g1eny0ung @chaos-mesh/committers 
PTAL

**Comment by iguoyr** [comment]
/cc @chaos-mesh/committers @chaos-mesh/maintainers 
PTAL

**Review by cwen0 — APPROVED** [review]
LGTM! @iguoyr Do you have a plan to store these templates in Chaos Dashboard as archive data when these were deleted?

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by iguoyr** [comment]
> LGTM! @iguoyr Do you have a plan to store these templates in Chaos Dashboard as archive data when these were deleted?

No such plan for now, I think archiving templates is useless, because templates are static resources. 🤔

**Pull request merged**
