### PR TITLE
Refine logging in pkg/portforward, using logger in portForwarder 

### PR DESCRIPTION
**Pull request by DaivikDave**
### What problem does this PR solve?
#2884 

### What's changed and how it works?
Portforward now uses logger instead of klog

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by DaivikDave** [comment]
Hey @STRRL This is the first time logr is added to e2e-test to i had to run make tidy without --exit-code command. 
What would be the right way to add new dependencies to e2e-test ? as i can't find any documentation for it.

**Comment by STRRL** [comment]
> Hey @STRRL This is the first time logr is added to e2e-test to i had to run make tidy without --exit-code command. What would be the right way to add new dependencies to e2e-test ? as i can't find any documentation for it.

Hi @DaivikDave , sorry for the late response. It seems everything already works well, you have done it.

**Comment by STRRL** [comment]
> Hey @STRRL This is the first time logr is added to e2e-test to i had to run make tidy without --exit-code command. What would be the right way to add new dependencies to e2e-test ? as i can't find any documentation for it.

Hi @DaivikDave , sorry for the late response. It seems everything already works well, you have done it.

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
