### PR TITLE
chore: rename durtaion in workflowspec.template to deadline

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

rename the confusing name from `Duration` to `Deadline`

### What is changed and how it works?

close https://github.com/chaos-mesh/chaos-mesh/issues/1951

What's Changed:

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No.
* Need to update Chaos Dashboard component, related issue:  https://github.com/chaos-mesh/chaos-mesh/issues/1951
* Need to cheery-pick to the release branch: No.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by STRRL** [comment]
It needs updating on the Chaos Mesh Dashboard. PTAL @g1eny0ung 
/cc @g1eny0ung

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by fewdan** [comment]
It seems that you should fix the Conflicting files.

**Comment by STRRL** [comment]
> It seems that you should fix the Conflicting files.

Conflicts resolved! PTAL! ：D

**Review by g1eny0ung — APPROVED** [review]

**Pull request merged**
