### PR TITLE
Remove yeya24 as current maintainer

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <benye@amazon.com>

I have been inactive on the project for 2 years since I left PingCAP. I have other things to focus now and it is hard for me to focus back to the project.
Since we have more and more active maintainers now I feel it is better to move myself to emeritus maintainer state.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.4
  - [ ] release-2.3

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by yeya24** [comment]
Umm I guess this change doesn't require a changelog entry?

**Comment by STRRL** [comment]
> Umm I guess this change doesn't require a changelog entry?

Aha yes, I would append the label.

**Review by STRRL — APPROVED** [review]
LGTM and best wishes. ❤️

**Pull request merged**
