### PR TITLE
fixes opt.semgrep.err-nil-check

### PR DESCRIPTION
**Pull request by someshkoli**
Signed-off-by: someshkoli <kolisomesh27@gmail.com>

### What is changed and how does it work?
Removes unwanted err nil checks 
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM
/auto-cc

**Review by AsterNighT — APPROVED** [review]
LGTM

**Review by AsterNighT — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
The CI cluster has such little resources!!!!! My eight years old laptop will work better than it :angry:.

I will merge this PR and test manually.

Thanks again for your contribution and sorry for the bad experience on CI.

**Comment by someshkoli** [comment]
> The CI cluster has such little resources!!!!! My eight years old laptop will work better than it .
> 
> I will merge this PR and test manually.
> 
> Thanks again for your contribution and sorry for the bad experience on CI.

haha understandable. Looking forward to more contributions <3

**Pull request merged**
