### PR TITLE
build: don't use disable TLS verification in build

### PR DESCRIPTION
**Pull request by grahambrereton-form3**
Remove `-k` flag to `curl` that was introduced previously. This flag disables all TLS verification and could allow for downloading the components from an untrusted source during the build.

## What problem does this PR solve?

This removes a source of potential insecurity during the build of chaos-daemon.

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by cwen0** [comment]
@grahambrereton-form3 Thanks for your contribution! Can you update CHANGELOG.md?

**Review by cwen0 — APPROVED** [review]
/lgtm

**Comment by grahambrereton-form3** [comment]
Integration tests seem to fail, having passed yesterday, with the only change being the changelog update?

**Comment by cwen0** [comment]
> Integration tests seem to fail, having passed yesterday, with the only change being the changelog update?

I have rerun it.

**Pull request merged**
