### PR TITLE
bump gqlgen to v0.17.2

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: xixi <i@hexilee.me>

### What problem does this PR solve?

[go 1.18](https://tip.golang.org/doc/go1.18) is released! It introduces generics, which may improve our development effectiveness.

However, the gqlgen v0.13 cannot work on go 1.18, so we should upgrade it first.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by Hexilee** [comment]
It seems there is a [bug](https://github.com/99designs/gqlgen/issues/1675) in gqlgen with go-1.18.

**Comment by Hexilee** [comment]
> It seems there is a [bug](https://github.com/99designs/gqlgen/issues/1675) in gqlgen with go-1.18.

It's fixed in gqlgen v0.17.2.

**Comment by Andrewmatilde** [comment]
PTAL on e2e-test @Hexilee .

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
