### PR TITLE
fix(ui): isolate scopes when creating NetworkChaos

### LINKED ISSUE #3224: fix(workflow-ng): isolate `target` field and `Scope` when creating `NetworkChaos` in UI

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Close #3224

### What's changed and how it works?

This PR distinguishes between different scopes when creating `NetworkChaos`.

Also, you can also see some non-related changes, most of these are needed for testing. So the core changes of this PR I have marked below:

https://github.com/chaos-mesh/chaos-mesh/blob/f4a20a74e354f2ac22ea95edc848a71919912367/ui/app/src/components/Scope/index.tsx#L64-L66

It checks if the `scope` key is the target field of the `NetworkChaos`.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [x] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — COMMENTED** [review]
LGTM

inside the component Scope, there might be a little mess about which kind of selector should we present, in lines 64 - 69; In the future, is there possible to extract one more components for render wiith leaving glue codes here? 🙈

**Review by STRRL — APPROVED** [review]

**Comment by g1eny0ung** [comment]
> LGTM
> 
> inside the component Scope, there might be a little mess about which kind of selector should we present, in lines 64 - 69; In the future, is there possible to extract one more components for render wiith leaving glue codes here? 🙈

@STRRL Yes! To reduce unnecessary conditions, another base component can be wrapped up here and I will create an issue to track it.

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
