### PR TITLE
fix:The patched annotation will overwrite the original annotation of the pod

### PR DESCRIPTION
**Pull request by wenliumeng**
fix：

The patched annotation will overwrite the original annotation of the pod.

To ensure deterministic patches sort the keys.

Problem Summary:

### What is changed and how it works?

* Modified the ifelse logic so that the logic in the first if statement does not cover all annotations.

* Traverse the map instead of traversing the string array.

What's Changed:

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

Tests
- [√] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Breaking backward compatibility

### CODE REVIEW

**Comment by STRRL** [comment]
Why do we need "To ensure deterministic patches sort the keys"?

`Labels` and `Annotations` are stored as `map[string]string` in golang, which is not guaranteed stable order of keys.

rest LGTM

**Comment by wenliumeng** [comment]
> Why do we need "To ensure deterministic patches sort the keys"?
> 
> `Labels` and `Annotations` are stored as `map[string]string` in golang, which is NOT claimed as stable order of keys.
> 
> rest LGTM

map is unordered. Because the return value of this method is an array. Ensure that the sequence in the loop will be safer

**Comment by STRRL** [comment]
> Ensure that the sequence in the loop will be safer

I do NOT think so. 😰 The order of patch operations is not required. If the order is required, we should specify it as an interface explicitly. Do not do unnecessary things. :) 

Too many bugs occur because of these "take the granted" things.

**Comment by wenliumeng** [comment]
> > Ensure that the sequence in the loop will be safer
> 
> I do NOT think so. 😰 The order of patch operations is not required. If the order is required, we should specify it as an interface explicitly. Do not do unnecessary things. :)
> 
> Too many bugs occur because of these "take the granted" things.

I think i agree。👍

**Comment by STRRL** [comment]
Hi @wenliumeng , let's move on!

How about removing that `sort.Strings(keys)`?

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
