### PR TITLE
Enable users to specify pod failure pause image via helm values

### LINKED ISSUE #1924: PodChaos - Pause Container
## Feature Request

**Is your feature request related to a problem? Please describe:**
No, not a problem but a feature request.

**Describe the feature you'd like:**
It would be really useful to have a chaos scenario that simply pauses a specific container for a specific amount of time, similar to `container-kill` but without killing the container, just pausing it.

**Describe alternatives you've considered:**
I've used `pumba` to accomplish this in the past, which basically relies on the `docker pause` command. The main problem is that `pumba` only works with `docker`, which is being deprecated within the Kubernetes echosystem.
Right now, and at least until there's a better approach, I'm simply using a Kubernetes `job` with a privileged container that searches for the process within the node and pauses it for a certain time:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: manager
spec:
  backoffLimit: 0
  template:
    spec:
      hostPID: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: statefulset.kubernetes.io/pod-name
                operator: In
                values:
                - "POD_NAME_HERE"
            topologyKey: "kubernetes.io/hostname"
      restartPolicy: Never
      containers:
      - name: root-container
        image: busybox
        env:
          - name: REGEX
            value: "REGEX_TO_MATCH_PROCESS_TO_PAUSE_HERE"
          - name: SLEEP_TIME
            value: "HOW_MUCH_TIME_TO_PAUSE_THE_PROCESS"
        command: ["/bin/sh", "-c"]
        args:
        - 
          PID=$(ps aux | grep ${REGEX} | grep -v "grep" | awk '{print $1}');
          [ -z ${PID} ] && echo "Could not find PID for process '${REGEX}'" && exit 1;
          echo "Pausing container with pid ${PID}...";
          kill -STOP ${PID} || exit 1;
          echo "Pausing container with pid ${PID}... Done!";
          echo "Sleeping ${SLEEP_TIME} seconds...";
          sleep ${SLEEP_TIME};
          echo "Resuming container with pid ${PID}...";
          kill -CONT ${PID} || exit 1;
          echo "Resuming container with pid ${PID}... Done!";
        securityContext:
          allowPrivilegeEscalation: true
```

**Teachability, Documentation, Adoption, Migration Strategy:**
This might be useful to simulate `stop-the-world` GC executions for java applications.
It would also be useful to simulate "temporal unresponsiveness" from a particular member of an already stablished distributed system and see how it behaves when the responsiveness have been restored (has it being removed from the system?, can it rejoin the system?, etc.).

### LINKED ISSUE #1925: Pause container in Pod Failure from Private Registry
## Feature Request

**Describe the feature you'd like:**
Currently the pause container used for pod failure is been pulled from gcr.io, but many orgs only allow images to be pulled from their private registries, in fact some orgs has OPA enforcement specifying the repos where images can be pulled from, and so chaos mesh gets blocked from even replacing the container image.

I would like to be able to configure the registry where the pause image https://github.com/chaos-mesh/chaos-mesh/blob/d343189d3ccb6e882720461903084fa8f84cc417/controllers/chaosimpl/podchaos/podfailure/impl.go#L34 is pulled from in values.yaml etc as well as the secret if required to pull from a private registry.

### PR DESCRIPTION
**Pull request by aido123**
Signed-off-by: root <root@vm2.j5nfkxtvikcexczoernjzqy4zb.fx.internal.cloudapp.net>

### What problem does this PR solve?

Issue Number: close #1925

Problem Summary:

### What is changed and how it works?

Proposal: This PR allows users to specify a pod failure pause image via helm values. This is useful for for organizations who can only pull images from internal registries and also where organizations have policy applied where images can only come from xyz.com

What's Changed:

* Added a new environmental variable (controller deployment) for the pause image to the chaos controller
* Add this new environment variable to the controller config. Defaults to gcr.io pause image
* Add this controller config to the pod failure impl and set the pause image from this config

Tests

- [x] Unit test
- [x] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Manual Tests

Test 1
- Created a new Kind cluster as per development guide
- Build images and add images to kind nodes
```
./install.sh --local kind --dependency-only
```
- Install chaos mesh via helm 
```
./helm install chaosmesh chaos-mesh/helm/chaos-mesh/ --set controllerManager.podChaos.podFailure.pauseImage=abc.io/google-containers/pause:latest --set controllerManager.image=localhost:5000/pingcap/chaos-mesh
```
- Install sample nginx deployment
```
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
- Install Pod Failure 
```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
spec:
  action: pod-failure
  mode: one
  value: ''
  selector:
    labelSelectors:
      'app': 'nginx'
```
- Get pod yaml and check if image is updated "abc.io/google-containers/pause:latest"
- Delete pod failure chaos and get image and reverted back to original

Test 2

- Repeat Test 1, but leave out controllerManager.podChaos.podFailure.pauseImage when installing helm. Get pod yaml of nginx pod and image should be updated to "gcr.io/google-containers/pause:latest"
- Delete pod failure chaos and get image and reverted back to original

Notes
- Needed to remove the crd for IoChaos installed via "./install.sh --local kind --dependency-only" as it had specified IoChaos, rather than expected IOChaos. Just applied from the crds directory
- In order to run unit tests and e2e tests via "make test", needed to move the location of kubebuilder to /usr/local/
```
cp -r /home/myhynes/chaos-mesh/output/bin/kubebuilder /usr/local/
```

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by fewdan — COMMENTED** [review]
It seems that there is no problem, you can update the "README.md" of helm.

**Comment by fewdan** [comment]
@aido123 
CI failed,  you can run "make check" to fix the CI.

**Comment by STRRL** [comment]
hi @aido123 , CI failed, you could run `make check`, this command will reformat/lint the codes, then commit the changes, that could fix  CI checks.

feel free to tell us if you meet any problem :)

**Comment by aido123** [comment]
Hi @STRRL ,

I seem to be getting this problem with the go diff check as part of make check everytime:

```
GO111MODULE=on go mod tidy
git diff -U --exit-code go.mod go.sum
diff --git a/go.sum b/go.sum
index f1c75ad8..7b1dabe0 100644
--- a/go.sum
+++ b/go.sum
@@ -69,7 +69,6 @@ github.com/aead/siphash v1.0.1/go.mod h1:Nywa3cDsYNNK3gaciGTWPwHt0wlpNV15vwmswBA
 github.com/agnivade/levenshtein v1.0.1/go.mod h1:CURSv5d9Uaml+FovSIICkLbAUZ9S4RqaHDIsdSBg7lM=
 github.com/ajstarks/svgo v0.0.0-20180226025133-644b8db467af/go.mod h1:K08gAheRH3/J6wwsYMMT4xOr94bZjxIelGM0+d/wbFw=
 github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc/go.mod h1:LOuyumcjzFXgccqObfd/Ljyb9UuFJ6TxHnclSeseNhc=
-github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 h1:JYp7IbQjafoB+tBA3gMyHYHrpOtNuDiK/uB5uXxq5wM=
 github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751/go.mod h1:LOuyumcjzFXgccqObfd/Ljyb9UuFJ6TxHnclSeseNhc=
 github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf/go.mod h1:ybxpYRFXyAe+OPACYpWeL0wqObRcbAqCMya13uyzqw0=
 github.com/allegro/bigcache v1.2.1-0.20190218064605-e24eb225f156/go.mod h1:Cb/ax3seSYIx7SuZdm2G2xzfwmv3TPSk2ucNfQESPXM=
Makefile:168: recipe for target 'tidy' failed
make: *** [tidy] Error 1
```

The highlighted dependency that gets removed for me is:
-github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 h1:JYp7IbQjafoB+tBA3gMyHYHrpOtNuDiK/uB5uXxq5wM=


Any suggestions?

**Comment by aido123** [comment]
@STRRL make check working now. Thank you. Let me know if you have any feedback/comments

**Comment by aido123** [comment]
Closing PR as seem to have got in some sort of conflict hell :-) Will create another PR

**Pull request closed without merging**
