### PR TITLE
Remove unnecessary namespaceSelector from MutatingWebhookConfiguration

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Remove unnecessary `namespaceSelector` from `MutatingWebhookConfiguration`

### What is changed and how does it work?
Nothing changes from functionality point of view.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
@anuragpaliwal80 Great! Thanks for your contribution!

**Comment by STRRL** [comment]
I think the whole "admission-webhook.chaos-mesh.org" webhook is not used anymore, it could be deleted.

PTAL @cwen0 @YangKeao

**Comment by YangKeao** [comment]
@STRRL Yes. The first webhook of `MutatingWebhookConfiguration` can be removed. We don't need to modify pods anymore. However, the rest of these webhooks are still needed :smile_cat:

**Comment by anuragpaliwal80** [comment]
Does upcoming `JVMChaos` is also not depending upon `admission-webhook` @YangKeao ?

**Comment by YangKeao** [comment]
> Does upcoming `JVMChaos` is also not depending upon `admission-webhook` @YangKeao ?

Don't mind. @STRRL told me `JVMChaos` failed to reuse this part of configuration/codes :man_facepalming:

**Comment by anuragpaliwal80** [comment]
So will remove whole "admission-webhook.chaos-mesh.org" webhook in separate PR.

**Comment by anuragpaliwal80** [comment]
> So will remove whole "admission-webhook.chaos-mesh.org" webhook in separate PR.

Oops I just noticed `namespaceSelector` is part of this webhook only so will remove in this PR itself.

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
My bad. I just realize that JVMChaos does depend on that webhook.😥 @YangKeao @anuragpaliwal80 

So we should not remove it.

> I have designed a runtime-injection jvm chaos which have not merged into master, which causes my terrible idea. 😥

**Comment by anuragpaliwal80** [comment]
I am doing 
```
git commit --amend --no-edit --signoff
```
and then
```
git push --force-with-lease origin apaliwal_remove_admission-webhook_in_matchLabels
```
Still DCO check is failing?

**Comment by anuragpaliwal80** [comment]
As DCO is not passing tried a new PR #1580

**Comment by anuragpaliwal80** [comment]
So closing this one as new one has opened.

**Pull request closed without merging**
