### PR TITLE
cherry-pick(#2672): kill chaos-tproxy while failing to apply config

### LINKED ISSUE #2660: bpm runs into deadlocked once errors occur in applying config of HTTPChaos
## Bug Report

**What version of Chaos Mesh are you using?**

v2.x.x

**What did you do?**

Encounter any errors in applying the config of HTTPChaos .

**What did you expect to see?**

HTTPChaos works after retrying or fixing config.

**What did you see instead?**

The `bpm` runs into deadlocked

**Reason**

The bpm will try to get an identifier lock when a subprocess starts (the instance is 0) and release the lock when the subprocess exits. Currently, chaos-tproxy won't exit when encountering any errors in applying config, and in this case, the PodHTTPChaos won't store the instance in status. 

**Solutions**
1. Kill the tproxy instance when encountering any errors in applying config
2. Store the instance id in the status of PodHTTPChaos once the tproxy starts.

### PR DESCRIPTION
**Pull request by Hexilee**
### What problem does this PR solve?

Cherry pick #2672

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [x] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by Andrewmatilde** [comment]
Please fix unit tests.

**Comment by Hexilee** [comment]
> Please fix unit tests.

Fixed

**Review by STRRL — APPROVED** [review]

**Comment by Hexilee** [comment]
in.ProxyPorts

**Pull request merged**
