### PR TITLE
Revert "Use bigheap to inject heap stress (#776)"

### PR DESCRIPTION
**Pull request by YangKeao**
This reverts commit c0ff1bf0d0d25157baedbbfc503bf34cb7cf0d01.

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### What problem does this PR solve?

Sorry. It's my fault to submit #776, which is because of my wrong understanding of `stress-ng`. After reading the implementation and document again, I found that it not only `mmap` and allocate pages, but also write to them, which makes it a real used memory.

And test with the dashboard, I found that the original issue (which tells me `StressChaos` of memory doesn't work) cannot be reproduced :crying_cat_face:. I really regretted for this stupid PR :facepalm: . The frontend has also been modified, and I tried to revert it (and test through click, click :smile_cat: ). Hope it doesn't bring any bug. So @g1eny0ung please review this PR.

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM. Code in the front-end has no problems.

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> LGTM. Code in the front-end has no problems.

Does the front-end provide `size` field for `StressChaos` of memory?

**Comment by g1eny0ung** [comment]
> > LGTM. Code in the front-end has no problems.
> 
> Does the front-end provide `size` field for `StressChaos` of memory?

Yes.

**Comment by cwen0** [comment]
@YangKeao Please fix the e2e test! Thanks!

**Comment by YangKeao** [comment]
> @YangKeao E2e test failed sweat_smile, Please fix it! Thanks!

Wait for #1588

**Review by cwen0 — APPROVED** [review]

**Comment by cwen0** [comment]
> cherry pick to release-1.1 failed

@YangKeao PTAL

**Pull request merged**
