### PR TITLE
fix localstack installation in integration tests

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

The latest helm chart of localstack with version 0.1.3 has some issue, it breaks the integration test.😰

### What is changed and how does it work?

Install localstack with helm chart 0.1.2.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
Which issue breaks the integration test? could you please provide some links

**Comment by STRRL** [comment]
> Which issue breaks the integration test? could you please provide some links

There is no reported issue created yet, but I think this commit https://github.com/localstack/helm-charts/commit/819f55c66553d5058c63bee0444fb062576d3c22 causes the issue.

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
