### PR TITLE
Run default before validate schedule chaos

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Some validations depend on the mutating webhook. For example, network chaos validating webhook will validate the `correlation`, which is allowed to be empty and will be set by mutating webhook (to zero)

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
/merge

e2e test failed because of unstable network environment

**Pull request merged**
