### PR TITLE
chore: related changes on frontend about #2221

### LINKED ISSUE #2054: unnecessary wrap for `[]NodeNameWithTemplate` in Dashboard API
:cold_sweat:  I must be drunk when I wrote these code:

```go
// Node defines a single step of a workflow.
type Node struct {
	Name     string        `json:"name"`
	Type     NodeType      `json:"type"`
	State    NodeState     `json:"state"`
	Serial   *NodeSerial   `json:"serial,omitempty"`
	Parallel *NodeParallel `json:"parallel,omitempty"`
	Template string        `json:"template"`
	UID      string        `json:"uid"`
}

type NodeNameWithTemplate struct {
	Name     string `json:"name,omitempty"`
	Template string `json:"template,omitempty"`
}

// FIXME: unnecessary another wrap of []NodeNameWithTemplate, like struct NodeSerial and NodeParallel

// NodeSerial defines SerialNode's specific fields.
type NodeSerial struct {
	Children []NodeNameWithTemplate `json:"children"`
}

// NodeParallel defines ParallelNode's specific fields.
type NodeParallel struct {
	Children []NodeNameWithTemplate `json:"children"`
}
```

Structs `NodeSerial` and `NodeParallel` are totally useless. It should be like

```go
// Node defines a single step of a workflow.
type Node struct {
	Name     string                `json:"name"`
	Type     NodeType              `json:"type"`
	State    NodeState             `json:"state"`
	Serial   []NodeNameWithTemplate `json:"serial,omitempty"`
	Parallel []NodeNameWithTemplate `json:"parallel,omitempty"`
	Template string                `json:"template"`
	UID      string                `json:"uid"`
}
```

Related test cases and frontend API also need updates

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Issue Number: close #2054

Problem Summary:

- frontend related changes about #2221

### What is changed and how it works?

What's Changed:

- remove redundant nested `children`

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @fewdan

**Review by fewdan — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
