### PR TITLE
auth: add rooturl configuration in gcp authentication

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Try to get the scheme and host from the request is not realistic. If the dashboard is deployed behind a load balancer, it will have no way to guess the scheme. In this PR, I added a config field, so that the users can set the root url manually. The dashboard will append `/api/auth/gcp/callback` to the path.

BTW, it also installs the `ca-certificates` to the `chaos-dashboard` container, which is required to avoid x509 error.

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM! It works!

**Review by g1eny0ung — APPROVED** [review]
LGTM 🍺

**Pull request merged**
