### PR TITLE
chore: add CII best practices badge for Chaos Mesh

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

- add the badges for OpenSFF CII Best Practices: https://bestpractices.coreinfrastructure.org/en/projects/4185
- like that: 

[CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/3680)

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by YangKeao** [comment]
I wonder how these values are evaluated?

**Comment by STRRL** [comment]
> I wonder how these values are evaluated?

It should be updated MANUALLY. I could update it after login with GitHub.
image

But I am not sure how that platform resolves the permission.

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
