### PR TITLE
Add: Chaos Mesh community event page link

### PR DESCRIPTION
**Pull request by milasuperstar**
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by AsterNighT — APPROVED** [review]
lgtm

**Comment by fewdan** [comment]
@milasuperstar
It seems that you should resolve the conflicts first (READEME.md).

**Comment by AsterNighT** [comment]
BTW, there're conflicts to resolve first.

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
