### PR TITLE
Changes in error formats and string

### PR DESCRIPTION
**Pull request by nisarg1499**
### What problem does this PR solve?

fmt.Errorf should be used instead of errors.New and string in error should start with lower case
### What is changed and how does it work?
changed errors.New() to fmt.Errorf()
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM, but I remember it might be duplicated with another PR, and I failed to find the earlier one.   🙈
So this PR might be closed if another one is merged sooner.

**Review by Hexilee — APPROVED** [review]
LGTM

**Comment by nisarg1499** [comment]
> LGTM, but I remember it might be duplicated with another PR, and I failed to find the earlier one. 
> So this PR might be closed if another one is merged sooner.

@STRRL Yaa sure. But can you give this PR access to run tests and everything. If we find the previous PR and if it get's merged before this, then I'll close this.

**Comment by nisarg1499** [comment]
@STRRL Every test is passed. Should we merge this?

**Comment by YangKeao** [comment]
Thanks for your contribution :beers:

**Pull request merged**
