### PR TITLE
Revert #3342 multicluster 

### PR DESCRIPTION
**Pull request by STRRL**
"[multicluster] bootstrap controller manager at runtime with clusterregistry (#3342)"

This reverts commit ea12c187dcc8ea7d2b26f46cb0cf88ad97b5faaf.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
ping feature owner @YangKeao, PTAL

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
@STRRL Maybe we need to modify the configuration of bot to remove the test.

**Comment by YangKeao** [comment]
I've submitted a PR https://github.com/ti-community-infra/configs/pull/609 to fix this problem.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
