### PR TITLE
[BugBash] SC2217: Use cat instead of echo in kind-cluster-build.sh 

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?
Use cat instead of echo in kind-cluster-build.sh 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @anuragpaliwal80 , if you could paste the link on sonartype lift refers to the issue, I would be very thankful.

**Comment by anuragpaliwal80** [comment]
Sure. https://lift.sonatype.com/results/github.com/chaos-mesh/chaos-mesh/01G25JX80N5F51PH29QJ3RE7JV?t=Shellcheck%7CSC2217

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by Hexilee — APPROVED** [review]
LGTM

**Pull request merged**
