### PR TITLE
feat: add rate action in NetworkChaos

### PR DESCRIPTION
**Pull request by ibalajiarun**
### What problem does this PR solve?

This PR adds the ability to inject bandwidth chaos via netem action using the `tc netem`'s rate option. This is useful in situations where one needs to inject multiple network chaos including delay, loss, and rate supported by netem in a single test.

Limitations: unlike the bandwidth chaos action, the options supported by netem's rate feature is limited to only the bandwidth rate.

### What's changed and how it works?

The change adds a new field called `Rate` backed by a `RateSpec` into the `NetworkChaosSpec`. This rate is appended  to the `netem` command under the `rate` param.

### Related changes

- [x] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [x] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [X] Unit test
- [x] E2E test
- [ ] No code
- [X] Manual test (add steps below)

steps: 

Followed the steps in https://chaos-mesh.org/docs/add-new-chaos-experiment-type/ to make sure the chaos was injected successfully.

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Thanks @ibalajiarun for your contribution! That's a great PR for netem `rate` support. ❤️ 

The current PR acts as an adaptor, which bridge `BandwidthSpec` with `netem rate`, and it might be bring some confusion on the declarative API: The `bandwidth` still affect, even the action is not `bandwidth` but `netem`.

I prefer to append a new field into NetworkChaosSpec, called `RateSpec`, like existed `DelaySpec`, `LossSpec`, etc, for claiming the behavior more clearly.

What do you think about it? @ibalajiarun 

also cc @YangKeao

**Comment by ibalajiarun** [comment]
Hi @STRRL I was on the fence on this too, but I did not want to introduce any changes to CRDs, but looks like that will make this cleaner. Sure, let me quickly update the PR.

**Comment by STRRL** [comment]
Thanks a lot, @ibalajiarun! 

And there might be a little difficult to introduce changes into CRDs. Feel free discuss here or contact us in slack channel `#project-chaos-mesh` https://cloud-native.slack.com/archives/C0193VAV272

**Comment by ibalajiarun** [comment]
Hi @STRRL, I have tried to introduce the CRD change. Can you please take a look?

**Review by g1eny0ung — APPROVED** [review]
LGTM! I'll merge this PR now. FYI @STRRL if you have any additional questions, we can open an issue to talk about this feature.

**Pull request merged**
