### PR TITLE
Updated Makefile

### PR DESCRIPTION
**Pull request by Debanitrkl**
### What problem does this PR solve?
 #1540 has been solved

### What is changed and how does it work?
 Replaced the recipe `all` as the first recipe of the makefile

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Related changes

- [x] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @Debanitrkl, you should update your commits for the DCO check.

**Review by AsterNighT — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM

**Pull request merged**
