### PR TITLE
cherrypick "refine logging in pkg time (#2964)" into release-2.1

### PR DESCRIPTION
**Pull request by STRRL**
### What's changed and how it works?

cherry-pick https://github.com/chaos-mesh/chaos-mesh/pull/2964 into release-2.1

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by iguoyr — APPROVED** [review]
LGTM

**Review by iguoyr — CHANGES_REQUESTED** [review]
Please fix the CI error about `gqlgen` first.

**Comment by STRRL** [comment]
waiting for https://github.com/chaos-mesh/chaos-mesh/pull/3071

**Comment by STRRL** [comment]
Updated! PTAL

/cc @iguoyr @YangKeao @Andrewmatilde

**Comment by STRRL** [comment]
PTAL 

/cc @chaos-mesh/maintainers @chaos-mesh/committers

**Comment by STRRL** [comment]
Hi @iguoyr @YangKeao @Andrewmatilde , PTAL

**Comment by iguoyr** [comment]
Hi @STRRL, please add changelog for this pr, and it seems that the 'MUST update CHANGELOG' workflow is not exist on branch release-2.1, could you cherry pick it into branch release-2.1 first?

**Comment by STRRL** [comment]
> Hi @STRRL, please add changelog for this pr, and it seems that the 'MUST update CHANGELOG' workflow is not exist on branch release-2.1, could you cherry pick it into branch release-2.1 first?

OK, I will do that.

**Comment by STRRL** [comment]
PTAL

/cc @iguoyr @Andrewmatilde @YangKeao

**Review by g1eny0ung — APPROVED** [review]
LGTM. This PR has been around for too long.

**Comment by g1eny0ung** [comment]
Since `v2.1` is no longer in the maintenance cycle, I will merge this PR directly after the test passes

**Pull request merged**
