### PR TITLE
doc: add Apache APISIX as adopter.

### PR DESCRIPTION
**Pull request by moonming**
### What problem does this PR solve?

add Apache APISIX as adopter.
We are using this project to test the stability of Apache APISIX.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
@moonming Thanks for your contribution! Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/1268/checks?check_run_id=1529715465) first?

**Comment by dcalvin** [comment]
Great addition to the Chaos Mesh community!

**Comment by moonming** [comment]
> @moonming Thanks for your contribution! Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/1268/checks?check_run_id=1529715465) first?

sure, fixed

**Review by dcalvin — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
