### PR TITLE
fix doc error

### PR DESCRIPTION
**Pull request by inetkiller**
controllerManager.image.x is repeated. one should be chaosDaemon.image.x

Signed-off-by: yi.tang <tinetkiller@gmail.com>

### CODE REVIEW

**Comment by cwen0** [comment]
@inetkiller Thanks for your contribution! Can you fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/3446/checks?check_run_id=7296165218) first?

**Comment by inetkiller** [comment]
@cwen0 fixed.

**Review by xlgao-zju — APPROVED** [review]
LGTM

**Review by STRRL — COMMENTED** [review]
LGTM!

Thanks for your contribution! @inetkiller

**Review by STRRL — APPROVED** [review]

**Pull request merged**
