### PR TITLE
feat(chaos dashboard): add deleting status

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What's changed and how it works?

  

If the chaos object is deleted and blocked, we should show it on chaos dashboard. In this pr, I add a new status `deleting` to describe this status. 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [x] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [x] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

image

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
The name `Deleted` is more accurate?

**Comment by cwen0** [comment]
> 

I don't think so. Because the real status is `deleting` and the chaos experiment has not been recovered.  `Deleted` maybe make users confused.

**Comment by cwen0** [comment]
> The name `Deleted` is more accurate?

I don't think so. Because the real status is `deleting` and the chaos experiment has not been recovered.  `Deleted` maybe make users confused.

**Comment by g1eny0ung** [comment]
> > The name `Deleted` is more accurate?
> 
> I don't think so. Because the real status is `deleting` and the chaos experiment has not been recovered. `Deleted` maybe make users confused.

According to my understanding, when users click on the `Deleting` experiment, API will return experiment not found, it's also weird. 😢

**Comment by cwen0** [comment]
> > > The name `Deleted` is more accurate?
> > 
> > 
> > I don't think so. Because the real status is `deleting` and the chaos experiment has not been recovered. `Deleted` maybe make users confused.
> 
> But according to my understanding, when users click on the `Deleting` experiment, API will return experiment not found, it's also weird. 😢

This issue was fixed in #2698

**Review by g1eny0ung — APPROVED** [review]
Know about it. This LGTM. 👍🏽

**Review by STRRL — APPROVED** [review]
LGTM

**Pull request merged**
