### PR TITLE
fix not implement:fake_image_linux_arm64

### PR DESCRIPTION
**Pull request by Andrewmatilde**
Signed-off-by: andrewmatilde <davis6813585853062@outlook.com>

### What problem does this PR solve?
Make arm64 build well.
#3191

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] E2E test

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by Andrewmatilde** [comment]
PTAL @Hexilee , @STRRL .

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
PTAL

/cc @Hexilee @YangKeao

**Comment by STRRL** [comment]
I would retrigger the nightly build after this PR merged.

**Review by YangKeao — APPROVED** [review]

**Pull request merged**
