### PR TITLE
chore: change stress workers' default value to 0

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What is changed and how does it work?

Currently, all of the `StressChaos` workers' default values were init as 1.

This creates a problem if the user only wants to create the `CPU` or `Memory` test, she/he must set one to 0.

So this PR changes the default value to 0 and adds validation to restrict user must increase one `workers` field bigger than 0.

Other changes:

- Remove some unused imports

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@g1eny0ung PTAL

**Comment by g1eny0ung** [comment]
> @g1eny0ung PTAL

Done in #1524.

**Pull request merged**
