### PR TITLE
add genericSelector struct

### PR DESCRIPTION
**Pull request by iguoyr**
Signed-off-by: SiyuChen <ryougi201@gmail.com>

### What problem does this PR solve?

Problem Summary: as https://github.com/chaos-mesh/chaos-mesh/issues/2390 said, this pr prepares for physical machine auth.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: add `GenericSelectorSpec` struct, including `namespace`, `annotation`, `label`, `expression` and `field`.

### Related changes

NA

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by iguoyr** [comment]
/cc @YangKeao 
/cc @STRRL 
PTAL

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
