### PR TITLE
chaos node could also sync schedule

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

It makes Workflow could dispatch Schedule with `templateType: Schedule`.
for example:

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: podchaos-in-workflow
spec:
  entry: workflow-pod-chaos
  templates:
    - name: workflow-pod-chaos
      templateType: Schedule
      duration: 40s
      schedule:
        schedule: "@every 2s"
        concurrencyPolicy: Allow
        type: PodChaos
        podChaos:
          action: pod-kill
          mode: one
          selector:
            labelSelectors:
              "app": "hello-kubernetes"

```

### What is changed and how does it work?

It creates another struct called `ChaosOnlyScheduleSpec` for describing Schedule in workflow, the difference is `ChaosOnlyScheduleSpec` does not contains Workflow anymore.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
@AsterNighT Please use github Approve to approve this PR. `/lgtm` will not work anymore.

**Review by AsterNighT — APPROVED** [review]

**Comment by STRRL** [comment]
Yeah! I am going to merge this PR!

**Pull request merged**
