### PR TITLE
[BugBash] ST1019: Removed extra import of common pkg

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Removed extra import of common pkg

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
@STRRL How can we re-run the failed tests?

**Comment by STRRL** [comment]
> @STRRL How can we re-run the failed tests?

Only committers and maintainers (hold the write permission to GitHub repo) could rerun the tests, due to the poor integration between github actions and our bot....

**Review by STRRL — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
> > @STRRL How can we re-run the failed tests?
> 
> Only committers and maintainers (hold the write permission to GitHub repo) could rerun the tests, due to the poor integration between github actions and our bot....

Do you mean, we should use the bot to rerun the failed tests? (As the github actions only allow the developer with write permission to rerun the workflow)

**Pull request merged**
