### PR TITLE
feat: update the start time of workflow

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What is changed and how does it work?
The rest part of #1828, I forgot to update the startTime. :cry: 

When the entry controller applying, update the startTime of the workflow.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by AsterNighT — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
Note: some others CRD use the `Meta#CreationTimeStamp` as the `StartTime`, I think it's much better to use the time of controller visit it.

**Pull request merged**
