### PR TITLE
cherry pick #3449 to release-2.3

### PR DESCRIPTION
**Pull request by STRRL**
this PR manually cherrypick #3449 into release-2.3

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL 

/cc @g1eny0ung

also ping release managers

/cc @YangKeao @Hexilee @cwen0

**Review by g1eny0ung — APPROVED** [review]
LGTM, thanks for helping cherry-pick the original PR.

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
