### PR TITLE
Prune multiclueter out from release 2.4

### PR DESCRIPTION
**Pull request by STRRL**
this PR is most like #3471, pruning multicluster related codes out of release-2.4 branch

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Please fix the DCO:

> Commit sha: [df65cf2](https://github.com/chaos-mesh/chaos-mesh/pull/3661/commits/df65cf264fcaf4ad473da02e5e8f8da97bd4e131), Author: STRRL, Committer: STRRL; The sign-off is missing.

**Comment by STRRL** [comment]
> Please fix the DCO:
> 
> > Commit sha: [df65cf2](https://github.com/chaos-mesh/chaos-mesh/pull/3661/commits/df65cf264fcaf4ad473da02e5e8f8da97bd4e131), Author: STRRL, Committer: STRRL; The sign-off is missing.

Updated!

**Pull request merged**
