### PR TITLE
fix the bug that create JVMChaos failed in workflow

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

### What problem does this PR solve?

fix issue #3155 

### What's changed and how it works?

`JVMChaosSpec`'s root may not be `JVMChaos`, it can also be `Workflow`.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
Validation with `root` might be dangerous, and there are also other similar usages like `IOErrno`, `EbsVolume`, which would be a potential issue.   

FYI @YangKeao

**Comment by Andrewmatilde** [comment]
IMO, we should also reduce code with reflction.

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
