### PR TITLE
Overwrite $IMAGE_BUILD_ENV_TAG with $IMAGE_TAG-$ARCH in `upload_env_image.yml` github action

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What problem does this PR solve?

 

https://github.com/chaos-mesh/chaos-mesh/blob/e0e0d54f646362d8df81826b4b3b3c723302779a/build/build_image.py#L31-L46 
In `build_image.py`, `IMAGE_BUILD_ENV_TAG` lacks the platform information and will overwrite `IMAGE_TAG`, which makes `update-env-image`  task fail.  

https://github.com/chaos-mesh/chaos-mesh/runs/7280233499?check_suite_focus=true

```
docker buildx build --load --platform amd64 --build-arg GOPROXY=https://proxy.golang.org/,direct --build-arg LDFLAGS=-s -w -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.buildDate=2022-07-11T10:12:10Z' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitCommit=a625391909b3a3abec0a8e1321ecc31dcb43491b' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitVersion=master-a625391909b3a3' --build-arg GO_BUILD_CACHE=/home/runner/work/chaos-mesh/chaos-mesh/.cache/chaos-mesh --build-arg YARN_BUILD_CACHE=/home/runner/work/chaos-mesh/chaos-mesh/.cache/yarn --build-arg TARGET_PLATFORM=amd64 -t ghcr.io/chaos-mesh/build-env:latest images/build-env
touch images/build-env/.dockerbuilt
0s
Run # ${VAR,,} convert VAR to lower case
The push refers to repository [ghcr.io/chaos-mesh/build-env]
tag does not exist: ghcr.io/chaos-mesh/build-env:latest-amd64
Error: Process completed with exit code [1](https://github.com/chaos-mesh/chaos-mesh/runs/7280233499?check_suite_focus=true#step:6:1).
``` 

https://github.com/chaos-mesh/chaos-mesh/pull/3216 made `IMAGE_BUILD_ENV_TAG` really work, and caused https://github.com/chaos-mesh/chaos-mesh/runs/7280233499?check_suite_focus=true failed. 

### What's changed and how it works?

~~Remove `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG`~~ 
Overwrite $IMAGE_BUILD_ENV_TAG with $IMAGE_TAG-$ARCH in upload_env_image.yml github action 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)  

https://github.com/chaos-mesh/chaos-mesh/runs/7323983673?check_suite_focus=true

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by cwen0** [comment]
https://github.com/chaos-mesh/chaos-mesh/pull/3216 made `IMAGE_BUILD_ENV_TAG` really work, and caused https://github.com/chaos-mesh/chaos-mesh/runs/7280233499?check_suite_focus=true failed.

**Comment by STRRL** [comment]
First of all, we lack documentation about how our CI works. 😅

I am afraid that we could not just remove `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG`.

The purpose of `IMAGE_BUILD_ENV_TAG`, `IMAGE_DEV_ENV_TAG` is, to use `ghcr.io/chaos-mesh/dev-env:<tag>` and  `ghcr.io/chaos-mesh/build-env:<tag>` with **corresponding tag based on the branch name**. 

For example, when we build Chaos Mesh on branch `release-2.2`, it should use use `ghcr.io/chaos-mesh/dev-env:release-2.2` and  `ghcr.io/chaos-mesh/build-env:release-2.2`, not `ghcr.io/chaos-mesh/dev-env:latest` and  `ghcr.io/chaos-mesh/build-env:latest`.

Only removing these ENV would affect the next release branch: release-2.3, it would always use `latest` instead of `release-2.3`, which is not expected.

And actually, only the CI "Upload Env Images" requires considering the "multi-platform container images" thing, the developers/contributors working on the local machine usually do not need to build multi-platform container images.

I think we should update the GitHub Action for https://github.com/chaos-mesh/chaos-mesh/blob/release-2.2/.github/workflows/upload_env_image.yml, using the current branch name with `-arm64` and `-amd64` suffix as the tag.

And these changes should be cherry-picked into release-2.1 and release-2.2

/cc @YangKeao

**Comment by cwen0** [comment]
> First of all, we lack documentation about how our CI works. 😅
> 
> I am afraid that we could not just remove `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG`.
> 
> The purpose of `IMAGE_BUILD_ENV_TAG`, `IMAGE_DEV_ENV_TAG` is, to use `ghcr.io/chaos-mesh/dev-env:<tag>` and `ghcr.io/chaos-mesh/build-env:<tag>` with **corresponding tag based on the branch name**.
> 
> For example, when we build Chaos Mesh on branch `release-2.2`, it should use use `ghcr.io/chaos-mesh/dev-env:release-2.2` and `ghcr.io/chaos-mesh/build-env:release-2.2`, not `ghcr.io/chaos-mesh/dev-env:latest` and `ghcr.io/chaos-mesh/build-env:latest`.
> 
> Only removing these ENV would affect the next release branch: release-2.3, it would always use `latest` instead of `release-2.3`, which is not expected.
> 
> And actually, only the CI "Upload Env Images" requires considering the "multi-platform container images" thing, the developers/contributors working on the local machine usually do not need to build multi-platform container images.
> 
> I think we should update the GitHub Action for https://github.com/chaos-mesh/chaos-mesh/blob/release-2.2/.github/workflows/upload_env_image.yml, using the current branch name with `-arm64` and `-amd64` suffix as the tag.
> 
> And these changes should be cherry-picked into release-2.1 and release-2.2
> 
> /cc @YangKeao

Yes, removing `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG` may not be a good choice.  In `upload_env_image.yam`, image-tag was generated by ` IMAGE_TAG=$(./hack/env-image-tag.sh build-env)`. So the image tag in GitHub action includes the branch name.  And also post `IMAGE_TAG-$ARCH` to the build command.  Maybe we can overwrite `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG` with `IMAGE_TAG-$ARCH` In `upload_env_image.yam`

**Comment by cwen0** [comment]
> > First of all, we lack documentation about how our CI works. 😅
> > I am afraid that we could not just remove `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG`.
> > The purpose of `IMAGE_BUILD_ENV_TAG`, `IMAGE_DEV_ENV_TAG` is, to use `ghcr.io/chaos-mesh/dev-env:<tag>` and `ghcr.io/chaos-mesh/build-env:<tag>` with **corresponding tag based on the branch name**.
> > For example, when we build Chaos Mesh on branch `release-2.2`, it should use use `ghcr.io/chaos-mesh/dev-env:release-2.2` and `ghcr.io/chaos-mesh/build-env:release-2.2`, not `ghcr.io/chaos-mesh/dev-env:latest` and `ghcr.io/chaos-mesh/build-env:latest`.
> > Only removing these ENV would affect the next release branch: release-2.3, it would always use `latest` instead of `release-2.3`, which is not expected.
> > And actually, only the CI "Upload Env Images" requires considering the "multi-platform container images" thing, the developers/contributors working on the local machine usually do not need to build multi-platform container images.
> > I think we should update the GitHub Action for https://github.com/chaos-mesh/chaos-mesh/blob/release-2.2/.github/workflows/upload_env_image.yml, using the current branch name with `-arm64` and `-amd64` suffix as the tag.
> > And these changes should be cherry-picked into release-2.1 and release-2.2
> > /cc @YangKeao
> 
> Yes, removing `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG` may not be a good choice. In `upload_env_image.yam`, image-tag was generated by ` IMAGE_TAG=$(./hack/env-image-tag.sh build-env)`. So the image tag in GitHub action includes the branch name. And also post `IMAGE_TAG-$ARCH` to the build command. Maybe we can overwrite `IMAGE_BUILD_ENV_TAG` and `IMAGE_DEV_ENV_TAG` with `IMAGE_TAG-$ARCH` In `upload_env_image.yam`
> 
> @STRRL @YangKeao PTAL

Fixed!

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by iguoyr — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
