### PR TITLE
refactor: refine logging in pkg/dashboard/apiserver/utils

### LINKED ISSUE #2878: Refine logging in `pkg/dashboard/apiserver/utils`, use `log.L()` instead of package level variable `Log`
> Please leave comments with your idea if you are interested in this issue. And comment `/assign` to operate self-assign before you work on it.

### PR DESCRIPTION
**Pull request by spencercjh**
## What problem does this PR solve?

Close #2878 

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [X] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [X] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

### CODE REVIEW

**Comment by spencercjh** [comment]
It seems that CONTRIBUTING.md is out of date and updating CHANGE_LOG isn't mentioned there. I will fix it soon.

**Comment by g1eny0ung** [comment]
> It seems that CONTRIBUTING.md is out of date and updating CHANGE_LOG isn't mentioned there although this PR is no need to update changelog.

Hmmm...the `CONTRIBUTING.md` was indeed outdated for a time. Yes, this PR can be done without the changelog.

**Review by g1eny0ung — APPROVED** [review]
/lgtm

LGTM!

**Pull request merged**
