### PR TITLE
fix(#2155): 404 not found

### LINKED ISSUE #2155: Check Markdown links always fails on master branch
## Bug Report

It seems https://chaos-mesh.org/blog/how-a-top-game-company-uses-chaosengineering-to-improve-testing not rendered correctly, the `.md` file does exist in `chaos-mesh/website` repo, but that URL path returns 404.

```
=========================> MARKDOWN LINK CHECK <=========================

FILE: ./ADOPTERS.md
[✖] chaos-mesh.org/blog/how-a-top-game-company-uses-chaosengineering-to-improve-testing

19 links checked.

ERROR: 1 dead links found!
[✖] chaos-mesh.org/blog/how-a-top-game-company-uses-chaosengineering-to-improve-testing → Status: 404

```

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Issue Number: close #2155

Problem Summary:

### What is changed and how it works?

What's Changed:

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

Changes on indent do not affect the rendering result.

**Review by milasuperstar — APPROVED** [review]
LGTM

**Pull request merged**
