### PR TITLE
Update Go to 1.20

### PR DESCRIPTION
**Pull request by fasmat**
## What problem does this PR solve?

With the release of Go 1.21 version 1.19 has been discontinued. This PR updates the go version used for `chaos-mesh` to 1.20.

## What's changed and how it works?

- All `Dockerfiles` and workflow files specifying Go 1.19 have been updated to use Go 1.20 instead.
- Other smaller fixes that came with the version update

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [x] Unit test
- [x] E2E test
- [ ] Manual test

### Side effects

- [x] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @cwen0, IIUC, there is also a security issue that we should bump the go version, right?

or maybe we could bump the go version to 1.21 directly?

**Comment by fasmat** [comment]
https://github.com/quic-go/quic-go isn't yet compatible with Go 1.21 afaik. Also skipping to 1.21 would prevent users still on 1.20 to update chaos-mesh.

**Comment by g1eny0ung** [comment]
> Hi @cwen0, IIUC, there is also a security issue that we should bump the go version, right?
> 
> or maybe we could bump the go version to 1.21 directly?

I remembered that the security issues were also be carried into 1.20. 🤔

**Comment by fasmat** [comment]
This PR probably needs the labels `rebuild-build-env-image` and `rebuild-dev-env-image` to pass the CI.

**Comment by fasmat** [comment]
CI is passing now 🙂

**Comment by g1eny0ung** [comment]
> CI is passing now 🙂

Great! we will review it tonight.

**Comment by fasmat** [comment]
Is something still needed to merge the PR? 🙂

**Comment by g1eny0ung** [comment]
> Is something still needed to merge the PR? 🙂

Nothing. Don't know why the bot got stuck. I will manually merge it now.

**Pull request merged**
