### PR TITLE
fix: add some annotation to pull request template

### PR DESCRIPTION
**Pull request by iguoyr**
### What problem does this PR solve?

Problem Summary: 

### What is changed and how it works?

What's Changed: update pull_request_template.md

### Related changes

* No

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by cwen0** [comment]
@iguoyr Please fix [DCO](https://github.com/chaos-mesh/chaos-mesh/pull/2276/checks?check_run_id=3502474677) first!

**Comment by iguoyr** [comment]
@cwen0 done.

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
