### PR TITLE
dashboard: remove limit action from BlockChaos and generate specs

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

This PR removes the limit action, and run codegen, though I don't know whether these codegen behaves well.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [x] release-2.4
  - [x] release-2.3
  - [ ] release-2.2

### CODE REVIEW

**Review by g1eny0ung — CHANGES_REQUESTED** [review]
It looks like for a long time the `PhysicalMachineChaos` weren't syncing the OpenAPI after the changes, so it's better to fix that with the new PR since I'm not sure if it's causing problems (not sure if it is compatible with `v2.3`) either. 😢

I need to test it before I can guarantee that everything works, so I suggest that this PR does not take any changes other than `ui/app/src/components/NewExperimentNext/data/types.ts` for now.

**Comment by g1eny0ung** [comment]
I will update the CI to check if the OpenAPI changes need to be synced to the API clients and forms in the UI.

**Comment by YangKeao** [comment]
> It looks like for a long time the PhysicalMachineChaos weren't syncing the OpenAPI after the changes, so it's better to fix that with the new PR since I'm not sure if it's causing problems (not sure if it is compatible with v2.3) either. cry
> I need to test it before I can guarantee that everything works, so I suggest that this PR does not take any changes other than ui/app/src/components/NewExperimentNext/data/types.ts for now.

Good! I reset these files. I wonder whether I need to generate files for `BlockChaos`? (I'll need to add a `"blockchaos"` in a variable, and then it can be generated).

**Comment by g1eny0ung** [comment]
> > It looks like for a long time the PhysicalMachineChaos weren't syncing the OpenAPI after the changes, so it's better to fix that with the new PR since I'm not sure if it's causing problems (not sure if it is compatible with v2.3) either. cry
> > I need to test it before I can guarantee that everything works, so I suggest that this PR does not take any changes other than ui/app/src/components/NewExperimentNext/data/types.ts for now.
> 
> Good! I reset these files. I wonder whether I need to generate files for `BlockChaos`? (I'll need to add a `"blockchaos"` in a variable, and then it can be generated).

@YangKeao After I check PhysicalMachineChaos it will be ready, I will do this change this afternoon and I will let you know when it is done.

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by g1eny0ung** [comment]
> cherry pick to release-2.3 failed

Manually cherry-pick with #3658.

**Pull request merged**
