### PR TITLE
ui: update RBACGenerator's text

### LINKED ISSUE #3461: Chaos Dashboard: Generation ServiceAccount Token with TokenRequest API on kubernetes 1.24+
## Feature Request

**Is your feature request related to a problem? Please describe:**

Yes. Chaos Dashboard would give the hint to create a token to login:
image

But it would NOT work on Kubernetes 1.24+.

After https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token get finished, the secret which contains the token for serviceaccount would NOT be created automatically.

it requires an extra command like `kubectl create token <serviceaccount-name>`

image

**Describe the feature you'd like:**

Update the recommended commands provided by Chaos Dashboard, append `kubectl create token` with Kubernetes 1.24+

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by longfangsong**
### What problem does this PR solve?

Close #3461

### What's changed and how it works?

Just update the text.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [x] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.3
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

(Just open the panel and read the text.)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Review by Andrewmatilde — COMMENTED** [review]
PTAL @cwen0 , @STRRL , @g1eny0ung

**Comment by Andrewmatilde** [comment]
Plz update CHANGELOG . @longfangsong

**Review by STRRL — COMMENTED** [review]
Thanks for your contribution!

Please update the CHANGELOG.md :D

rest LGTM!

**Review by g1eny0ung — APPROVED** [review]
LGTM!

**Comment by cwen0** [comment]
@longfangsong Can you help to update docs? https://github.com/chaos-mesh/website/blob/master/docs/manage-user-permissions.md

**Pull request merged**
