### PR TITLE
remove remote build by moving file into a docker image

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <keao.yang@yahoo.com>

### What problem does this PR solve?

Originally, for compiling on remote docker, Chaos Mesh will build a docker image with files copied from current file. However, this image is recursive, which means history ones cannot be deleted and will reach storage threshold or layer count threshold.

This feature was implemented because Mac OS and minikube uses virtual machine to run docker on a remote machine, so `--volume` would fail to mount the current work directory. However, @STRRL  told me the Mac OS docker virtual machine mounts some folder into the virtual machine, and the minikube also provides some technology to mount directory (with `minikube mount` or start with `start --mount --mount-string "$(pwd):$(pwd)"` on docker driver).

So, it's not needed to load folders into the virtual machine now :smile_cat:. Everything becomes simpler. 

It would be really grateful if any developer using mac os could test for me.

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM

and more details about "File Sharing" docker are here if you have interests. https://docs.docker.com/docker-for-mac/#file-sharing

**Comment by cwen0** [comment]
> LGTM
> 
> and more details about "File Sharing" docker are here if you have interests. https://docs.docker.com/docker-for-mac/#file-sharing


Is there a requirement for Docker version for `File Sharing`?

**Comment by STRRL** [comment]
> > LGTM
> > and more details about "File Sharing" docker are here if you have interests. [docs.docker.com/docker-for-mac/#file-sharing](https://docs.docker.com/docker-for-mac/#file-sharing)
> 
> Is there a requirement for Docker version for `File Sharing`?

That feature has existed since the very old version in 2016.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
