### PR TITLE
Update helm doc

### PR DESCRIPTION
**Pull request by Gallardot**
### Check List

Tests

- Unit test
- E2E test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has Go code change
- Has CI related scripts change
- Has Terraform scripts change

Side effects

- Breaking backward compatibility

Related changes

- Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
@Gallardot Can we review this pr now. Seems it is still WIP

**Comment by Gallardot** [comment]
> @Gallardot Can we review this pr now. Seems it is still WIP

@zhouqiang-cl @cwen0 
Sorry for this PR. I'm a little confused about that. Do we need to sync this helm charts doc to [chaos mesh docs](https://chaos-mesh.org/docs/)? What is the relationship between [helm/chaos-mesh](https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh) and [charts](https://github.com/chaos-mesh/charts) ?

**Comment by cwen0** [comment]
> > @Gallardot Can we review this pr now. Seems it is still WIP
> 
> @zhouqiang-cl @cwen0
> Sorry for this PR. I'm a little confused about that. Do we need to sync this helm charts doc to [chaos mesh docs](https://chaos-mesh.org/docs/)? What is the relationship between [helm/chaos-mesh](https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh) and [charts](https://github.com/chaos-mesh/charts) ?

We don't need to do it.  When we add a chart tag like `chart-0.01`, the GitHub action will release a tar package to [charts](https://github.com/chaos-mesh/charts) repo.

**Pull request merged**
