### PR TITLE
codebase: Add static interface checks for the interface `InnerObject` (#2163)

### LINKED ISSUE #2163: codebase: static interface checks
## Feature Request

This issue will not introduce any NEW features or any changes to the current architecture. It's only about improving the style of codes, and let it be easier to understand Chaos Mesh's codes.

As [Effective Go/Interface checks](https://golang.org/doc/effective_go#blank_implements) introduced, we do not need to declare explicitly that one struct implements an interface. So that brings some trouble when reading the code: it's hard to find all the implementations of one interface, even you are working with modern IDE like goland.

For example: 

https://github.com/chaos-mesh/chaos-mesh/blob/1eb4025c68580e16045bba4273b07d50768feffc/controllers/common/controller.go#L44-L47

Here is an interface called `ChaosImpl`, and all of the chaos should implement this interface. If we could add one line of code here:

https://github.com/chaos-mesh/chaos-mesh/blob/1eb4025c68580e16045bba4273b07d50768feffc/controllers/chaosimpl/iochaos/impl.go#L40-L47

```go
var _ common.ChaosImpl = (*Impl)(nil)
```

to declare the implementation explicitly, will give huge help for understanding codes.

I will list several (not all) interfaces and their implements, which could be applied with "static interface checks", this list will keep growing if we find the same situation at new place.

- [x] interface `ChaosImpl` at controllers/common/controller.go https://github.com/chaos-mesh/chaos-mesh/pull/2224
  - struct `Delegate` at controllers/action/delegate.go
  - struct `Impl` at controllers/chaosimpl/awschaos/detachvolume/impl.go
  - struct `Impl` at controllers/chaosimpl/awschaos/ec2restart/impl.go
  - struct `Impl` at controllers/chaosimpl/awschaos/ec2stop/impl.go
  - struct `Impl` at controllers/chaosimpl/dnschaos/types.go
  - struct `Impl` at controllers/chaosimpl/gcpchaos/diskloss/impl.go
  - struct `Impl` at controllers/chaosimpl/gcpchaos/nodereset/impl.go
  - struct `Impl` at controllers/chaosimpl/gcpchaos/nodestop/impl.go
  - struct `Impl` at controllers/chaosimpl/httpchaos/impl.go
  - struct `Impl` at controllers/chaosimpl/iochaos/impl.go
  - struct `Impl` at controllers/chaosimpl/jvmchaos/impl.go
  - struct `Impl` at controllers/chaosimpl/kernelchaos/types.go
  - struct `Impl` at controllers/chaosimpl/networkchaos/trafficcontrol/impl.go
  - struct `Impl` at controllers/chaosimpl/networkchaos/partition/impl.go
  - struct `Impl` at controllers/chaosimpl/podchaos/containerkill/impl.go
  - struct `Impl` at controllers/chaosimpl/podchaos/podfailure/impl.go
  - struct `Impl` at controllers/chaosimpl/podchaos/podkill/impl.go
  - struct `Impl` at controllers/chaosimpl/stresschaos/impl.go
  - struct `Impl` at controllers/chaosimpl/timechaos/impl.go
- [x] interface `InnerObjectWithCustomStatus`  at controllers/common/controller.go (refactor required: move this interface to api/v1alpha1) https://github.com/chaos-mesh/chaos-mesh/pull/2262
  - struct `GCPChaos` at api/v1alpha1/gcpchaos_types.go
  - struct `HTTPChaos` at api/v1alpha1/httpchaos_types.go
  - struct `IOChaos` at api/v1alpha1/iochaos_types.go
  - struct `NetworkChaos` at api/v1alpha1/networkchaos_types.go
  - struct `StressChaos` at api/v1alpha1/stresschaos_types.go
- [x] interface `InnerObjectWithSelector` at controllers/common/controller.go (refactor required: move this interface to api/v1alpha1)
  - struct `AWSChaos` at api/v1alpha1/awschaos_types.go
  - struct `DNSChaos` at api/v1alpha1/dnschaos_type.go
  - struct `GCPChaos` at api/v1alpha1/gcpchaos_types.go
  - struct `HTTPChaos` at api/v1alpha1/httpchaos_types.go
  - struct `IOChaos` at api/v1alpha1/iochaos_types.go
  - struct `JVMChaos` at api/v1alpha1/jvmchaos_types.go
  - struct `KernelChaos` at api/v1alpha1/kernelchaos_types.go
  - struct `NetworkChaos` at api/v1alpha1/networkchaos_types.go
  - struct `PodChaos` at api/v1alpha1/podchaos_types.go 
  - struct `StressChaos` at api/v1alpha1/stresschaos_types.go
  - struct `TimeChaos` at api/v1alpha1/timechaos_types.go
- [ ] interface `InnerObject` at api/v1alpha1/common_types.go
  - struct `AWSChaos` at api/v1alpha1/awschaos_types.go
  - struct `DNSChaos` at api/v1alpha1/dnschaos_type.go
  - struct `GCPChaos` at api/v1alpha1/gcpchaos_types.go
  - struct `HTTPChaos` at api/v1alpha1/httpchaos_types.go
  - struct `IOChaos` at api/v1alpha1/iochaos_types.go
  - struct `JVMChaos` at api/v1alpha1/jvmchaos_types.go
  - struct `KernelChaos` at api/v1alpha1/kernelchaos_types.go
  - struct `NetworkChaos` at api/v1alpha1/networkchaos_types.go
  - struct `PodChaos` at api/v1alpha1/podchaos_types.go 
  - struct `StressChaos` at api/v1alpha1/stresschaos_types.go
  - struct `TimeChaos` at api/v1alpha1/timechaos_types.go

### PR DESCRIPTION
**Pull request by PrayagS**
This commit adds explicit declarations of implementation for the
interface `InnerObject`

Signed-off-by: PrayagS <prayag.s@ahduni.edu.in>

### What problem does this PR solve?

Issue Number: close #2163

Problem Summary:
- Missing static interface checks for the interface `InnerObject`

What's Changed:
- Task 4 of #2163 is done.

### Related changes
- Added static interface checks for the interface `InnerObject` (#2163).

Tests

- [X] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by fewdan** [comment]
Hi!  @PrayagS
Thank you for your contribution.

**Comment by PrayagS** [comment]
@fewdan Your welcome! Glad to contribute and hoping to do more 🙂

**Comment by PrayagS** [comment]
Is there something wrong with the tests? Why has the e2e test not returned any results yet?

**Review by STRRL — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
