### PR TITLE
Ability to add Pod securityContext for controller-manager and dashboard

### LINKED ISSUE #3598: [Feature] securityContext for controller-manager and dashboard
## Feature Request

**Is your feature request related to a problem? Please describe:**
The helm installation fails with an error: "Error: container has runAsNonRoot and image will run as root"

**Describe the feature you'd like:**
The ability to set securityContext for controler-manager and dashboard will allow you to specify a specific user.

**Describe alternatives you've considered:**
I don't know any other.

**Teachability, Documentation, Adoption, Migration Strategy:**
Can be set:

```
dashboard:
  securityContext:
    runAsUser: 1001
```

### PR DESCRIPTION
**Pull request by alekczapski**
Signed-off-by: Aleksander Czapski <alekczapski@gmail.com>

### What problem does this PR solve?

This PR allows for configuring Pod securityContext for controller-manager and dashboard in Helm template (closes #3598
)
### What's changed and how it works?

A new controller.securityContext and dashboard.securityContext configuration option in values.yaml is used for controler-manager and dashboard securityContext field.
For more details refer to [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [X] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [X] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @alekczapski, thanks for your contribution!!!

There are several files that need updates. You could execute `make check` on your local machine, then commit the changes. :)

**Comment by alekczapski** [comment]
Hi @STRRL
the missing file has been updated :)

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
