### PR TITLE
removed docker registry mirror

### LINKED ISSUE #2294: `install.sh --docker-mirror` not work
## Bug Report

**What version of Kubernetes are you using?**
 

v1.7.2

**What version of Chaos Mesh are you using?**
 

v2.0.0

**What did you do?**
 

use `install.sh` to install chaos-mesh

**What did you expect to see?** 

Install chaos mesh successfully

**What did you see instead?** 

```
Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m55s                default-scheduler  Successfully assigned chaos-testing/chaos-controller-manager-55b9c58646-4s9v7 to minikube
  Normal   Pulling    82s (x4 over 2m54s)  kubelet            Pulling image "gcr.azk8s.cn/pingcap/chaos-mesh:v2.0.0"
  Warning  Failed     82s (x4 over 2m54s)  kubelet            Failed to pull image "gcr.azk8s.cn/pingcap/chaos-mesh:v2.0.0": rpc error: code = Unknown desc = Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
  Warning  Failed     82s (x4 over 2m54s)  kubelet            Error: ErrImagePull
  Normal   BackOff    68s (x6 over 2m54s)  kubelet            Back-off pulling image "gcr.azk8s.cn/pingcap/chaos-mesh:v2.0.0"
  Warning  Failed     56s (x7 over 2m54s)  kubelet            Error: ImagePullBackOff
```

**Output of chaosctl**

### LINKED ISSUE #2740: remove china mainland docker registry mirror in `install.sh`
## Feature Request

Request:

Remove `docker_mirror` feature and related codes in `install.sh`. 

Reason:
- `dockerhub.azk8s.cn`( also `gcr.azk8s.cn` and `quay.azk8s.cn`) could not access with public network anymore, related issue #2294
- After release-2.1, we moved docker images from dockerhub to ghcr.io, there are no other docker registry mirror(s) supporting `ghcr.io` in china mainland right now.

### PR DESCRIPTION
**Pull request by rksharma95**
### What problem does this PR solve?

Close #2294
Close #2740

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by YangKeao** [comment]
@rksharma95 Please sign off the commit according to [DCO instruction](https://github.com/chaos-mesh/chaos-mesh/pull/2797/checks?check_run_id=4842123784)

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by g1eny0ung — CHANGES_REQUESTED** [review]
Hi, @rksharma95, thx for your contribution. ❤️ There still has a little extra work, after the `--docker-mirror` flag is removed, the `azk8spull` function needs to be removed too.

**Comment by g1eny0ung** [comment]
@STRRL Shall this PR needs to cherry-pick each branch?

**Comment by STRRL** [comment]
> @STRRL Shall this PR needs to cherry-pick each branch?

Yes, I would append tag for this PR.

**Comment by STRRL** [comment]
Hi @rksharma95, could you append a description of this PR in CHANGELOG.md?

**Comment by rksharma95** [comment]
> Hi @rksharma95, could you append a description of this PR in CHANGELOG.md?

**Comment by rksharma95** [comment]
> Hi @rksharma95, could you append a description of this PR in CHANGELOG.md?

ya sure i on it, i accidentally closed the PR :pensive:

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by iguoyr** [comment]
@rksharma95 Hi, could you fix `DCO` check first? It seems CI is blocked :)

**Comment by STRRL** [comment]
Hi @rksharma95 , thanks for your contribution! As you enabled "Allow edits and access to secrets by maintainers", I have helped you to clean up the commits that block the tide and DCO checks.

**Review by STRRL — APPROVED** [review]

**Pull request merged**
