### PR TITLE
feat: switch views between k8s and hosts nodes

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What's changed and how it works?

Add tabs to switch views between k8s and hosts nodes:

image

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.4
  - [ ] release-2.3

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@STRRL I've also updated the changelog, adding `v2.5.0` release notes.

**Comment by STRRL** [comment]
> @STRRL I've also updated the changelog, adding `v2.5.0` release notes.

I prefer to make these changes in another PR...

**Comment by g1eny0ung** [comment]
@STRRL #3834.

**Comment by g1eny0ung** [comment]
I will merge this PR to continue the subsequent development. Feel free to comment below in the future if there have any problems.

**Pull request merged**
