### PR TITLE
fix: unhandled empty value in LabelField

### PR DESCRIPTION
**Pull request by shaowenchen**
Signed-off-by: shaowenchen <mail@chenshaowen.com>

### What problem does this PR solve?

Resolve https://github.com/chaos-mesh/chaos-mesh/issues/1467.

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Good catch! But I think it's better to check first, like:

```js
const t = text.trim()

// Here
if (t === '') {
  return
}

if (isKV && !/^.+:.+$/.test(t)) {
  setError('Invalid key:value format')

  return
}
```

**Comment by shaowenchen** [comment]
> Good catch! But I think it's better to check first, like:
> 
> ```js
> const t = text.trim()
> 
> // Here
> if (t === '') {
>   return
> }
> 
> if (isKV && !/^.+:.+$/.test(t)) {
>   setError('Invalid key:value format')
> 
>   return
> }
> ```

Adopted

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
