### PR TITLE
Promote "Chenxi Li" to committer

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: Cwen Yin <cwenyin0@gmail.com>

In accordance with our [Governance](https://github.com/chaos-mesh/chaos-mesh/blob/master/GOVERNANCE.md#committer), I am pleased to promote @Hexilee  as a new committer. I would like to hereby thank him for his great contributions to the project and look forward to seeing more of his growth and engagements.

## What does becoming a Chaos Mesh Committer mean to you? 

Chaos Mesh is the first full-time project for me, and I learn how open source communities work and govern from it, which affects my values of open source greatly. I have contributed to Chaos Mesh for more than one year and it provides me a stage to communicate with users and developers in the world, I believe this project will benefit my whole career.  Becoming a Chaos Mesh Committer is not only a recognition for my contributions, but also a passion for me to design and decide the future of Chaos Mesh project. 

## Contribution Highlights

* Improve performance and code base for IOChaos [toda#1](https://github.com/chaos-mesh/toda/pull/1), [toda#2](https://github.com/chaos-mesh/toda/pull/2), [toda#3](https://github.com/chaos-mesh/toda/pull/3), [toda#4](https://github.com/chaos-mesh/toda/pull/4)
* Implement HTTPChaos in Chaos Mesh [#1706](https://github.com/chaos-mesh/chaos-mesh/pull/1706), [#1858](https://github.com/chaos-mesh/chaos-mesh/pull/1858)
* Migrate code base from v1.2 to v2.0 [#1841](https://github.com/chaos-mesh/chaos-mesh/pull/1841), [#1901](https://github.com/chaos-mesh/chaos-mesh/pull/1901)
* Design and implement the new chaosctl [#2192](https://github.com/chaos-mesh/chaos-mesh/pull/2192), [#2459](https://github.com/chaos-mesh/chaos-mesh/pull/2459), [#2950](https://github.com/chaos-mesh/chaos-mesh/pull/2950), [#2992](https://github.com/chaos-mesh/chaos-mesh/pull/2992), [#3056](https://github.com/chaos-mesh/chaos-mesh/pull/3056)
* Improve the stability of chaos-daemon [#2668](https://github.com/chaos-mesh/chaos-mesh/pull/2668), [#2673](https://github.com/chaos-mesh/chaos-mesh/pull/2673), [#2918](https://github.com/chaos-mesh/chaos-mesh/pull/2918), [#3312](https://github.com/chaos-mesh/chaos-mesh/pull/3312)
* Improve interactivity and implement kafka attack in chaosd [chaosd#139](https://github.com/chaos-mesh/chaosd/pull/139), [chaosd#154](https://github.com/chaos-mesh/chaosd/pull/154), [chaosd#181](https://github.com/chaos-mesh/chaosd/pull/181)

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by STRRL** [comment]
LGTM! Congratulations! 🎉🎉🎉

**Review by g1eny0ung — APPROVED** [review]
LGTM! 🍻

**Review by dcalvin — APPROVED** [review]

**Comment by dcalvin** [comment]
LGTM. Congratulations!🎉

**Pull request merged**
