### PR TITLE
Fix networkchaos/iochaos recover slow (#1215)

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

Cherry pick #1215 to `release-1.0`

### CODE REVIEW

**Comment by STRRL** [comment]
e2e tests failed by "docker pull rate limit", should we cherry-pick #1205 to release-1.0?

**Comment by YangKeao** [comment]
> e2e tests failed by "docker pull rate limit", should we cherry-pick #1205 to release-1.0?

Good suggestion

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
