### PR TITLE
Webhook refactor

### PR DESCRIPTION
**Pull request by AsterNighT**
### What is changed and how does it work?
Move validators down to spec rather than chaos itself. So that schedule could reuse them. 
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by STRRL** [comment]
I think this PR relates to the validation of `Schedule,` so I append this PR into milestone "Release 2.0 Beta"

**Comment by AsterNighT** [comment]
> I think this PR relates to the validation of `Schedule,` so I append this PR into milestone "Release 2.0 Beta"

Is there anything that I could use to validate a workflow spec?

**Comment by STRRL** [comment]
> > I think this PR relates to the validation of `Schedule,` so I append this PR into milestone "Release 2.0 Beta"
> 
> Is there anything that I could use to validate a workflow spec?

Thanks！

I wonder that if we could embed `EmbedChaos` into `ScheduleItem`, and build the validation methods for `EmbedChaos`, many codes could be reused, like:

```go
type ScheduleItem struct {
	EmbedChaos `json:",inline"` 
	// +optional
	Workflow *WorkflowSpec `json:"workflow,omitempty"`
}
```

**Comment by AsterNighT** [comment]
> > > I think this PR relates to the validation of `Schedule,` so I append this PR into milestone "Release 2.0 Beta"
> > 
> > 
> > Is there anything that I could use to validate a workflow spec?
> 
> Thanks！
> 
> I wonder that if we could embed `EmbedChaos` into `ScheduleItem`, and build the validation methods for `EmbedChaos`, many codes could be reused, like:
> 
> ```go
> type ScheduleItem struct {
> 	EmbedChaos `json:",inline"` 
> 	// +optional
> 	Workflow *WorkflowSpec `json:"workflow,omitempty"`
> }
> ```

Great idea. I'll take a look. But still, that does not validate workflow.

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
