### PR TITLE
chore: use github token to avoid GitHub API Rate Limiting with e2e tests

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Avoiding failure caused by GitHub API Rate Limiting like https://github.com/chaos-mesh/chaos-mesh/runs/5781739841?check_suite_focus=true

`actions-setup-minikube` provides parameter `github token`: https://github.com/manusa/actions-setup-minikube#optional-input-parameters

### What's changed and how it works?

- append one more parameter `github token`

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by fewdan — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]

**Comment by STRRL** [comment]
> cherry pick to release-2.1 failed

I would manually cherry-pick to release-2.1

**Comment by STRRL** [comment]
> > cherry pick to release-2.1 failed
> 
> I would manually cherry-pick to release-2.1

carried with https://github.com/chaos-mesh/chaos-mesh/pull/3087

**Pull request merged**
