### PR TITLE
fix panic when cpu or memory stress start time is nil

### PR DESCRIPTION
**Pull request by xlgao-zju**
### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)
create cpu or memory stress experiment, and then delete them. chaos controller will not panic

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by iguoyr — APPROVED** [review]
LGTM

**Comment by xlgao-zju** [comment]
seems I can not re-trigger the test...

**Pull request merged**
