### PR TITLE
feat: token generator

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What is changed and how does it work?

Previous: #1480.

This PR adds a token generator that can help users to generate different tokens by choosing different namespaces and roles.

Other changes:

- Remove unused `id` property in `FormField`s
- Prevent `Predefined` component's YAML editor auto refreshed by wrapping `React.memo`
- Remove redundant `setAlertOpen`s

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

image

image

### CODE REVIEW

**Review by fewdan — DISMISSED** [review]
LGTM

**Review by STRRL — DISMISSED** [review]
LGTM

I saw that there are some code modifications that not relate to the token generator, please split them into another PR next time.😜

**Comment by g1eny0ung** [comment]
> LGTM
> 
> I saw that there are some code modifications that not relate to the token generator, please split them into another PR next time.😜

Got it!

**Review by STRRL — APPROVED** [review]

**Review by fewdan — APPROVED** [review]

**Pull request merged**
