### PR TITLE
(bugbash) Fixes gosimple warnings

### PR DESCRIPTION
**Pull request by rajaSahil**
### What problem does this PR solve?

- Fixes gosimple warnings.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]

**Review by STRRL — DISMISSED** [review]
CI failed, please format that file: controllers/gcpchaos/diskloss/types.go

**Review by AsterNighT — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
