### PR TITLE
fix(workflow): no more event after accomplished

### LINKED ISSUE #2901: workflows: endless events
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.3", GitCommit:"01849e73f3c86211f05533c2e807736e776fcf29", GitTreeState:"clean", BuildDate:"2021-02-17T12:35:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
Controller manager Version: version.Info{GitVersion:"v2.1.2", GitCommit:"24a1f565ed000ba8738a4ed568b4e9a0925fe2fb", BuildDate:"2021-12-29T11:43:40Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Create a workflow

```
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: sleep
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 10s
      children:
        - sleep
    - name: sleep
      templateType: Suspend
      deadline: 10s
```

**What did you expect to see?**

After the workflow is accomplished, no more event can be generated.

**What did you see instead?**

Events still generate everyday, about 8-12 events per day.

```
sleep - workflow accomplished
entry-m6wrm - node accomplished
sleep - workflow accomplished
entry-m6wrm - node accomplished
[...]
```

**Output of chaosctl**

N

### PR DESCRIPTION
**Pull request by imlonghao**
Signed-off-by: imlonghao <git@imlonghao.com>

### What problem does this PR solve?

close #2901

### What's changed and how it works?

It checks whether this node is already accomplished before
emit new events.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [x] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

I didn't test it yet, looks should work.

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Comment by STRRL** [comment]
Hi @imlonghao , could you append a line of description in the CHANGELOG.md? Thanks a lot!

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
