### PR TITLE
chore(makefile): build e2e thing on local host

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

This is a part of https://github.com/chaos-mesh/chaos-mesh/issues/1187.

This PR could let developers deploy the latest modified codes and testcases on any kubernetes cluster. And it requires a docker registry which is available by both kubernetes cluster and the compling-machine.

- remove the compatibility with helm v2, as we have done the https://github.com/chaos-mesh/chaos-mesh/pull/1575
- `make prepare-install install` could deploy your local codes to any kubernetes cluster
- `make prepare-e2e e2e` could run e2e test on your local machine, attach test cases on any kubernetes cluster

### What is changed and how does it work?

- move `test/image/e2e/bin/ginkgo` and `test/image/e2e/bin/e2e.test` out of the `BUILD_IN_DOCKER_TEMPLATE`, build it on the local machine(not docker)
- new recipe `prepare-install`, it will build all the chaos-mesh required docker images, and push it to the `DOCKER_REGISTRY`
- modify recipe `install`, drop the support with helm v2, 
- modify recipe `install`, use `helm upgrade --install` instead of `helm install`, it could let users run `make install` more than once. 
- new recipe `prepare-e2e`, mostly like `prepare-install`, it will build all the e2e test required docker images, and push it to the `DOCKER_REGISTRY`
- modify recipe `e2e`, add specify the images of `e2e-helper`, and could pass through flags to `ginkgo`, like `-p --nodes=6` means run test cases parallelly within 6 nodes.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```
Signed-off-by: STRRL <str_ruiling@outlook.com>

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @YangKeao 
/cc @Hexilee

**Comment by Hexilee** [comment]
LGTM, it will improve our development experience!

**Review by Hexilee — APPROVED** [review]

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
