### PR TITLE
docs: generate api reference

### LINKED ISSUE #2513: generate api reference document from code and comments
Chaos Mesh needs something similar with https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

close #2513

image

Generate an api reference.

It uses the [crd-ref-docs](https://github.com/elastic/crd-ref-docs) and `asciidoctor` to generate the web page. The kubernetes api reference generator seems cannot be used in CRD.

I haven't decided whether it's a good place to write the api reference html page.

### CODE REVIEW

**Comment by STRRL** [comment]
I prefer to use a GitHub Action CI and publish the rendered HTML somewhere. Cloudflare? aws s3? How do you think about it? @g1eny0ung @cwen0

**Comment by g1eny0ung** [comment]
> I prefer to use a GitHub Action CI and publish the rendered HTML somewhere. GitHub Pages (in another repo)? Cloudflare? aws s3? How do you think about it? @g1eny0ung @cwen0

We can deploy it to our Netlify. Netlify is very easier to integrate with GitHub Action and is already available.

**Comment by YangKeao** [comment]
> > I prefer to use a GitHub Action CI and publish the rendered HTML somewhere. GitHub Pages (in another repo)? Cloudflare? aws s3? How do you think about it? @g1eny0ung @cwen0
> 
> We can deploy it to our Netlify. Netlify is very easier to integrate with GitHub Action and is already available.

Does netlify support to deploy documents of different branch into different sub-path? For example, the `api-reference.chaos-mesh.org/master` and `api-reference.chaos-mesh.org/release-1.2.2`. I haven't found a way to do it. It seems that they have to have different domains.

**Comment by g1eny0ung** [comment]
> > > I prefer to use a GitHub Action CI and publish the rendered HTML somewhere. GitHub Pages (in another repo)? Cloudflare? aws s3? How do you think about it? @g1eny0ung @cwen0
> > 
> > 
> > We can deploy it to our Netlify. Netlify is very easier to integrate with GitHub Action and is already available.
> 
> Does netlify support to deploy documents of different branch into different sub-path? For example, the `api-reference.chaos-mesh.org/master` and `api-reference.chaos-mesh.org/release-1.2.2`. I haven't found a way to do it. It seems that they have to have different domains.

@YangKeao AFAIK, no. They can only be published with different subdomains. But we can use proxies to achieve this: https://docs.netlify.com/routing/redirects/rewrites-proxies/.

**Comment by STRRL** [comment]
> netlify

Could we still use `chaos-mesh.org` for both documentation and this API Reference on Netlify? Or we need to use another domain? (I just found that `chaos-mesh.dev` is available :D

**Comment by STRRL** [comment]
> > @YangKeao AFAIK, no. They can only be published with different subdomains. But we can use proxies to achieve this: docs.netlify.com/routing/redirects/rewrites-proxies.
> 
> @g1eny0ung Could we still use `chaos-mesh.org` for both documentation and this API Reference on Netlify? Or we need to use another domain? (I just found that `chaos-mesh.dev` is available :D

Hi @YangKeao @g1eny0ung, as this pr had been stucked for a while, I built a static website with keao's codes: https://chaos-mesh.dev/reference/ . : P

**Pull request closed without merging**
