### PR TITLE
Use the chaos-mesh Helm repository

### PR DESCRIPTION
**Pull request by wstrm**
### What problem does this PR solve?
The command provided in the instructions results in:

```bash
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock

Error: failed to download "helm/chaos-mesh" (hint: running `helm repo update` may help)
```

### What is changed and how does it work?
Changing it to:

```bash
helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock

NAME: chaos-mesh
LAST DEPLOYED: Fri Oct 16 09:51:37 2020
NAMESPACE: chaos-testing
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Make sure chaos-mesh components are running
   kubectl get pods --namespace chaos-testing -l app.kubernetes.io/instance=chaos-mesh
```

Solves the issue.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by cwen0** [comment]
@wstrm Thanks for your contribution!

**Review by cwen0 — DISMISSED** [review]

**Comment by zhouqiang-cl** [comment]
Do we also need to update master/v0.9.1's document? @cwen0

**Comment by cwen0** [comment]
@zhouqiang-cl Yes, we need to do it, @wstrm Can you help us to update it?

**Comment by wstrm** [comment]
> @wstrm Can you help us to update it?

Ah, yes I'll fix that. :+1:

**Comment by wstrm** [comment]
Done, ready for review again. :)

**Review by fewdan — DISMISSED** [review]
LGTM

**Comment by cwen0** [comment]
@wstrm Can you help to update this file https://github.com/chaos-mesh/chaos-mesh/blob/master/website/docs/get_started/installation.md#step-3-install-chaos-mesh? Thanks!

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by zhouqiang-cl** [comment]
LGTM

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
