### PR TITLE
update go-protoc version to 1.3.0

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>### What problem does this PR solve?

The current go-protoc version is too old and deprecated.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by fewdan** [comment]
It seems that CI failed. Maybe you should make some changes? @Hexilee

**Comment by Hexilee** [comment]
> It seems that CI failed. Maybe you should make some changes? @Hexilee

It seems we should upgrade k8s as it depends on etcd which depends on grpc.

**Comment by Hexilee** [comment]
> It seems that CI failed. Maybe you should make some changes? @Hexilee

Resolved

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
