### PR TITLE
Replaced all chaos-testing namespace tags with chaos-mesh

### PR DESCRIPTION
**Pull request by dmallya**
Signed-off-by: dmallya <mallya.dushyant@gmail.com>

### What problem does this PR solve?

Resolves the issues that the ``chaos-testing`` namespace might create which assumes Chaos Mesh is installed.

Close https://github.com/chaos-mesh/chaos-mesh/issues/2818

### What's changed and how it works?

Replaced all namespaces and references of ``chaos-testing`` with ``chaos-mesh``.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @dmallya , sorry for the late response! 

Here is another file that requires updates about namespace: `.github/workflows/integration_test.yml`, PTAL.

**Comment by STRRL** [comment]
Hi @dmallya , could you update this PR?

**Comment by dmallya** [comment]
My Apologies, I have been terribly busy, I'll update it within the next 24h.

**Comment by dmallya** [comment]
Hmm the ``verify`` stage fails, not sure what happened here I cant quite seem to understand, did the auto merge mess with the files or is have to do with the modifications I made? I just manually updated the contents of the action.go file with the newest version of the file from the master branch.

**Comment by dmallya** [comment]
> > Hmm the `verify` stage fails, not sure what happened here I cant quite seem to understand, did the auto merge mess with the files or is have to do with the modifications I made? I just manually updated the contents of the action.go file with the newest version of the file from the master branch.
> 
> `verify` relates to some code linter and code generation. You could run `make check` on your local machine then commit the changes to fix that.

Alright, I'll do that and commit when I can.

**Comment by STRRL** [comment]
> > > Hmm the `verify` stage fails, not sure what happened here I cant quite seem to understand, did the auto merge mess with the files or is have to do with the modifications I made? I just manually updated the contents of the action.go file with the newest version of the file from the master branch.
> > 
> > 
> > `verify` relates to some code linter and code generation. You could run `make check` on your local machine then commit the changes to fix that.
> 
> Alright, I'll do that and commit when I can.

Hi @dmallya, are you still interested in this PR? Do you need our help? ❤️

**Comment by STRRL** [comment]
I am going to close this PR because of the inactivity.

Feel free to reopen this PR if you would like to work on it.

**Pull request closed without merging**
