### PR TITLE
fix "sidecar config" e2e test cases run failed in some scenario

### PR DESCRIPTION
**Pull request by zhengbingxian**
Signed-off-by: zhengbingxian <zhengbingxian@archeros.com>

### What problem does this PR solve?
https://github.com/chaos-mesh/chaos-mesh/issues/3563

### What's changed and how it works?

Add judgment to check newPod.items' length,  so that it will not cause "runtime error: index out of range [0] with length 0"

### Related changes

- [ ] This change also requires further upadtes to `chaos-mesh/website` (e.g. docs)
- [ ] This change also requires further updates to `UI interface`
- Need to **cheery-pick to release branches**
  - [x] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!!!!

**Pull request merged**
