### PR TITLE
Fix clusterrole name in DNS server

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Fix the cluster role name for DNS server 

### What's changed and how it works?
Use the correct cluster role name

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by iguoyr — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
I notice that the service account  `{{ .Values.dnsServer.serviceAccount }}` (which binded with ClusterRole `{{ .Release.Name }}-chaos-dns-server-target-namespace`) actually has no usage.

It seems that we could purge the `dns-rbac.yaml`.

/cc @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
> I notice that the service account `{{ .Values.dnsServer.serviceAccount }}` (which binded with ClusterRole `{{ .Release.Name }}-chaos-dns-server-target-namespace`) actually has no usage.
> 
> It seems that we could purge the `dns-rbac.yaml`.
> 
> /cc @WangXiangUSTC

It is used here https://github.com/chaos-mesh/chaos-mesh/blob/59cfaba0e27a9b798a64fe1e99c5fc98ffbd887d/helm/chaos-mesh/templates/dns-deployment.yaml#L47
But I fill it with a static value by mistake, need to update it with `{{ .Values.dnsServer.serviceAccount }}` 😅

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
