### PR TITLE
version unrealated manifests

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

close https://github.com/chaos-mesh/chaos-mesh/issues/3292

After this PR merged, we would not be required to update versions `Chart.yaml` and `install.sh` anymore.

### What's changed and how it works?

- update `upload_release_files.yml` and `release_helm_chart.yml`
  - make sure that it must triggered by push event  with certain tag
  - extract the version from tag
  - replace version when publish the artifacts
- update `install.sh`, make it easier to replace with certain version

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```
Signed-off-by: STRRL <im@strrl.dev>

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @Hexilee @YangKeao

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by Hexilee — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
also waiting https://github.com/chaos-mesh/chaos-mesh/pull/3305

**Pull request merged**
