### PR TITLE
use ContainerSelector in kernel chaos

### PR DESCRIPTION
**Pull request by xlgao-zju**
### What problem does this PR solve?
close https://github.com/chaos-mesh/chaos-mesh/issues/3157

### What's changed and how it works?

since KernelChaos is a container level chaos, so use `ContainerSelector` in kernel chaos instead of `PodSelector`.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by xlgao-zju** [comment]
cc @STRRL @Hexilee

**Comment by xlgao-zju** [comment]
image
looks like this link has broken, do we need to remove it?

**Comment by Hexilee** [comment]
> image
> 
> looks like this link has broken, do we need to remove it?

Please wait for https://github.com/chaos-mesh/chaos-mesh/pull/3401

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
