### PR TITLE
Rename validate-auth as chaos-mesh-validate-auth

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?
As `validate-auth` is quite common. Let's use `chaos-mesh-validate-auth` to avoid confusion and conflicts.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
> /label "no-need-update-changelog"

It seems there are misconfigurations on our bot, I would figure it out later. 🤔

**Comment by STRRL** [comment]
As the restriction of GitHub Action, it requires a new commit to retrigger the Check with new labels. You could use `git commit --amend --no-edit` then `git push -f` to retrigger it.

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
And there should be one place that needs to update the website: https://chaos-mesh.org/docs/uninstallation/#step-5-remove-webhook. Here records the name of webhooks that requires updates.

Would you like to help us to update it? ❤️

**Comment by STRRL** [comment]
close https://github.com/chaos-mesh/chaos-mesh/issues/2412

**Comment by anuragpaliwal80** [comment]
> 

Sure, I will open a different PR to update the details.

**Comment by anuragpaliwal80** [comment]
Opedn https://github.com/chaos-mesh/chaos-mesh/pull/3193 closing this one

**Pull request closed without merging**
