### PR TITLE
Fix ContianerRecordDecoder typo

### PR DESCRIPTION
**Pull request by mingleiw**
### What problem does this PR solve?

> Problem Summary: Container had been misspelt as “Contianer”"

### What's changed and how it works?

> What's Changed: Fix the typo and update all the references

### Related changes

- [x] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
Thanks! LGTM

**Comment by mingleiw** [comment]
@WangXiangUSTC thanks! the doc update pr is https://github.com/chaos-mesh/website/pull/167

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
