### PR TITLE
Fix few error checks

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Fix few error checks

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
There is a similar PR# https://github.com/chaos-mesh/chaos-mesh/pull/1791 but I checked that changes in this PR are not part of that one.

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by anuragpaliwal80** [comment]
@fewdan Can you please add `bugbash` tag to this PR? - thx

**Pull request merged**
