### PR TITLE
Replace ChaosInstance and ChaosList with GenericChaos and GenericChaosList

### PR DESCRIPTION
**Pull request by FingerLeader**
### What problem does this PR solve?
`ChaosInstance` and `ChaosList` are similar to `GenericChaos` and `GenericChaosList`, We can get all the data which ChaosInstance has from `metav1.Object`, so I combine them to reduce redundancy.
### What is changed and how it works?

What's Changed:
* `ChaosInstance` and `ChaosList` are removed
* `InnerObject` doesn't have method `GetChaos()` anymore, you can get data by using `InnerObject.GetXXX()` ranther than `InnerObject.GetChaos().XXX`
* `cmd/chaos-builder/test.go` doesn't generate `TestXXXGetChaos()` anymore

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
PTAL

/cc @YangKeao 
/cc @Hexilee 
/cc @cwen0

**Comment by Hexilee** [comment]
LGTM

**Review by Hexilee — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
