### PR TITLE
chore: resolve error with utils pakcage

### LINKED ISSUE #2537: Unexpected successful Workflow creation with incorrect content
## Bug Report

**What version of Kubernetes are you using?**

No relation with kubernetes version

**What version of Chaos Mesh are you using?**

Master branch, but it also affected `release-2.0`

**What did you do?**

- Create a workflow on dashboard, filling `10ms` for NetworkChaos, action `Loss`, in field `Loss`. It is the invalid value for `Loss`.
- Create/Submit this workflow.

**What did you expect to see?**
- Dashboard should notice me that creating failed, because of the invalid value.

**What did you see instead?**
- Dashboard show me that creating succeed, but `chaos-dashboard` print `invalid values` (by webhook) in its logs.
-  The invalid workflow is not created actually, aborted with kubernetes validation webhook.
- `chaos-dashboard` response 200(should be 500 or 400), which is unexpected. 

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Close #2537

> Problem Summary:

- did not resolve errors from kubernetes client properly

### What's changed and how it works?

> What's Changed:

- use `utils.SetAPIMachinaryError` instead or `c.Error`

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Review by g1eny0ung — APPROVED** [review]
LGTM 🍺

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> cherry pick to release-2.0 failed
@STRRL PTAL

**Comment by g1eny0ung** [comment]
This doesn't require a cherry-pick to 2.0 because the 2.0 API hasn't been refactored.

**Pull request merged**
