### PR TITLE
feat: remove token when get Unauthorized

### LINKED ISSUE #4170: Automatically logout from dashboard when token expired
## Feature Request

I found out that RBAC tokens will expire after one and after that dashboard shows  `error.api.internal_server_error: Unauthorized` error message but doesn't remove the previous token and you should go remove it manually. 

I think this process can be done automatically.

### PR DESCRIPTION
**Pull request by jamshidi799**
## What problem does this PR solve?

When the token expires, the dashboard will need you to manually delete the token from the settings section and log out. This PR deletes the token automatically when a 500 response code which includes Unauthorized text happens. After that, the dashboard will redirect to /#/dashboard path and it will show the Auth dialog.

Moreover, when I try to remove the token from the settings page, I face the below error which fixed by this PR.

Screenshot 2023-09-13 at 1 55 25 AM

Close #4170

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
> Moreover, when I try to remove the token from the settings page, I face the below error which fixed by this PR.
>
> Screenshot 2023-09-13 at 1 55 25 AM

I updated the code to fix the problem, which still occurs if the token is not set.

**Comment by g1eny0ung** [comment]
/lgtm

I also fixed a problem where the auth interceptor needed to be reset before clearing the token. Other changes are LGTM. Thank you for the contribution, @jamshidi799!

**Comment by jamshidi799** [comment]
> /lgtm
> 
> I also fixed a problem where the auth interceptor needed to be reset before clearing the token. Other changes are LGTM. Thank you for the contribution, @jamshidi799!

Your welcome, Thank you for the review.

**Pull request merged**
