### PR TITLE
bump version to 2.2.2

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

Bump version to 2.2.1

### Release Note

Here is the draft of release note:

# v2.2.2 Release Notes

This release introduces one bug fix for Chaos Mesh.

## Changed

- Bump chaos-tproxy to v0.5.1 [#3426](https://github.com/chaos-mesh/chaos-mesh/pull/3426)
- Run build image ci on self-hosted machine [#3429](https://github.com/chaos-mesh/chaos-mesh/pull/3429)

### CODE REVIEW

**Review by Hexilee — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Don't be urgent. I think this PR should be merged after https://github.com/chaos-mesh/chaos-mesh/pull/3429

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by Andrewmatilde — COMMENTED** [review]
LGTM

**Pull request merged**
