### PR TITLE
Remove not used Clientset in cmd/chaos-controller-manager/main.go

### LINKED ISSUE #3331: refactor: remove not used `Clientset *kubernetes.Clientset`
refer: 

https://github.com/chaos-mesh/chaos-mesh/blob/bb58c2efcf69421cf332947c051fa6e336ab4990/cmd/chaos-controller-manager/main.go#L106-L108

I think we could remove it directly and safely.

### PR DESCRIPTION
**Pull request by z1cheng**
Signed-off-by: z1cheng <imchench@gmail.com>

### What problem does this PR solve?

Close #3331 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Welcome @z1cheng ! Thanks for your contribution!

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
