### PR TITLE
fix: can't set to immediate job

### LINKED ISSUE #1225: chaos-dashboard: Can not create "Run immediately" Chaos
## Bug Report

**What version of Kubernetes are you using?**

```
❯ minikube version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

chaos-mesh/chaos-mesh master branch, c7a7d15

I guess: chaos-dashboard ignore the "Run immediately" switcher.

**What did you do?**

- deploy chaos-mesh with helm, enable dashboard
- create a NetworkChaos, fill other unimportant specs
- switch "Run immediately" on, then click SUBMIT
image

**What did you expect to see?**
Chaos create succeed.

**What did you see instead?**
Nothing happened. No notice, no popup, console no log.

**Following-up story**

And I switch off "Run immediately", I found validator warn on "cron" and "schedule".
image

Then I fill "cron" and "schedule", but switch on "Run immediately" again, chaos created succeed; BUT it still hold a "cron" and "schedule".

Operation:

Result:
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: just-another-delay
  namespace: default
  labels: null
  annotations: null
spec:
  action: partition
  mode: one
  value: ''
  selector:
    namespaces:
      - default
  duration: 8m # <= this is unexpected
  scheduler:
    cron: '@every 10m' # <= this is unexpected
  direction: to

```

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

Resolve #1225.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@g1eny0ung Do we need to cherry-pick this pr to 1.0 branch?

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
