### PR TITLE
add dashboard hostNetwork option in helm

### PR DESCRIPTION
**Pull request by fewdan**
Signed-off-by: “fewdan” <fewdan@hotmail.com>

### What problem does this PR solve?
add dashboard hostNetwork option in helm

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [x] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by yeya24 — APPROVED** [review]
The change LGTM. But what's the use case of running the dashboard in host network mode?

**Comment by STRRL** [comment]
> But what's the use case of running the dashboard in host network mode?

Same question for me.

**Comment by fewdan** [comment]
> > But what's the use case of running the dashboard in host network mode?
> 
> Same question for me.

@yeya24 @STRRL 
I encountered a situation yesterday. It may be a problem with the CNI configuration (flannel) of the user cluster, which caused the pod to fail to connect to the api-server. Changing to hostNetwork can temporarily solve this user's problem.

**Comment by STRRL** [comment]
That issue caused by the user's non-standard environment, and I think it's not necessary to change the default network mode. 🙈

**Comment by fewdan** [comment]
> That issue caused by the user's non-standard environment, and I think it's not necessary to change the default network mode. 🙈

Yes, so when installing through helm, the default network mode is still "hostNetwork:false".

**Review by STRRL — APPROVED** [review]

**Pull request merged**
