### PR TITLE
chore: remove unused codes

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Problem Summary:

- these codes are old and unused for workflow
- and we will not abstract new patterns for workflow anymore

so I think we could delete them.

### What is changed and how it works?

What's Changed:

- remove related code and makefile recipes

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL 

/cc @YangKeao 
/cc @Hexilee 
/cc @WangXiangUSTC

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
