### PR TITLE
force group imports

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: Yang Keao <keao.yang@yahoo.com>

Manually modifying the import groups are very frustrating, especially when some tools add import for you. Like in #1504 

### What problem does this PR solve?

I have tried to fork `goimports` and modify a little to forcely group imports into four groups:

1. standard libraries
2. third-party libraries
3. third-party libraries contain `k8s.io`
4. local libraries

But I haven't found a good way to `go get` binary from a fork repo :(

### CODE REVIEW

**Comment by STRRL** [comment]
How do you make this? I only see the result: the `imports` statements are re-formatted. 

Could you introduce the detail?

**Comment by YangKeao** [comment]
> How do you make this? I only see the result: the `imports` statements are re-formatted.
> 
> Could you introduce the detail?

https://github.com/YangKeao/tools/commit/0daaf08ee5cd7cc261de1340a545c34879506612

Do you have any idea on how to `go get` a binary from a forked repo :crying_cat_face: ?

**Comment by fewdan** [comment]
It seems that there will be a lot of conflicts. If you have to manually group imports every time, it is not a good solution.

**Comment by AsterNighT** [comment]
> > How do you make this? I only see the result: the `imports` statements are re-formatted.
> > Could you introduce the detail?
> 
> [YangKeao/tools@0daaf08](https://github.com/YangKeao/tools/commit/0daaf08ee5cd7cc261de1340a545c34879506612) @STRRL
> 
> Do you have any idea on how to `go get` a binary from a forked repo 😿 ?

What about simply cloning the repo and building it?

**Comment by STRRL** [comment]
It seems very complex to finish that, should we close this PR now?

**Pull request closed without merging**
