### PR TITLE
feat: enable chaos-controller-manager leader election

### LINKED ISSUE #1516: Controller-manager enables leader election
## Feature Request

**Describe the feature you'd like:**
 

Enable leader election and make controller-manager HA. 

**Describe alternatives you've considered:**
 

HA is important for most applications, including Chaos Mesh. We support setting `replicas: 1` on helm chart files, but we have not tested it., and we don't recommend users to enable it at present. I think we should test it and make it available. 

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by iguoyr**
### What problem does this PR solve?

Issue Number: close #1516 

Problem Summary: enable chaos-controller-manager leader election

### What is changed and how it works?

What's Changed:

### Related changes

* no

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by iguoyr** [comment]
The script test failed, because I modified the manifest yaml in `install.sh`. In other words, I set the default value of the environment variable `ENABLE_LEADER_ELECTION` to `true`, and the master branch already has this environment variable, but the code on the master branch cannot use this function properly.(BTW, I have already tested `install.sh` on my branch)

**Comment by iguoyr** [comment]
/cc @STRRL 
/cc @YangKeao 

PTAL

**Comment by WangXiangUSTC** [comment]
how about adding a simple test for it? for example, set `replicas: 2` when installing controller-manager, and kill one by random, and make sure can create experiment success.

**Comment by iguoyr** [comment]
@WangXiangUSTC I've thought about adding some e2e test cases, but I have a unsolved problem:
set `replicas:2` only works with `---install-chaos-mesh` flag, if user want to run e2e tests in their own cluster, we have no idea whether we need to execute test cases related to leader election or not.

BTW, I looked at the e2e tests for Kubernetes and I don't seem to find any test cases related to high availability, as well as, we are using the leader election feature provided by `controller-runtime` framework, I found the test for this feature(https://github.com/kubernetes-sigs/controller-runtime/pull/118/files), so I decided not to add e2e tests for now. If you have a better solution please let me know :)

**Comment by STRRL** [comment]
How about setting the `replica: 3` for controller-manager deployment in helm? ( Enable HA by default)

**Comment by iguoyr** [comment]
@STRRL This looks like a good idea, updated ;)

**Comment by iguoyr** [comment]
@STRRL @YangKeao @fewdan PTAL

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
