### PR TITLE
promote shivanshs9 as a new committer

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

In accordance with our Governance, I am pleased to apply to promote [shivanshs9](https://github.com/shivanshs9) as a new committer for Chaos Mesh. I would like to hereby thank him for his great contributions to the project and look forward to seeing more of his growth and engagements.

## Contribution Highlights

Mainly develop [chaosd](https://github.com/chaos-mesh/chaosd), which is a Chaos Engineering toolkit of Chaos Mesh.

- Support host attack(shutdown host) https://github.com/chaos-mesh/chaosd/pull/26
- Refactor the code to make it easier to develop a new chaos function https://github.com/chaos-mesh/chaosd/pull/31
- Enhance the server mode  https://github.com/chaos-mesh/chaosd/pull/31
- Implement Scheduling in server mode https://github.com/chaos-mesh/chaosd/pull/50
- Support ssl + client ssl authentication https://github.com/chaos-mesh/chaosd/pull/69 (In Review)

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@chaos-mesh/maintainers PTAL

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by dcalvin — APPROVED** [review]
LGTM. Congrats to @shivanshs9!

**Pull request merged**
