### PR TITLE
fix: dashboard panic while replacing query namespace with target namespace in namespace scoped mode

### LINKED ISSUE #4409: dashboard: panic in namespace scoped mode with specific targetNamespace
## Bug Report

stack trace:
```
2024-04-30T06:55:26.561Z        DPANIC  experiments     experiment/experiment.go:113    odd number of arguments passed as key-value pairs for logging   {"ignored key": "some-namespace-name"}
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/apiserver/experiment.(*Service).list
        /home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/apiserver/experiment/experiment.go:113
github.com/gin-gonic/gin.(*Context).Next
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2947
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1991
[GIN] 2024/04/30 - 06:55:26 | 500 |     258.594µs |       127.0.0.1 | GET      "/api/experiments"
```

**What version of Kubernetes are you using?**

client: Major:"1", Minor:"22", GitVersion:"v1.22.2"
server: Major:"1", Minor:"22+", GitVersion:"v1.22.5"

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"chart-2.6.3", GitCommit:"b159d1c5a361ca350ca7789c9eb7fc917479db39", BuildDate:"2024-01-23T15:04:53Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**

reproducible cmd:
`helm install chaos-mesh chaos-mesh/chaos-mesh --set clusterScoped=false --set controllerManager.targetNamespace="my-namespace"`

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by monitor1379**
## What problem does this PR solve?

fix #4409 

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by monitor1379** [comment]
Integration Tests failed on downloading python package in stage "Install localstack && aws client". 

@STRRL Could you please take a look or re-run integration tests?  Thanks~


```
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: urllib3, six, PyYAML, pyasn1, jmespath, docutils, colorama, rsa, python-dateutil, botocore, s3transfer, awscli
Successfully installed PyYAML-6.0.1 awscli-1.32.94 botocore-1.34.94 colorama-0.4.6 docutils-0.16 jmespath-1.0.1 pyasn1-0.6.0 python-dateutil-2.9.0.post0 rsa-4.7.2 s3transfer-0.10.1 six-1.16.0 urllib3-2.2.1
error: timed out waiting for the condition on pods/localstack-5bf996bf57-w6hx6
Error: Process completed with exit code 1.
```

**Comment by monitor1379** [comment]
Could you please ask other maintainers to take a look at my PR? thanks!
@STRRL @YangKeao @g1eny0ung

**Comment by monitor1379** [comment]
any updates?

> Could you please ask other maintainers to take a look at my PR? thanks! @STRRL @YangKeao @g1eny0ung

**Comment by g1eny0ung** [comment]
Thanks @monitor1379, I'll take a look.

**Review by g1eny0ung — APPROVED** [review]
Thanks @monitor1379! I'm also no problem with the changes. Good catch!

**Pull request merged**
