### PR TITLE
Remove the duplicated GetObjectMeta method

### PR DESCRIPTION
**Pull request by iawia002**
### What problem does this PR solve?

Problem Summary: 

Since `GenericChaos` interface implements the `metav1.Object` interface, there is no need to  add the `GetObjectMeta` method.

### What is changed and how it works?

What's Changed:

Remove the duplicated `GetObjectMeta` method in the `StatefulObject` interface.

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
None
```

/assign @STRRL for review since you add the duplicated note.

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

Thanks for your contribution!

**Comment by STRRL** [comment]
PTAL

/cc @FingerLeader

**Comment by FingerLeader** [comment]
LGTM!

**Review by FingerLeader — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
> /retest

I have retriggered the tests manually for you. 🤣

**Comment by iawia002** [comment]
> > /retest
> 
> I have retriggered the tests manually for you. 🤣

🤣 I thought the /retest command works.

**Pull request merged**
