### PR TITLE
chore: format imports

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

BTW: I noticed that the `Makefile` doesn't change. Have you modified these manually? (Or how to do it automatically?)

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
> LGTM
> 
> BTW: I noticed that the `Makefile` doesn't change. Have you modified these manually? (Or how to do it automatically?)

Yep, I modified these manually now! Maybe we can use a script to help us format imports and I will try it!

**Comment by YangKeao** [comment]
> > LGTM
> > BTW: I noticed that the `Makefile` doesn't change. Have you modified these manually? (Or how to do it automatically?)
> 
> Yep, I modified these manually now! Maybe we can use a script to help us format imports and I will try it!

In #1525, I have modified `goimports` to achieve this target. But it's a little hard to deliver a modified go-tools...

**Pull request merged**
