### PR TITLE
loading pingcap/coredns:latest while e2e tests, because of docker pull rate limit

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Bypass docker hub pull request rate limit.

### What is changed and how does it work?
Loading pingcap/coredns:latest before installing chaos-mesh in e2e-tests, for avoiding docker pull rate limit.
Since "feature: DNS Chaos"  is not merged into release-1.0, so this PR also no need to cherry-pick to release-1.0.

### Checklist

Tests

- [ ] Unit test
- [x] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

It passed manually e2e-test on my local machine.

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
Please also cherry pick to release-1.0 (I have added the label)

**Comment by STRRL** [comment]
> Please also cherry pick to release-1.0 (I have added the label)

Why?  DNS Chaos is not merged into release-1.0, it does NOT need this image

**Comment by YangKeao** [comment]
> > Please also cherry pick to release-1.0 (I have added the label)
> 
> Why? DNS Chaos is not merged into release-1.0, it does NOT need this image

Sorry, my fault.

**Pull request merged**
