### PR TITLE
Fix schedule workflow webhook

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

Issue Number: 
- fix https://github.com/chaos-mesh/chaos-mesh/issues/2453

Problem Summary:
- it calls `Default` with a bad parameter, the `root` object spawned by `SpawnNewObject` has already been a pointer.

### What is changed and how it works?

What's Changed:
- change `gw.Default(&root)` to `gw.Default(root)`
- several comments for defaulter and validator 
### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No.
* Need to update Chaos Dashboard component, related issue: No.
* Need to cheery-pick to the release branch: No.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL
/cc @cwen0 
/cc @YangKeao

**Review by YangKeao — APPROVED** [review]
LGTM

cc @Hexilee

**Review by Hexilee — APPROVED** [review]
LGTM

**Pull request merged**
