### PR TITLE
[dashboard]: update DeleteIncompleteSchedules

### PR DESCRIPTION
**Pull request by fewdan**
Signed-off-by: “fewdan” <fewdan@hotmail.com>

### What problem does this PR solve?

16lgnf9jyN

Problem Summary:

### What is changed and how it works?

update DeleteIncompleteSchedules

What's Changed:

### Related changes

* None

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM

and I think the effected line is only changing the model in GORM.

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by AsterNighT — APPROVED** [review]
lgtm

**Pull request merged**
