### PR TITLE
Removing U1000 static check errors

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?
Removing U1000 static check errors

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — CHANGES_REQUESTED** [review]
please remove these codes instead of using comments.

**Comment by STRRL** [comment]
FYI, your changes have duplicated with #1762, #1768, and these PRs are going to be merged, you might need to resolve conflicts.

**Review by AsterNighT — APPROVED** [review]
LGTM

**Pull request merged**
