### PR TITLE
fix the dependency of `generate`

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What problem does this PR solve?

I should use `space` but not `,` in the arguments of dependency. Some dependencies of `generate` hasn't been added successfully.

This PR is also related to https://github.com/chaos-mesh/chaos-mesh/pull/2274.

### CODE REVIEW

**Comment by YangKeao** [comment]
@STRRL @fewdan @g1eny0ung PTAL, now `swagger_spec` is part of the `generate` target.

**Review by fewdan — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
