### PR TITLE
Check restart count for containerkill e2e test

### LINKED ISSUE #1602: `ContainerKill` e2e test is not stable
## Bug Report

If your machine is too fast, and the container was quickly resumed, it would be always "Ready", and the following condition will never meet:

https://github.com/chaos-mesh/chaos-mesh/blob/master/test/e2e/chaos/podchaos/container_kill.go#L86

```go
if cs.Name == "nginx" && !cs.Ready && cs.LastTerminationState.Terminated != nil
```

### PR DESCRIPTION
**Pull request by AsterNighT**
Signed-off-by: AsterNighT <klxjt99@outlook.com>

### What problem does this PR solve?
Fix #1602

### What is changed and how does it work?
Now container kill check restart count along with other flags, so a lightning fast restart won't be missed.

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by AsterNighT** [comment]
@YangKeao PTAL

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
