### PR TITLE
refactor!: support for deploying chaos-dashboard under the subpath

### LINKED ISSUE #2697: Change root path in chaos-mesh dashboard
## Question

I want to host dashboard under `<common-fqdn>/chaos-mesh`, instead of `<unique-fqdn-for-chaos-mesh>/`. Is it possible to achieve?

### PR DESCRIPTION
**Pull request by g1eny0ung**
## What problem does this PR solve?

Close #2697

## What's changed and how it works?

As the title says, this PR supports deploying the dashboard under the subpath (usually with an ingress).

Details: https://github.com/chaos-mesh/chaos-mesh/issues/2697#issuecomment-1604183735.

## Related changes

- [x] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [x] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [x] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@cwen0 @STRRL If there have no other suggestions, I will merge this PR tomorrow.

**Comment by ClemontX** [comment]
Hey @g1eny0ung will it autmomaticly be in the current release or do we have to wait until a new version is published?

**Comment by g1eny0ung** [comment]
> Hey @g1eny0ung will it autmomaticly be in the current release or do we have to wait until a new version is published?

A new version. I will cherry-pick this change into the `v2.6` branch and release `v2.6.2` as soon as possible (I also need to check if there have some other changes and then release at the same time).

**Comment by ClemontX** [comment]
Okay, i cross the fingers that it will be released today. 
Thanks for your work :)

**Review by STRRL — APPROVED** [review]
/lgtm

**Pull request merged**
