### PR TITLE
chore: remove useless rollme

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

close https://github.com/chaos-mesh/chaos-mesh/issues/2516.

related issue: #1996 

> Problem Summary:

### What's changed and how it works?

> What's Changed:

- remove `rollme`, because it seems we do not need it.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [x] Need to **cheery-pick to release branches**: yes, release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @AsterNighT @YangKeao @iguoyr

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM. Though, a little worried about the potential problem (as it's added deliberately)

**Pull request merged**
