### PR TITLE
Update io-attr-example.yaml

### PR DESCRIPTION
**Pull request by wingyiu**
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by YangKeao** [comment]
:beers: Thanks for your contribution @wingyiu. Can you add a sign-off?

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
