### PR TITLE
simplified logic and add test case

### PR DESCRIPTION
**Pull request by 0xff-dev**
Signed-off-by: 0xff-dev <stevenshuang521@gmail.com>

### What problem does this PR solve?
simplified logic and add test case.

### What's changed and how it works?
return in advance when conditions are met to avoid redundant traversal.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
Thanks for your contribution!

**Comment by STRRL** [comment]
Hi @0xff-dev, please resolve the conflicts with CHANGELOG.md. And I prefer to change the content in changelog like 

```
Simplified logic and add test case about finalizers. [#3422](https://github.com/chaos-mesh/chaos-mesh/pull/3422)
```

**Comment by 0xff-dev** [comment]
> Hi @0xff-dev, please resolve the conflicts with CHANGELOG.md. And I prefer to change the content in changelog like
> 
> ```
> Simplified logic and add test case about finalizers. [#3422](https://github.com/chaos-mesh/chaos-mesh/pull/3422)
> ```
ok.

**Comment by STRRL** [comment]
> > Hi @0xff-dev, please resolve the conflicts with CHANGELOG.md. And I prefer to change the content in changelog like
> > ```
> > Simplified logic and add test case about finalizers. [#3422](https://github.com/chaos-mesh/chaos-mesh/pull/3422[](https://github.com/chaos-mesh/chaos-mesh/pull/3422))
> > ```
> 
> ok.

Hi @0xff-dev ! How about updating the changelog? 🤣

**Comment by 0xff-dev** [comment]
> > > Hi @0xff-dev, please resolve the conflicts with CHANGELOG.md. And I prefer to change the content in changelog like
> > > ```
> > > Simplified logic and add test case about finalizers. [#3422](https://github.com/chaos-mesh/chaos-mesh/pull/3422[](https://github.com/chaos-mesh/chaos-mesh/pull/3422))
> > > ```
> > 
> > 
> > ok.
> 
> Hi @0xff-dev ! How about updating the changelog? 🤣
I'm so sorry, I just resolved the conflict. changelog has been updated

**Comment by 0xff-dev** [comment]
> > > Hi @0xff-dev, please resolve the conflicts with CHANGELOG.md. And I prefer to change the content in changelog like
> > > ```
> > > Simplified logic and add test case about finalizers. [#3422](https://github.com/chaos-mesh/chaos-mesh/pull/3422[](https://github.com/chaos-mesh/chaos-mesh/pull/3422))
> > > ```
> > 
> > 
> > ok.
> 
> Hi @0xff-dev ! How about updating the changelog? 🤣

First contribution, a little excited. 😅

**Comment by STRRL** [comment]
> > > > Hi @0xff-dev, please resolve the conflicts with CHANGELOG.md. And I prefer to change the content in changelog like
> > > > ```
> > > > Simplified logic and add test case about finalizers. [#3422](https://github.com/chaos-mesh/chaos-mesh/pull/3422[](https://github.com/chaos-mesh/chaos-mesh/pull/3422)[](https://github.com/chaos-mesh/chaos-mesh/pull/3422[](https://github.com/chaos-mesh/chaos-mesh/pull/3422)))
> > > > ```
> > > 
> > > 
> > > ok.
> > 
> > 
> > Hi @0xff-dev ! How about updating the changelog? 🤣
> 
> First contribution, a little excited. 😅

Haha, again, thanks for your contribution!

**Pull request merged**
