### PR TITLE
fix JVMChaos missing file: /usr/local/byteman/lib/chaos-agent.jar

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <im@strrl.dev>

### What problem does this PR solve?

close https://github.com/chaos-mesh/chaos-mesh/issues/3472

### What's changed and how it works?

- copy missing file `/usr/local/byteman/lib/chaos-agent.jar` into applications container / mount namespace

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.3
  - [x] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @YangKeao @Andrewmatilde @WangXiangUSTC @cwen0 @Hexilee

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
It's my mistake, thanks. LGTM

**Pull request merged**
