### PR TITLE
also run ci skip to pass required test

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

Add multi architecture strategy to ci skip.

This is not the best way to solve the problem. I'll find better way to skip (with required test) in the future, track in https://github.com/chaos-mesh/chaos-mesh/issues/3306

### CODE REVIEW

**Comment by YangKeao** [comment]
This may fix the problem which makes https://github.com/chaos-mesh/chaos-mesh/pull/329 impossible to merge.

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
there are still 2 checks stuck in "Waiting for status to be reported", PTAL @YangKeao 
image

**Comment by YangKeao** [comment]
> there are still 2 checks stuck in "Waiting for status to be reported", PTAL @YangKeao image

I removed the ui verify/test on arm64 as the frontend itself is not platform dependent :thinking: . PTAL

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
