### PR TITLE
(bugsbash) remove redundant # from CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by asquare14**
### What is changed and how does it work?
Removed a typo from CONTRIBUTING.md

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
Hi @asquare14, thanks for your contribution.

You should fix the DCO to pass the check. In short, you should commit your codes with `--signoff`.

**Review by AsterNighT — APPROVED** [review]
lgtm

**Pull request merged**
