### PR TITLE
feat(ui): allow importing external workflows and copying flow nodes in next generation `New Workflow`

### LINKED ISSUE #3364: ui(workflow-ng): copy single `Node` to reuse

### LINKED ISSUE #3365: ui(workflow-ng): import workflow from Yaml

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What problem does this PR solve?

Close #3364.
Close #3365.

### What's changed and how it works?

This PR modifies the way nodes are connected in the flowchart. Since Workflow is "flexible" (for example, if there are currently two parallel nodes, one with 3 children and the other with 4, they cannot be connected one-to-one), I created separate `Serial` and `Parallel` nodes to contain the children. Then I finished this PR based on that.

#### Demos

https://user-images.githubusercontent.com/15034155/174005450-8221b36e-fced-4064-b8f1-b9d8ecac999e.mp4

https://user-images.githubusercontent.com/15034155/173811776-5c073be5-307a-4ce9-b72b-331915797074.mp4

https://user-images.githubusercontent.com/15034155/173811815-9203ea92-617b-495d-9775-a30ceb0327f3.mp4

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [x] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
In fe24730, I added an arrow at the end of the edge to identify the next node, and the workflow flow is now a bit clearer.

**Review by STRRL — COMMENTED** [review]
I failed to build the frontend project:
image



I think we should remove this line: https://github.com/chaos-mesh/chaos-mesh/blob/fe247305e5c27549ed40819b5f766606691acbfd/ui/app/src/components/AutoForm/index.tsx#L279

**Comment by STRRL** [comment]
rest LGTM!

Awesome!

**Comment by g1eny0ung** [comment]
> I failed to build the frontend project: image
> 
> I think we should remove this line:
> 
> https://github.com/chaos-mesh/chaos-mesh/blob/fe247305e5c27549ed40819b5f766606691acbfd/ui/app/src/components/AutoForm/index.tsx#L279

Thanks! I forgot to remove this line. Now it's fixed.

**Comment by cwen0** [comment]
I can't delete this `parallel` node. 
image

**Comment by cwen0** [comment]
In `parallel` node, I created three experiments and specified the sequential relationship, but the YAML file still has three parallel tasks. If we don't support such an operation, we should disable the addition of sequential relationships. 

image
image

**Comment by cwen0** [comment]
image
image

**Comment by g1eny0ung** [comment]
> I can't delete this `parallel` node. image

😵 I forgot to add the operations menu to `Serial` and `Parallel` nodes. I will fix them soon.

**Review by STRRL — APPROVED** [review]
LGTM!

I have tried to use it on my own machine with the example workflow yaml files.

**Comment by g1eny0ung** [comment]
> In `parallel` node, I created three experiments and specified the sequential relationship, but the YAML file still has three parallel tasks. If we don't support such an operation, we should disable the addition of sequential relationships.
> 
> image image

This place needs to be improved. Currently, I haven't limited users to connect nodes when they aren't permitted to connect. I will open an issue to track it later.

**Comment by g1eny0ung** [comment]
> image image

Fixed in [bdc8b8d](https://github.com/chaos-mesh/chaos-mesh/pull/3368/commits/bdc8b8dfe0e82c8ba1ac521c446afe67c85f098e).

**Pull request merged**
