### PR TITLE
[add]add unit tests for archive

### PR DESCRIPTION
**Pull request by fewdan**
### What problem does this PR solve?

add unit tests for archive

### What is changed and how does it work?
add unit tests for archive

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
Seems this PR includes changes in #1189.

**Comment by fewdan** [comment]
> Seems this PR includes changes in #1189.

Yes, I cut the wrong branch when I was "checkout"..

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
