### PR TITLE
Workflow: flatten the directory; appending mock thing and unit test for serial scheduler;

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

Mock framework and unit test for the serial scheduler.

### What is changed and how does it work?

- As comments by @cwen0, the "engine" directory is meaningless, so I flatten the structure, remove this directory.
- Generate mocking codes by `mockgen`, provided by [gomock](https://github.com/golang/mock).
- Several unit test cases for the serial scheduler.

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by STRRL** [comment]
I think this PR is ready to review. PTAL @YangKeao @WangXiangUSTC @cwen0 

Most codes of this PR are generated mocking codes, about 882 lines. So this is PR is not so that giant.😜

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
