### PR TITLE
validate cpu load

### LINKED ISSUE #3064: STRESS TEST load over 100 will not take effect
chaos mesh v2.1.3
dashboard -> STRESS TEST -> CPU -> Load

If I fill in the blank with value over 100, the STRESS TEST will not take effect.
the value's validation is needed.
image

### PR DESCRIPTION
**Pull request by xlgao-zju**
### What problem does this PR solve?

Close #3064

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

set cpu stress load 150

then I get 

```
error.api.internal_server_error: admission webhook "vstresschaos.kb.io" denied the request: Spec.Stressors.CPUStressor.Load: Invalid value: 150: valid cpu load is from 0 to 100
Side effects
```

image

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Maybe we could use `kubebuilder:validation:Maximum` and `kubebuilder:validation:Minimum` to archive this easier. 🙈

And both the edge values `0` and `100` should be included as the valid vlaues.

**Comment by xlgao-zju** [comment]
@STRRL updated

**Comment by xlgao-zju** [comment]
maybe we can rerun the failed tests periodically, if the PR has `status/can-merge` label.

**Pull request merged**
