### PR TITLE
reset failed message when applying action successfully

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What problem does this PR solve?
 

image

After updating the chaos experiment and applying successfully, we should reset failed message. But we didn't it. 

### What is changed and how does it work? 

* Reset failed message when applying action successfully
* Set message for each event. 

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by fewdan — DISMISSED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@g1eny0ung We can show the failed message at each event on chaos dashboard.

**Comment by g1eny0ung** [comment]
> @g1eny0ung We can show the failed message at each event on chaos dashboard.

Got it. I will think about how to implement it in the dashboard.

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
