### PR TITLE
fix: chaos-kernel-builds, python3 and mark bcc version

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Close https://github.com/chaos-mesh/chaos-mesh/issues/2691

### What's changed and how it works?

- mark bcc at v0.23.0

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [x] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

build chaos-kernel with `make image-chaos-kernel` on local machine

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @YangKeao @Hexilee @Andrewmatilde

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by Hexilee — APPROVED** [review]
LGTM

**Pull request merged**
