### PR TITLE
fix panic with /metrics of chaos-daemon

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

- chaos-daemon would panic when access it's /metrics endpoint

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @Andrewmatilde @Hexilee @iguoyr

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@STRRL Does this pr need to cherry-pick to release-2.1 branch?

**Comment by STRRL** [comment]
yes, but it needs manually cheerypick with #2912 which introduce this bug

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
