### PR TITLE
Fix for make check does not respect the env-images.yaml

### PR DESCRIPTION
**Pull request by DaivikDave**
Signed-off-by: Daivik <daivikdave229@gmail.com>

### What problem does this PR solve?
#3210 

### What's changed and how it works?
IMAGE_DEV_ENV_TAG and IMAGE_DEV_ENV_TAG were not accessible in build/build_images.py. It resulted in it taking the default value defined by export IMAGE_TAG ?= latest

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — COMMENTED** [review]
Hi @DaivikDave! Thanks for your contribution!

Please update the CHANGELOG.md, rest LGTM!

after exporting enough of ENV, maybe BASIC_IMAGE_ENV could be removed?

/cc @YangKeao

**Comment by DaivikDave** [comment]
Thanks @STRRL , Updated the changelog!

**Comment by STRRL** [comment]
> Thanks @STRRL , Updated the changelog!

Hi @DaivikDave , you should update the section under `Unreleased`, not `2.2.0` :)

**Comment by STRRL** [comment]
Hi @DaivikDave, do you need some help? :)

**Comment by DaivikDave** [comment]
Hey @STRRL , I was unable to work on it due to some urgency. I'll get the changes pushed.

**Comment by DaivikDave** [comment]
Hey @STRRL , Sorry for the delay, I made the changes.

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by YangKeao — APPROVED** [review]
LGTM

BTW: `export` doesn't work for the `shell` command in the `Makefile`. It's a known but will not be fixed issue (of the GNU make) :cry: .

**Pull request merged**
