### PR TITLE
update go version to 1.15.11 in github workflows

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>

### What problem does this PR solve?

Follow the upgrade in #1688.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by AsterNighT — COMMENTED** [review]
https://github.com/chaos-mesh/chaos-mesh/blob/64c59c0a1d43d15fe707afb8160e0601b4bc2f82/test/cmd/e2e_helper/go.mod#L3

Can we change this to 115?

**Comment by Hexilee** [comment]
> https://github.com/chaos-mesh/chaos-mesh/blob/64c59c0a1d43d15fe707afb8160e0601b4bc2f82/test/cmd/e2e_helper/go.mod#L3
> 
> Can we change this to 115?

It seems this package is independent.

**Comment by Hexilee** [comment]
> https://github.com/chaos-mesh/chaos-mesh/blob/64c59c0a1d43d15fe707afb8160e0601b4bc2f82/test/cmd/e2e_helper/go.mod#L3
> 
> Can we change this to 115?

Downgraded.

**Comment by AsterNighT** [comment]
It is still troublesome to change all go versions manually every time. Is there a way to track all go versions?

**Comment by AsterNighT** [comment]
> > https://github.com/chaos-mesh/chaos-mesh/blob/64c59c0a1d43d15fe707afb8160e0601b4bc2f82/test/cmd/e2e_helper/go.mod#L3
> > 
> > Can we change this to 115?
> 
> Downgraded.

https://golang.org/doc/modules/gomod-ref#go-syntax

**Comment by Hexilee** [comment]
> It is still troublesome to change all go versions manually every time. Is there a way to track all go versions?

Maybe we should lock the medium version as `1.15` and accept all auto-upgrade of the minor version.

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]

**Comment by AsterNighT** [comment]
It seems that we need to cherrypick this to `nirvana`.

**Comment by cwen0** [comment]
@Hexilee PTAL

**Pull request merged**
