### PR TITLE
Fix SA4006 errors

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Fix SA4006 errors

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by STRRL — CHANGES_REQUESTED** [review]
Part of this PR is duplicated with https://github.com/chaos-mesh/chaos-mesh/pull/1778, and we prefer that one. 🙈

Rest part LGTM

**Comment by anuragpaliwal80** [comment]
@STRRL I just check the PR #1778 and to me it looks like we are fixing different issues. I pulled those changes via rebase as that PR has been merged. Can you please review this again ? -thx

**Comment by STRRL** [comment]
> @STRRL I just check the PR #1778 and to me it looks like we are fixing different issues. I pulled those changes via rebase as that PR has been merged. Can you please review this again ? -thx

Actually, they resolve the same issue. 🙈
Please fixes the CI, and you will find that the duplication when compiling it.

**Comment by anuragpaliwal80** [comment]
Closing this PR.

**Pull request closed without merging**
