### PR TITLE
refactor: move common used attach/ptrace function

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

No.

### What's changed and how it works?

refactor: 
- move a method which would be commonly used in each `TimeChaosInject` into `FakeImage`

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @YangKeao @Hexilee @Andrewmatilde

**Review by iguoyr — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
I would manually cherry-pick it

**Pull request merged**
