### PR TITLE
chore: rename PodMode to SelectorMode

### PR DESCRIPTION
**Pull request by iguoyr**
Signed-off-by: SiyuChen <ryougi201@gmail.com>

### What problem does this PR solve?

Problem Summary: as #2390 said, this pr prepares for physical machine auth.

### What is changed and how it works?

What's Changed: rename PodMode to SelectorMode

### Related changes

NA

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by iguoyr** [comment]
/cc @STRRL 
/cc @WangXiangUSTC 
PTAL

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
There are many comments still using words like `FixedPercentPodMode` and `RandomMaxPercentPodMode`. It's better to update the comments in another PR. :)  PTAL @iguoyr

**Comment by iguoyr** [comment]
> There are many comments still using words like `FixedPercentPodMode` and `RandomMaxPercentPodMode`. It's better to update the comments in another PR. :) PTAL @iguoyr

@STRRL I see! These comments have typo with `FixedPercentPodMod` and `RandomMaxPercentPodMod` (so they are missed in batch replacement), I'll fix it in next pr.

**Pull request merged**
