### PR TITLE
Refactor pkg/dashboard/apiserver/schedule to use pkg level log 

### LINKED ISSUE #2876: Refine logging in `pkg/dashboard/apiserver/schedule`, move package level variable `log` into struct `Service` as a field.
> Please leave comments with your idea if you are interested in this issue. And comment `/assign` to operate self-assign before you work on it.

### PR DESCRIPTION
**Pull request by afzal442**
Signed-off-by: afzal442 <afzal442@gmail.com>

### What problem does this PR solve?
Fixes #2876 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM! 🍻

Thanks for your contribution!

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
