### PR TITLE
fix: the broken webhook for workflow

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Issue Number:

Problem Summary:

Thanks to @g1eny0ung for noticing me about this issue.

As #2122 merged, some of the generated methods (`Validate() field.ErrorList` and `Default()`) for interface `CommonSpec` has been purged ``:

```golang
type CommonSpec interface {
	GetDuration() (*time.Duration, error)
	Validate() field.ErrorList
	Default()
}
```

but `GetDuration()` is required for validation in workflow by `shouldNotSetupDurationInTheChaos()`.

So I rename and slim the unimplemented methods of `CommonSpec`.

### What is changed and how it works?

What's Changed:

- delete `Validate() field.ErrorList` and `Default` in interface `CommonSpec`
- rename interface `CommonSpec` to `ContainsDuration`
- add some unit test for this validation webhook

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No.
* Need to update Chaos Dashboard component, related issue: No.
* Need to cheery-pick to the release branch: No.

### Checklist

Tests

- [x] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @YangKeao, do we have other better interface for replacing `CommonSpec`?

**Review by g1eny0ung — APPROVED** [review]
I have no problem with this temporary fix. LGTM.

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
