### PR TITLE
chore: update overview and experiments related (new, detail)

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What problem does this PR solve?

This PR introduces a lot of changes in the dashboard, includes:

- Overview page
  - Total Experiments panel
  - Status panel
- Renew **experiment detail**, get rid of the json-view panel
- Renew **new experiment**, now you can create an experiment from existing experiments
- bug fixes

And also, this PR has some issues that are left, need to wait for other PRs to fix it before solving it:

- Support limit parameter to update events dynamically. #645
- If we have two experiments with the same name, now the events table can't distinguish them correctly. #711
- Remove empty fields in experiment detail to help the update experiment operation. #700

Due to more changes, it's hard to review the code one by one file. You can check this PR to the local to view the interface changes.

### CODE REVIEW

**Comment by cwen0** [comment]
Sometimes, when the creation is completed, the page will jump to a blank page.  
WeChatWorkScreenshot_32d204f7-bbee-4a12-9641-98ec8ce6d3c7

**Comment by g1eny0ung** [comment]
@cwen0 @fewdan The blank page issue should be fixed in e6bb42b.

**Pull request merged**
