### PR TITLE
fix: pod chaos example

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Problem Summary: 

### What is changed and how it works?

What's Changed:

update example file of pod chaos

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No.
* Need to update Chaos Dashboard component, related issue: No.
* Need to cheery-pick to the release branch: No.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by fewdan** [comment]
You can look at my [PR](https://github.com/chaos-mesh/chaos-mesh/pull/1985) which deals with this problem.

**Review by AsterNighT — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
As https://github.com/chaos-mesh/chaos-mesh/pull/1985 has been merged, this PR should be closed.

**Pull request closed without merging**
