### PR TITLE
upgrade go version to 1.15.11 in build-env

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>

### What problem does this PR solve?
We can use the features of go-1.15 like `sync.Map.LoadAndDelete`.

### What is changed and how does it work?
Upgrade go toolchain in Dockerfile of build-env.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
e2e test failed because of dockerhub rate limiting, I will back to look it after several hours.

**Comment by STRRL** [comment]
Hi @Hexilee, does this PR need to be cheery-picked to release-1.1 and release-1.2?

**Comment by Hexilee** [comment]
> Hi @Hexilee, does this PR need to be cheery-picked to release-1.1 and release-1.2?

It seems we don't require any features of go-1.15 in release-1.1 or release-1.2, and it may cause issues like #1618.

**Comment by Hexilee** [comment]
> > Hi @Hexilee, does this PR need to be cheery-picked to release-1.1 and release-1.2?
> 
> It seems we don't require any features of go-1.15 in release-1.1 or release-1.2, and it may cause issues like #1618.

@AsterNighT said #1618 is already fixed, we can cherry-pick this pr following #1692.

**Pull request merged**
