### PR TITLE
fix panic in state machine when state is unexpected

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

### What problem does this PR solve?

fix issue https://github.com/chaos-mesh/chaos-mesh/issues/1568 controller-manager will be panic if chaos experiment with unexpected phase

### What is changed and how does it work?

return error if state is unexpected

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by Colstuwjx** [comment]
Could you add a test case in `state_machine_test.go` for this case?

**Comment by WangXiangUSTC** [comment]
> state_machine_test

Of course 😃

**Comment by Colstuwjx** [comment]
It seems that ci test panicked from [this line](https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/apiserver/experiment/experiment.go#L164).

**Comment by WangXiangUSTC** [comment]
> It seems that ci test panicked from [this line](https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/apiserver/experiment/experiment.go#L164).

seems that get error when send request to `/api/experiments/update`, not in create

**Comment by Colstuwjx** [comment]
> seems that get error when send request to /api/experiments/update, not in create

Yes, my mistake 😅

**Review by Colstuwjx — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Comment by Colstuwjx** [comment]
It seems that the APIServer integration test is not stable, I've run it again.

**Pull request merged**
