### PR TITLE
Fix development guide broken link

### PR DESCRIPTION
**Pull request by shardulsrivastava**
Fix development guide broken link

### What problem does this PR solve?
Fix the broken link to the development guide.

Problem Summary: The link to the development guide from README.md wasn't working.

### What is changed and how it works?

What's Changed: Added the correct [link](https://chaos-mesh.org/docs/developer-guide-overview) 

### Related changes

* PR to update `chaos-mesh/chaos-mesh`/`README.md`.

Tests

- [x] No code

Side effects- N/A

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by Hexilee** [comment]
Hi @shardulsrivastava ,the DCO check fails, please follow the [guide](https://probot.github.io/apps/dco/) to sign the commits and force push them to your work branch.

**Comment by shardulsrivastava** [comment]
Hi @Hexilee , I have fixed it and pushed the commit using DCO.

**Review by Hexilee — APPROVED** [review]
LGTM

**Review by STRRL — APPROVED** [review]
LGTM!
Thanks for your contribution!

**Pull request merged**
