### PR TITLE
ci: fix cache path calculation

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

Recent e2e test image build doesn't hit the cache, because of a bug in calculating the cache directory 😢 This PR solves two problems:

1. The fake_image targets should depend on build-env, but not dev-env.
2. The cache directory should be joined with an image name directory.

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

**Comment by STRRL** [comment]
Should this PR be cheery-picked to release-2.1?

**Comment by YangKeao** [comment]
> Should this PR be cheery-picked to release-2.1?

No. `build-script` is only merged on master (which is expected, I think)

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
