### PR TITLE
chore: upgrade kind apiVersion to v1alpha4 (#2258)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2258 to release-2.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In chaos-mesh repo:
git pr https://github.com/chaos-mesh/chaos-mesh/pull/2260
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/chaos-mesh.git pr/2260:release-2.0-25db3b4dcff3
```

---

### What problem does this PR solve?

Problem Summary: 

```
start to create kubernetes cluster kindERROR: failed to create cluster: unknown apiVersion: kind.sigs.k8s.io/v1alpha3
```

### What is changed and how it works?

What's Changed: 

1. upgrade `kind.sigs.k8s.io/v1alpha3` to `kind.x-k8s.io/v1alpha4`,  `v1alpha3` kind config is no longer supported since v0.9.0
2. use v0.11.1 as the default version of kind

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`:
* Need to update Chaos Dashboard component, related issue:
* Need to cheery-pick to the release branch

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by cwen0 — APPROVED** [review]

**Comment by STRRL** [comment]
it seems Jenkins failed to pull e2e images：
```
[2021-08-30T11:29:34.705Z] [Normal][jenkins-tidb/chaos-mesh-e2e-942-kn1l0-htc76-n7m4q][BackOff] Back-off pulling image "hub.pingcap.net/yangkeao/chaos-mesh-e2e-base"

[2021-08-30T11:29:34.707Z] ERROR: Unable to pull Docker image "hub.pingcap.net/yangkeao/chaos-mesh-e2e-base". Check if image tag name is spelled correctly.

```

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
