### PR TITLE
upgrade gopsutil pkg to v3

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### What problem does this PR solve?

 

fixed: #2388 

### What's changed and how it works?

  

upgrade gopsutil pkg to v3 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

image

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by YangKeao — APPROVED** [review]
This PR reminds me to PR to gopsutil to fix some bugs which should be fixed one year ago 😢.

LGTM

**Comment by STRRL** [comment]
Hi @cwen0 does this PR need to be cherry-picke to `release-2.0` and `release-2.1`?

**Pull request merged**
