### PR TITLE
Fix bugsmash errors of SA1019

### PR DESCRIPTION
**Pull request by soniasingla**

### CODE REVIEW

**Comment by asquare14** [comment]
@soniasingla Arent they the same https://github.com/chaos-mesh/chaos-mesh/pull/1812

**Comment by soniasingla** [comment]
Just rebased

**Comment by STRRL** [comment]
the changes on bpkfi.pb.go duplicated with #1799 and #1798, also meets the same issue: you should NOT edit .pb.go manually.

maybe these comments will help you fixing that issue correctly: https://github.com/chaos-mesh/chaos-mesh/pull/1798#discussion_r628357495, https://github.com/chaos-mesh/chaos-mesh/pull/1798#discussion_r628350934

**Pull request closed without merging**
