### PR TITLE
Create selector.Selector type and accept it in SelectAndFilterPods

### LINKED ISSUE #1548: Dispatch the config in a better way
```go
pods, err := selector.SelectAndFilterPods(ctx, r.Client, r.Reader, &dnschaos.Spec, config.ControllerCfg.ClusterScoped, config.ControllerCfg.TargetNamespace, config.ControllerCfg.AllowedNamespaces, config.ControllerCfg.IgnoredNamespaces)
```

This line of code occurs several times in Chaos Mesh code base, and most of these `config.xxx.xxx` won't change during the runtime. Please construct a "Selector" struct from config (or something similar) to select, rather than passing these arguments everytime.

### PR DESCRIPTION
**Pull request by dominikbraun**
### What problem does this PR solve?
Closes #1548.

### What is changed and how does it work?
This PR introduces the `selector.Selector` type. The following line exists multiple times throughout the codebase:

```go
pods, err := selector.SelectAndFilterPods(ctx, r.Client, r.Reader, &dnschaos.Spec, config.ControllerCfg.ClusterScoped, config.ControllerCfg.TargetNamespace, config.ControllerCfg.AllowedNamespaces, config.ControllerCfg.IgnoredNamespaces)
```

With this change, they will look as follows:

```go
pods, err := selector.SelectAndFilterPods(ctx, r.Client, r.Reader, &dnschaos.Spec, selector.FromControllerConfig(config.ControllerCfg))
```

### Checklist

Tests

- [ ] Unit test

### CODE REVIEW

**Comment by dominikbraun** [comment]
At the moment, some of the CI checks fail:

```
failed to compute cache key: "/bin/chaos-daemon" not found: not found
```

Is this my fault or are those tests flaky by any chance? 🤔

**Comment by fewdan** [comment]
It seem that you can fix some simple CI first, for example, you can execute "make test" on your computer to process it.

**Comment by YangKeao** [comment]
> At the moment, some of the CI checks fail:
> 
> ```
> failed to compute cache key: "/bin/chaos-daemon" not found: not found
> ```
> 
> Is this my fault or are those tests flaky by any chance? thinking

Because the `/bin/chaos-daemon` failed to compile:

```log
2021-03-28T11:42:59.3391422Z # github.com/chaos-mesh/chaos-mesh/pkg/mock
2021-03-28T11:42:59.3392848Z pkg/mock/mock.go:58:29: undefined: _curpkg_
2021-03-28T11:42:59.3394068Z note: module requires Go 1.15
2021-03-28T11:43:12.9176864Z make: *** [Makefile:250: images/chaos-daemon/bin/chaos-daemon] Error 2
```

**Comment by dominikbraun** [comment]
Something obviously went wrong here :-)

**Comment by dominikbraun** [comment]
I'm going to create a new PR since this mess is too big for me 🤣

**Pull request closed without merging**
