### PR TITLE
fix document for container selector

### LINKED ISSUE #2678: fix codecov for each branch
The codecov has been misconfigured on this repo for a long time.

It seems there exists a CI job to upload the coverage data to the codecov, but unstable.

 I think we could set up another GitHub Action for this thing.

### LINKED ISSUE #2687: k8s: Simulate Time Faults can not work
## Bug Report

What version of Kubernetes are you using?
1.20.4-aliyun.1

What version of Chaos Mesh are you using?
Controller manager Version: version.Info{GitVersion:"v2.1.1", GitCommit:"4ebd7a21520305bd0cf38e228f84ebc639aab994", BuildDate:"2021-12-10T10:27:29Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

```
kind: TimeChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: clockreviews
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: reviews
  mode: all
  timeOffset: '-30m'
  clockIds:
    - CLOCK_REALTIME
  duration: 3600s
```

image

image

the logs of the application is below, time is not change also.
image

**What did you expect to see?**
I expect the time is Tue Dec 21 12:47:01 UTC 2021, but is Tue Dec 21 12:07:01 UTC 2021.

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

Fix #2687 

The problem is that, every document about container selector shows that it will inject all containers, but the implementation is (and always was) to inject only the first one. I prefer to keep the real behavior and modify the document. If you have other opinions (like "we should modify the behavior!"), please comment in this PR.

Related document PR https://github.com/chaos-mesh/website/pull/218

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by STRRL** [comment]
> Fix #2678

@YangKeao It points to a PR, not an issue. Please update. 🤣

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
