### PR TITLE
fix gitVersion while compling in GithubAction

### LINKED ISSUE #2659: Invalid `GitVersion`: "v0.0.0-master+$Format:%h$"
## Bug Report

**What version of Kubernetes are you using?**
 

1.20.2

**What version of Chaos Mesh are you using?**
 

```
Chaos Dashboard Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"e79f3114571122cd3b6991d1faaa66cdcce35a73", BuildDate:"2021-12-15T18:04:31Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

**What did you expect to see?**  

v0.0.0-master-`commit` 

**What did you see instead?** 

v0.0.0-master+$Format:%h$

**Output of chaosctl**

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

close #2659 

### What's changed and how it works?

- with step `action/checkout@master`, setup `fetch-depth: 0` to fetch all the tags and branches
- setup `--always` with `git describe`, it would give the commit hash as fallback instead of fatal then nothing be set with `GIT_VERSION`. 

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [x] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

I manually tested it at https://github.com/STRRL/chaos-mesh/actions/workflows/fix_git_version.yml.

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```
Signed-off-by: STRRL <str_ruiling@outlook.com>

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @iguoyr @cwen0

**Comment by iguoyr** [comment]
@STRRL Hi, the latest workflow in https://github.com/STRRL/chaos-mesh/actions/workflows/fix_git_version.yml is failed, could you run a new one?

**Comment by STRRL** [comment]
> @STRRL Hi, the latest workflow in [STRRL/chaos-mesh/actions/workflows/fix_git_version.yml](https://github.com/STRRL/chaos-mesh/actions/workflows/fix_git_version.yml) is failed, could you run a new one?

Updated!

**Review by iguoyr — APPROVED** [review]
LGTM!

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
