### PR TITLE
feat!: UI monorepo

### PR DESCRIPTION
**Pull request by g1eny0ung**
### What problem does this PR solve?

> Problem Summary:

### What's changed and how it works?

Proposal: [feat: scalable codebase in UI via monorepo](https://github.com/chaos-mesh/rfcs/pull/26)

> What's Changed:

See RFC for more details.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Chaos Dashboard`
- [ ] Need to **cheery-pick to release branches**

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Breaking backward compatibility

### Release note 

```text
BREAKING CHANGE: UI codebase changed from single app to monorepo
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
I meet an issue that after I execute `yarn install` under `ui`, the `make check` goes wrong.

It seems there is some npm package that downloads several `.c` files and let `go vet` goes wrong.  

PTAL @g1eny0ung

**Comment by g1eny0ung** [comment]
> I meet an issue that after I execute `yarn install` under `ui`, the `make check` goes wrong.
> 
> It seems there is some npm package that downloads several `.c` files and let `go vet` goes wrong.
> 
> PTAL @g1eny0ung

After I checked I found that some examples files existed for a dependency and I thought I could delete them after installing the dependency because I found it inconvenient to ignore commands like `go vet`.

**Comment by g1eny0ung** [comment]
@STRRL Already fixed.

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
