### PR TITLE
add values.schema.json

### LINKED ISSUE #3358: provide values.schema.json for helm chart
## Feature Request

**Is your feature request related to a problem? Please describe:**

Schemaless helm values.yaml.

**Describe the feature you'd like:**

provide `values.schema.json`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by losisin**
## What problem does this PR solve?
Adds values.schema.json file with validations for `dashboard.env.DATABASE_DRIVER` and `chaosDaemon.runtime`.

Close #3358

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [x] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@losisin Looks great! I was searching for a tool that could automatically generate a schema, and then I found https://github.com/karuppiah7890/helm-schema-gen. Are you using this?

**Comment by losisin** [comment]
Yes and forked it already but doesn't work if you want validations for acceptable input values

**Comment by g1eny0ung** [comment]
> Yes and forked it already but doesn't work if you want validations for acceptable input values

I haven't had time to verify it yet, but I'll get to it this week.

**Comment by STRRL** [comment]
> Yes and forked it already but doesn't work if you want validations for acceptable input values

Is there anyway to generate helm schema automatically?

**Comment by losisin** [comment]
> > Yes and forked it already but doesn't work if you want validations for acceptable input values
> 
> Is there anyway to generate helm schema automatically?

yes. In this PR I used https://github.com/karuppiah7890/helm-schema-gen but that one is public archive now. Started writing my own but I haven't released it yet. It will accept multiple values files as input, custom output file name/location and draft version. You can use it with pre-commit hooks or from CI pipeline. My plugin also doesn't support fields like required or enum but I might add that in future if it's a deal breaker. I plan to release it next week 🤞

**Review by g1eny0ung — APPROVED** [review]
@losisin LGTM! I am preparing to merge this PR and hope your new schema-gen plugin is successfully released! If it improves the existing schema-gen plugin, please let us know and we can update the schema again.

**Pull request merged**
