### PR TITLE
Respect flag enableProfiling in chaos-dashboard

### LINKED ISSUE #3456: Profiler is not disabled even controlling key is set to false
## Bug Report

**What version of Kubernetes are you using?**

**1.21**

**What version of Chaos Mesh are you using?**

**2.2.1**

**What did you do?**

When the dashboard pod is created, GIN outputs all the routes, as well as reports running in, debug mode:

```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /debug/pprof/             --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/block        --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
[GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-contrib/pprof.pprofHandler.func1 (3 handlers)
```

So I've investigated a bit and tweaked a couple of things:
* Added `GIN_MODE: release` to `dashboard.env`
* Set `enableProfiling` to `false`
* Redeployed the dashboard

**What did you expect to see?**

* Profiling endpoints not accessible
* GIN running in release mode

**What did you see instead?**

* Gin runs in release mode
* Profiling endpoints are still accessible:

```
❯ curl http://mydomain.tld/debug/pprof/
<html>
<head>
<title>/debug/pprof/</title>
<style>
.profile-name{
	display:inline-block;
	width:6rem;
}
</style>
</head>
<body>
/debug/pprof/<br>
<br>
Types of profiles available:
<table>
<thead><td>Count</td><td>Profile</td></thead>
<tr><td>86</td><td><a href='allocs?debug=1'>allocs</a></td></tr>
<tr><td>0</td><td><a href='block?debug=1'>block</a></td></tr>
<tr><td>0</td><td><a href='cmdline?debug=1'>cmdline</a></td></tr>
<tr><td>247</td><td><a href='goroutine?debug=1'>goroutine</a></td></tr>
<tr><td>86</td><td><a href='heap?debug=1'>heap</a></td></tr>
<tr><td>0</td><td><a href='mutex?debug=1'>mutex</a></td></tr>
<tr><td>0</td><td><a href='profile?debug=1'>profile</a></td></tr>
<tr><td>10</td><td><a href='threadcreate?debug=1'>threadcreate</a></td></tr>
<tr><td>0</td><td><a href='trace?debug=1'>trace</a></td></tr>
</table>
<a href="goroutine?debug=2">full goroutine stack dump</a>
<br>
<p>
Profile Descriptions:
<ul>
<li><div class=profile-name>allocs: </div> A sampling of all past memory allocations</li>
<li><div class=profile-name>block: </div> Stack traces that led to blocking on synchronization primitives</li>
<li><div class=profile-name>cmdline: </div> The command line invocation of the current program</li>
<li><div class=profile-name>goroutine: </div> Stack traces of all current goroutines</li>
<li><div class=profile-name>heap: </div> A sampling of memory allocations of live objects. You can specify the gc GET parameter to run GC before taking the heap sample.</li>
<li><div class=profile-name>mutex: </div> Stack traces of holders of contended mutexes</li>
<li><div class=profile-name>profile: </div> CPU profile. You can specify the duration in the seconds GET parameter. After you get the profile file, use the go tool pprof command to investigate the profile.</li>
<li><div class=profile-name>threadcreate: </div> Stack traces that led to the creation of new OS threads</li>
<li><div class=profile-name>trace: </div> A trace of execution of the current program. You can specify the duration in the seconds GET parameter. After you get the trace file, use the go tool trace command to investigate the trace.</li>
</ul>
</p>
</body>
</html>
```

Ideally, I think it would make sense to make profiling disabled by default as well as GIN running in release mode. In other, words just flip the configuration

**Output of chaosctl**

N/A

### PR DESCRIPTION
**Pull request by brnck**
Signed-off-by: brnck <a.berneckas@gmail.com>

### What problem does this PR solve?

Close #3456

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [X] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [X] Manual test (add steps below)

* Deploy chaos-mesh
* `curl <domain>:<port>/debug/pprof/` - will return HTML with profiler endpoints
* Check chaos-dashboard logs - you will see that it registers endpoints
* set `enableProfiling` parameter to `false` and redeploy
* Check chaos-dashboard logs - you will see that it does not register endpoints
* `curl <domain>:<port>/debug/pprof/` - won't return HTML with profiler endpoints. WIll return homepage instead

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM!

**Review by g1eny0ung — APPROVED** [review]
LGTM! Thanks for the improvement. 🐝

**Comment by brnck** [comment]
@STRRL should I update swagger docs by myself? Re: [this job](https://github.com/chaos-mesh/chaos-mesh/runs/7515016440?check_suite_focus=true)

**Comment by STRRL** [comment]
> @STRRL should I update swagger docs by myself? Re: [this job](https://github.com/chaos-mesh/chaos-mesh/runs/7515016440?check_suite_focus=true)

you could execute `make check` on your local machine,it would generate all the manifests files, then commit the changes.

**Pull request merged**
