### PR TITLE
JVMChaos: ignore AgentLoadException when install agent

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

### What problem does this PR solve?

fix issue https://github.com/chaos-mesh/chaos-mesh/issues/2690

### What's changed and how it works?

`install com.sun.tools.attach.AgentLoadException: 0` this error is caused by the different attach result codes in different java versions. In fact, the agent has attached success, just ignore it here.

refer to https://stackoverflow.com/questions/54340438/virtualmachine-attach-throws-com-sun-tools-attach-agentloadexception-0-when-usi/54454418#54454418

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by Andrewmatilde** [comment]
PTAL, @STRRL .

**Review by STRRL — APPROVED** [review]

**Comment by STRRL** [comment]
Should we cherry-pick this PR to `release-2.0` and `release-2.1`?

**Comment by WangXiangUSTC** [comment]
> Should we cherry-pick this PR to `release-2.0` and `release-2.1`? @WangXiangUSTC

need to cherry-pick to 2.1

**Pull request merged**
