### PR TITLE
migrate e2e test to gitub action on branch release-2.1

### PR DESCRIPTION
**Pull request by STRRL**
### What's changed and how it works?

- manually cherrypick #2985 and #2058 into release-2.1
- there is an extra configuration:
  - env `DOCKER_REGISTRY: ghcr.io` when building images, because release-2.1 still use `localhost:5000` as default  registry

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [x] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
I think this PR is ready for review.

After this PR merged, we could disable the Jenkins job.

PTAL 

/cc @cwen0 @YangKeao @Hexilee

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
