### PR TITLE
Remove unnecessary namespaceSelector from MutatingWebhookConfiguration

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Remove unnecessary `namespaceSelector` from `MutatingWebhookConfiguration`

### What is changed and how does it work?
Nothing changes from functionality point of view.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
Earlier #1565

**Comment by cwen0** [comment]
@anuragpaliwal80 I think this `namespaceSelector` is necessary for `JVMChaos`. You can refer this pr https://github.com/chaos-mesh/chaos-mesh/pull/1264. We need to use this `namespaceSelector` to limit the scope of injecting the JVM sidecar.  

@STRRL @YangKeao @Gallardot PTAL

**Comment by STRRL** [comment]
You are right @cwen0, we use a namespaceSelector to restrict the affected namespace, and that is depended by JVMChaos.

FYI @anuragpaliwal80, we could not remove that. 😰

**Comment by anuragpaliwal80** [comment]
No prob, lets close this PR.

**Pull request closed without merging**
