### PR TITLE
bump controller-gen to v0.6.2

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: xixi <i@hexilee.me>

### What problem does this PR solve?

The controller-gen v0.4.1 does not support the deprecated version.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by Hexilee** [comment]
PTAL @STRRL @YangKeao @Andrewmatilde

**Review by STRRL — CHANGES_REQUESTED** [review]
it requires to change our command line to call `controller-gen`, and it might not support crd-v1beta1 anymore.

at least please fix `IMAGE_DEV_ENV make check` on you local machine :)

PTAL

**Comment by Hexilee** [comment]
> it requires to change our command line to call `controller-gen`, and it might not support crd-v1beta1 anymore.
> 
> at least please fix `IMAGE_DEV_ENV make check` on you local machine :)
> 
> PTAL

I downgrade controller-gen to v0.6.2

**Comment by STRRL** [comment]
> > it requires to change our command line to call `controller-gen`, and it might not support crd-v1beta1 anymore.
> > at least please fix `IMAGE_DEV_ENV make check` on you local machine :)
> > PTAL
> 
> I downgrade controller-gen to v0.6.2, but it seems to still doesn't support the deprecated version.

Due to https://github.com/chaos-mesh/chaos-mesh/issues/3169, I think we should remove the support for CRD v1beta1.

I prefer to upgrade controller-gen to the latest version. :)

**Pull request closed without merging**
