### PR TITLE
Add a judgement of `enterNS` in `getAllInterfaces()`

### LINKED ISSUE #3458: `nsexec` must be triggered when `getAllInterfaces()` is called
## Bug Report

**What version of Chaos Mesh are you using?**
latest

**What did you do?**
Called `getAllInterfaces()`

**What did you expect to see?**
Normally run
**What did you see instead?**
`Chaosd` reported an error of "error while getting interfaces"

That is because `getAllInterfaces()` doesn't determine if `enterNS` is true, this causes `nsexec` to be called all the time

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: FingerLeader <wanxfinger@gmail.com>

### What problem does this PR solve?
Close #3458 

### What's changed and how it works?

Add a judgement of `enterNS` in `getAllInterfaces()`

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [x] release-2.2
  - [x] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### CODE REVIEW

**Comment by FingerLeader** [comment]
PTAL /cc @Andrewmatilde @YangKeao

**Review by cwen0 — APPROVED** [review]
Good Catch!

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
