### PR TITLE
fix: disable duration when chaos is instant

### LINKED ISSUE #2267: I can not setup "Schedule: @every 10s"  for PodChaos with pod-kill and contaienr-kill
## Bug Report

**What version of Kubernetes are you using?**

minkube 1.21
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

master branch
```
Controller manager Version: version.Info{GitVersion:"events-for-workflow-g25db3b4dcff36d", GitCommit:"25db3b4dcff36d5ea814b2bd59a0f693530d9bd8", BuildDate:"2021-08-31T09:59:54Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

I am trying to create `Schedule` with pod-kill on Chaos Dashboard.

**What did you expect to see?**

The `Schedule` could be created as expected.

**What did you see instead?**

Here is nowhere to set up field `schedule`, so I submit with failure.

image

image

(screenshot on the way)
**Output of chaosctl**

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What problem does this PR solve?

Issue Number: fix #2267

Problem Summary:
- I can not setup field `Scehedule` with pod-kill Podchaos

### What is changed and how it works?

What's Changed:

- move `isInstant()` into component `Scheduler`

### Related changes

* PR to update `chaos-mesh/website`/`chaos-mesh/website-zh`: No. 
* Need to update Chaos Dashboard component, related issue: No. 
* Need to cheery-pick to the release branch: No. 

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
I think we should move the `isInstant` function into `Scheduler.tsx` since the `pod-kill` and `container-kill` doesn't need to set the duration. And now I think that perhaps disabling input can make the user's perception a bit stronger than just removing it?

So in `Scheduler.tsx`:

```tsx
// line 27
const { fromExternal, kindAction, basic } = useStoreSelector((state) => state.experiments)
const [kind, action] = kindAction
const instant = isInstant(kind, action)

// line 61
label={T('newE.run.continuous')}
disabled={instant} // add this line

// line 93
      {!continuous && (
        <TextField
          // fast // remove this line
          name="spec.duration"
          label={T('common.duration')}
          validate={instant ? undefined : validateDuration()} // modify this line
          helperText={
            getIn(errors, 'spec.duration') && getIn(touched, 'spec.duration')
              ? getIn(errors, 'spec.duration')
              : T('common.durationHelper')
          }
          error={getIn(errors, 'spec.duration') && getIn(touched, 'spec.duration') ? true : false}
          disabled={instant} // add this line
        />
      )}
```

**Comment by STRRL** [comment]
OK! I will update the codes.

**Comment by STRRL** [comment]
updated! PTAL @g1eny0ung

**Review by g1eny0ung — APPROVED** [review]
LGTM! 🍻

**Review by fewdan — APPROVED** [review]
LGTM

**Pull request merged**
