### PR TITLE
multicluster: helm integration to install/upgrade Chaos Mesh in RemoteCluster

### PR DESCRIPTION
**Pull request by STRRL**
### What problem does this PR solve?

This PR has been rebased on https://github.com/chaos-mesh/chaos-mesh/pull/3342, so it contains a lot of changes.

The basic changes based on #3342 contain:

- pkg/helm

After #3342 merged, I would rebase this PR to branch master.

It's a part of #3341;

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [x] Manual test (add steps below)

I tested it manually by

- running example functions

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
/cc @YangKeao @FingerLeader 

I think this PR is ready for review. PTAL :)

**Comment by YangKeao** [comment]
https://github.com/chaos-mesh/chaos-mesh/pull/3384 @STRRL could you please update the PR to align with the master?

**Comment by cwen0** [comment]
> #3384 @STRRL could you please update the PR to align with the master?

@STRRL PTAL

**Comment by STRRL** [comment]
Updated! I think this PR is ready for review!

/cc @cwen0 @YangKeao

**Comment by cwen0** [comment]
@STRRL Can you fix the conflicts?

**Comment by STRRL** [comment]
> @STRRL Can you fix the conflicts?

Updated!

**Review by xlgao-zju — APPROVED** [review]
LGTM, and we need to fix the conflicts.

**Comment by cwen0** [comment]
@STRRL Can you fix the conflicts and make this pr mergeable?

**Comment by cwen0** [comment]
@STRRL Can you fix the conflicts?

**Comment by STRRL** [comment]
> @STRRL Can you fix the conflicts?

Done

**Pull request merged**
