### PR TITLE
Update FAQ for Openshift scc

### PR DESCRIPTION
**Pull request by Gallardot**
### What problem does this PR solve?

Reference from this issue #899  will be helpful to OpenShift users  
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by YangKeao** [comment]
The CI can be fixed by #904 . A workaround is to run it again :crying_cat_face:

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Pull request merged**
