### PR TITLE
fix: replaced localhost:5000 with ghcr.io as registry name

### LINKED ISSUE #2820: Use `ghcr.io` instead of `localhost:5000` when building images.
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

When we execute `make`, it would build docker images like `localhost:5000/chaos-mesh/chaos-mesh:latest`.  I want it to be like `ghcr.io/chaos-mesh/chaos-mesh:latest`, which would be the real and final artifacts we would publish and release. 

I think the build scripts should build the "production-ready" artifacts as default, and append other ENV or flags for other purposes. For example, using artifacts with the debugger as development is a kind of "other purpose", using artifacts in e2e test cases is another kind of "other purpose".

And there are many related hard-coded literal "localhost:5000" in e2e test and integration test codes/scripts, they are also need updates.

**Describe alternatives you've considered:**

Do not cherry-pick these related changes into release-2.0 and release-2.1.

No other alternatives.

**Teachability, Documentation, Adoption, Migration Strategy:**

No other references.

### PR DESCRIPTION
**Pull request by rohankmr414**
Signed-off-by: Rohan Kumar <rohankmr414@gmail.com>

### What problem does this PR solve?

Close #2820

### What's changed and how it works?
hard-coded literal `localhost:5000` in Makefile, e2e tests and integration test codes/scripts replaced with `ghcr.io`

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [x] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by Andrewmatilde** [comment]
I think this change may break e2e-test.

**Review by Andrewmatilde — APPROVED** [review]
LGTM It works well.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
