### PR TITLE
removed namespace field

### PR DESCRIPTION
**Pull request by dmallya**
### What problem does this PR solve?
The namespace in the YAML files in the example folder can now be overwritten through Kubernetes Command Line.

close https://github.com/chaos-mesh/chaos-mesh/issues/2819

### What's changed and how it works?

Removed Namespace in YAML Files.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

### CODE REVIEW

**Comment by iguoyr** [comment]
@dmallya Hi, you need to fix `DCO` check first, you could refer to [CONTRIBUTING.md](https://github.com/chaos-mesh/chaos-mesh/blob/master/CONTRIBUTING.md#step-4-commit-and-push-your-changes) :)

**Review by STRRL — COMMENTED** [review]
LGTM!

Thanks for your contribution!

**Review by STRRL — APPROVED** [review]

**Review by iguoyr — APPROVED** [review]
LGTM

**Pull request merged**
