### PR TITLE
feat: add option to toggle metric scraping of chaos-daemon

### PR DESCRIPTION
**Pull request by chris-ng-scmp**
## What problem does this PR solve?

HELM chart has no option to disable metrics scraping for chaos-daemon service

## What's changed and how it works?

Add new value and update service template to have an option to toggle the annotation

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [x] release-2.7
- [x] release-2.6

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by chris-ng-scmp** [comment]
@g1eny0ung Would you mind to have a look on this PR? Many thanks

**Review by g1eny0ung — APPROVED** [review]
LGTM! Thank you for your contribution!

**Pull request merged**
