### PR TITLE
ci: setup new CI for finding merge conflicts

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <im@strrl.dev>

### What problem does this PR solve?

close https://github.com/chaos-mesh/chaos-mesh/issues/3806

### What's changed and how it works?

- using https://github.com/marketplace/actions/merge-conflict-finder
- because merge conflicts could easily funded by searching `<<<<<` , so I do not let this certain action need necessary on  the dev machine.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [x] release-2.5
  - [x] release-2.4

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by g1eny0ung — COMMENTED** [review]
Shall this workflow need to cherry-pick into the `v2.5` and `v2.4` branches? I think it should be. Right?

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
