### PR TITLE
chore: fix bug report issue template

### LINKED ISSUE #4508: Issue Template Not works well
When I try to create a new issue for Chaos Mesh, the "bug report" option is not available in issue template:

image

image

### PR DESCRIPTION
**Pull request by STRRL**
## What problem does this PR solve?

close #4508

## What's changed and how it works?

update issue template file for bug report

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [x] release-2.7
- [x] release-2.6

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below to fix it:

> [!TIP]
> Depends on actual situations, for example, if the failed commit isn't the most recent
> one, you can use `git rebase -i HEAD~n` to re-signoff the commit.

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
Hi @g1eny0ung  PTAL

**Review by g1eny0ung — APPROVED** [review]
LGTM!

**Pull request merged**
