### PR TITLE
feat: support more rate units for networkchaos/bandwidth

### PR DESCRIPTION
**Pull request by cwen0**
## What problem does this PR solve?

 

Support bit unit for network bandwidth action. 

## What's changed and how it works?

 

Change rate type from unint64 to string

## Related changes

- [x] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs) 
- [ ] This change also requires further updates to the `UI interface`

docs pr: https://github.com/chaos-mesh/website/pull/397/files

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

### CHANGELOG

> Must include at least one of them.

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [x] Unit test
- [ ] E2E test
- [ ] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by g1eny0ung** [comment]
@cwen0 Will review this PR within the next two days. BTW, do you have time to update the docs as well? Our work can be synchronized

**Review by g1eny0ung — APPROVED** [review]
Basically LGTM.

@cwen0 I have one more question. Do we need to update the `peakrate` as well to ensure consistency between the units of these two fields?

**Comment by cwen0** [comment]
> Basically LGTM.
> 
> @cwen0 I have one more question. Do we need to update the `peakrate` as well to ensure consistency between the units of these two fields?

Good! I think it also needs to be updated, and I will update it asap.

**Comment by cwen0** [comment]
> Basically LGTM.
> 
> @cwen0 I have one more question. Do we need to update the `peakrate` as well to ensure consistency between the units of these two fields? 

@g1eny0ung  `peakrate` change will break compatibility. So we shouldn't update it here.  I will merge this pr now.

**Comment by g1eny0ung** [comment]
> > Basically LGTM.
> > @cwen0 I have one more question. Do we need to update the `peakrate` as well to ensure consistency between the units of these two fields?
> 
> @g1eny0ung `peakrate` change will break compatibility. So we shouldn't update it here. I will merge this pr now.

Understood. The `/merge` command is currently unavailable. Instead, only other maintainers can add the `lgtm` tag to the PR before it can be merged.

**Pull request merged**
