### PR TITLE
feat: remove helm v2 tiller and use helm 3.5.3 as default

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### What is changed and how does it work?
It's a part of https://github.com/chaos-mesh/chaos-mesh/issues/1187.

- As helm v2 has been marked as deprecated, we should use helm v3.
- Compatibility issue with `timeoutSeconds` in mutating webhook configurations
- It executes e2e test on the multi kubernetes version, 1.20.2 and 1.12.10.

Ref: 
https://github.com/kubernetes/kubernetes/pull/74562,
https://github.com/liggitt/enhancements/blob/master/keps/sig-api-machinery/492-admission-webhooks/README.md#v1beta1-changes,
https://helm.sh/blog/helm-v2-deprecation-timeline/

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by AsterNighT — COMMENTED** [review]
btw, e2e test still takes around 22 mins to finish (on success), which is twice the time compared to integration test. Any chance that we can run e2e tests concurrently?

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
> btw, e2e test still takes around 22 mins to finish (on success), which is twice the time compared to integration test. Any chance that we can run e2e tests concurrently?

It's time to update the cache of e2e test. If the cache is available, it will take nearly 16min. (And I will also write up a document about how to update the cache. It will not update automatically now.)

**Comment by STRRL** [comment]
> And I will also write up a document about how to update the cache. It will not update automatically now.

Where are the documents? 🙈

**Comment by STRRL** [comment]
/merge

Does our robot support more words under the commands?

**Pull request merged**
