### PR TITLE
Bump version to v2.3.1

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
LGTM

**Review by g1eny0ung — CHANGES_REQUESTED** [review]
It still needs to update `Chart.yaml` and `install.sh`.

**Comment by cwen0** [comment]
> It still needs to update `Chart.yaml` and `install.sh`.

`install.sh` will be update in GitHub action https://github.com/chaos-mesh/chaos-mesh/blob/30b0037a3f1a3cacdd3137efae5321f3b6be6275/.github/workflows/upload_release_files.yml#L49-L53

**Comment by g1eny0ung** [comment]
> > It still needs to update `Chart.yaml` and `install.sh`.
> 
> `install.sh` will be update in GitHub action
> 
> https://github.com/chaos-mesh/chaos-mesh/blob/30b0037a3f1a3cacdd3137efae5321f3b6be6275/.github/workflows/upload_release_files.yml#L49-L53

Got it! What about `Chart.yaml`?

**Comment by cwen0** [comment]
> > > It still needs to update `Chart.yaml` and `install.sh`.
> > 
> > 
> > `install.sh` will be update in GitHub action
> > https://github.com/chaos-mesh/chaos-mesh/blob/30b0037a3f1a3cacdd3137efae5321f3b6be6275/.github/workflows/upload_release_files.yml#L49-L53
> 
> Got it! What about `Chart.yaml`?

You can refer to this pr https://github.com/chaos-mesh/chaos-mesh/pull/3293

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Comment by g1eny0ung** [comment]
> > > > It still needs to update `Chart.yaml` and `install.sh`.
> > > 
> > > 
> > > `install.sh` will be update in GitHub action
> > > https://github.com/chaos-mesh/chaos-mesh/blob/30b0037a3f1a3cacdd3137efae5321f3b6be6275/.github/workflows/upload_release_files.yml#L49-L53
> > 
> > 
> > Got it! What about `Chart.yaml`?
> 
> You can refer to this pr #3293

A wonderful change! Now I understand all.

**Pull request merged**
