### PR TITLE
chore: update CHANGELOG for released 2.3.0

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <im@strrl.dev>

### What problem does this PR solve?

N/A

### What's changed and how it works?

- update CHANGELOG in branch `master` for Chaos Mesh 2.3.0

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.3
  - [ ] release-2.2
  - [ ] release-2.1

### Checklist

CHANGELOG

- [x] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL 

/cc @YangKeao @Hexilee @cwen0

**Review by g1eny0ung — CHANGES_REQUESTED** [review]
### Added

- Support `KernelChaos` in `AutoForm` [#3449](https://github.com/chaos-mesh/chaos-mesh/pull/3449)

This is also not cherry-picked into 2.3.

**Review by g1eny0ung — APPROVED** [review]

**Comment by g1eny0ung** [comment]
> ### Added
> * Support `KernelChaos` in `AutoForm` [#3449](https://github.com/chaos-mesh/chaos-mesh/pull/3449)
> 
> This is also not cherry-picked into 2.3.

Sorry, I misread it.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
