### PR TITLE
Fix size percentile issue in memory stress

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
### What problem does this PR solve?

Fix size percentile issue in memory stress

If user specifies the size in %, it will not work. 
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
Verified at https://play.golang.org/p/Nj0WqnHk-0o

**Review by Hexilee — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
