### PR TITLE
feat(ui): add storybook for testing

### PR DESCRIPTION
**Pull request by g1eny0ung**
Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

After talking with @STRRL, we would like to introduce a place to test common UI components. Currently, [storybook](https://storybook.js.org/) is the best choice that can provide a sandbox to build UIs in isolation.

### What's changed and how it works?

1. Add storybook as dev dependencies
2. **I have kept some default examples for some reference**
3. Add `TextField` and `SelectFeild` for testing

> Note:
>
> It's needed to run `yarn workspace @ui/mui-extends build` before `yarn workspace @ui/mui-extends storybook` due to the stories relying on the `esm` builds, not source code.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

### CODE REVIEW

**Review by STRRL — APPROVED** [review]
That's awesome!

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
